[pytest]
filterwarnings =
    # treat all warnings as errors
    error
    ignore:.*Please upgrade to the latest Python version.*:FutureWarning
    ignore:(?s).*using a Python version.*past its end of life.*:FutureWarning
