# -*- coding: utf-8 -*-
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.netapp_v1 import gapic_version as package_version

__version__ = package_version.__version__


from .services.net_app import NetAppAsyncClient, NetAppClient
from .types.active_directory import (
    ActiveDirectory,
    CreateActiveDirectoryRequest,
    DeleteActiveDirectoryRequest,
    GetActiveDirectoryRequest,
    ListActiveDirectoriesRequest,
    ListActiveDirectoriesResponse,
    UpdateActiveDirectoryRequest,
)
from .types.backup import (
    Backup,
    CreateBackupRequest,
    DeleteBackupRequest,
    GetBackupRequest,
    ListBackupsRequest,
    ListBackupsResponse,
    UpdateBackupRequest,
)
from .types.backup_policy import (
    BackupPolicy,
    CreateBackupPolicyRequest,
    DeleteBackupPolicyRequest,
    GetBackupPolicyRequest,
    ListBackupPoliciesRequest,
    ListBackupPoliciesResponse,
    UpdateBackupPolicyRequest,
)
from .types.backup_vault import (
    BackupVault,
    CreateBackupVaultRequest,
    DeleteBackupVaultRequest,
    GetBackupVaultRequest,
    ListBackupVaultsRequest,
    ListBackupVaultsResponse,
    UpdateBackupVaultRequest,
)
from .types.cloud_netapp_service import OperationMetadata
from .types.common import EncryptionType, LocationMetadata, ServiceLevel
from .types.kms import (
    CreateKmsConfigRequest,
    DeleteKmsConfigRequest,
    EncryptVolumesRequest,
    GetKmsConfigRequest,
    KmsConfig,
    ListKmsConfigsRequest,
    ListKmsConfigsResponse,
    UpdateKmsConfigRequest,
    VerifyKmsConfigRequest,
    VerifyKmsConfigResponse,
)
from .types.replication import (
    CreateReplicationRequest,
    DeleteReplicationRequest,
    DestinationVolumeParameters,
    GetReplicationRequest,
    ListReplicationsRequest,
    ListReplicationsResponse,
    Replication,
    ResumeReplicationRequest,
    ReverseReplicationDirectionRequest,
    StopReplicationRequest,
    TransferStats,
    UpdateReplicationRequest,
)
from .types.snapshot import (
    CreateSnapshotRequest,
    DeleteSnapshotRequest,
    GetSnapshotRequest,
    ListSnapshotsRequest,
    ListSnapshotsResponse,
    Snapshot,
    UpdateSnapshotRequest,
)
from .types.storage_pool import (
    CreateStoragePoolRequest,
    DeleteStoragePoolRequest,
    GetStoragePoolRequest,
    ListStoragePoolsRequest,
    ListStoragePoolsResponse,
    StoragePool,
    UpdateStoragePoolRequest,
)
from .types.volume import (
    AccessType,
    BackupConfig,
    CreateVolumeRequest,
    DailySchedule,
    DeleteVolumeRequest,
    ExportPolicy,
    GetVolumeRequest,
    HourlySchedule,
    ListVolumesRequest,
    ListVolumesResponse,
    MonthlySchedule,
    MountOption,
    Protocols,
    RestoreParameters,
    RestrictedAction,
    RevertVolumeRequest,
    SecurityStyle,
    SimpleExportPolicyRule,
    SMBSettings,
    SnapshotPolicy,
    TieringPolicy,
    UpdateVolumeRequest,
    Volume,
    WeeklySchedule,
)

__all__ = (
    "NetAppAsyncClient",
    "AccessType",
    "ActiveDirectory",
    "Backup",
    "BackupConfig",
    "BackupPolicy",
    "BackupVault",
    "CreateActiveDirectoryRequest",
    "CreateBackupPolicyRequest",
    "CreateBackupRequest",
    "CreateBackupVaultRequest",
    "CreateKmsConfigRequest",
    "CreateReplicationRequest",
    "CreateSnapshotRequest",
    "CreateStoragePoolRequest",
    "CreateVolumeRequest",
    "DailySchedule",
    "DeleteActiveDirectoryRequest",
    "DeleteBackupPolicyRequest",
    "DeleteBackupRequest",
    "DeleteBackupVaultRequest",
    "DeleteKmsConfigRequest",
    "DeleteReplicationRequest",
    "DeleteSnapshotRequest",
    "DeleteStoragePoolRequest",
    "DeleteVolumeRequest",
    "DestinationVolumeParameters",
    "EncryptVolumesRequest",
    "EncryptionType",
    "ExportPolicy",
    "GetActiveDirectoryRequest",
    "GetBackupPolicyRequest",
    "GetBackupRequest",
    "GetBackupVaultRequest",
    "GetKmsConfigRequest",
    "GetReplicationRequest",
    "GetSnapshotRequest",
    "GetStoragePoolRequest",
    "GetVolumeRequest",
    "HourlySchedule",
    "KmsConfig",
    "ListActiveDirectoriesRequest",
    "ListActiveDirectoriesResponse",
    "ListBackupPoliciesRequest",
    "ListBackupPoliciesResponse",
    "ListBackupVaultsRequest",
    "ListBackupVaultsResponse",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ListKmsConfigsRequest",
    "ListKmsConfigsResponse",
    "ListReplicationsRequest",
    "ListReplicationsResponse",
    "ListSnapshotsRequest",
    "ListSnapshotsResponse",
    "ListStoragePoolsRequest",
    "ListStoragePoolsResponse",
    "ListVolumesRequest",
    "ListVolumesResponse",
    "LocationMetadata",
    "MonthlySchedule",
    "MountOption",
    "NetAppClient",
    "OperationMetadata",
    "Protocols",
    "Replication",
    "RestoreParameters",
    "RestrictedAction",
    "ResumeReplicationRequest",
    "ReverseReplicationDirectionRequest",
    "RevertVolumeRequest",
    "SMBSettings",
    "SecurityStyle",
    "ServiceLevel",
    "SimpleExportPolicyRule",
    "Snapshot",
    "SnapshotPolicy",
    "StopReplicationRequest",
    "StoragePool",
    "TieringPolicy",
    "TransferStats",
    "UpdateActiveDirectoryRequest",
    "UpdateBackupPolicyRequest",
    "UpdateBackupRequest",
    "UpdateBackupVaultRequest",
    "UpdateKmsConfigRequest",
    "UpdateReplicationRequest",
    "UpdateSnapshotRequest",
    "UpdateStoragePoolRequest",
    "UpdateVolumeRequest",
    "VerifyKmsConfigRequest",
    "VerifyKmsConfigResponse",
    "Volume",
    "WeeklySchedule",
)
