# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.netapp_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.netapp_v1.services.net_app",
    "google.cloud.netapp_v1.types.active_directory",
    "google.cloud.netapp_v1.types.backup",
    "google.cloud.netapp_v1.types.backup_policy",
    "google.cloud.netapp_v1.types.backup_vault",
    "google.cloud.netapp_v1.types.cloud_netapp_service",
    "google.cloud.netapp_v1.types.common",
    "google.cloud.netapp_v1.types.host_group",
    "google.cloud.netapp_v1.types.kms",
    "google.cloud.netapp_v1.types.ontap",
    "google.cloud.netapp_v1.types.quota_rule",
    "google.cloud.netapp_v1.types.replication",
    "google.cloud.netapp_v1.types.snapshot",
    "google.cloud.netapp_v1.types.storage_pool",
    "google.cloud.netapp_v1.types.volume",
}


from .services.net_app import NetAppAsyncClient, NetAppClient
from .types.active_directory import (
    ActiveDirectory,
    CreateActiveDirectoryRequest,
    DeleteActiveDirectoryRequest,
    GetActiveDirectoryRequest,
    ListActiveDirectoriesRequest,
    ListActiveDirectoriesResponse,
    UpdateActiveDirectoryRequest,
)
from .types.backup import (
    Backup,
    CreateBackupRequest,
    DeleteBackupRequest,
    GetBackupRequest,
    ListBackupsRequest,
    ListBackupsResponse,
    UpdateBackupRequest,
)
from .types.backup_policy import (
    BackupPolicy,
    CreateBackupPolicyRequest,
    DeleteBackupPolicyRequest,
    GetBackupPolicyRequest,
    ListBackupPoliciesRequest,
    ListBackupPoliciesResponse,
    UpdateBackupPolicyRequest,
)
from .types.backup_vault import (
    BackupVault,
    CreateBackupVaultRequest,
    DeleteBackupVaultRequest,
    GetBackupVaultRequest,
    ListBackupVaultsRequest,
    ListBackupVaultsResponse,
    UpdateBackupVaultRequest,
)
from .types.cloud_netapp_service import OperationMetadata
from .types.common import (
    DirectoryServiceType,
    EncryptionType,
    FlexPerformance,
    HybridReplicationSchedule,
    LocationMetadata,
    OsType,
    QosType,
    ScaleType,
    ServiceLevel,
    StoragePoolType,
    UserCommands,
)
from .types.host_group import (
    CreateHostGroupRequest,
    DeleteHostGroupRequest,
    GetHostGroupRequest,
    HostGroup,
    ListHostGroupsRequest,
    ListHostGroupsResponse,
    UpdateHostGroupRequest,
)
from .types.kms import (
    CreateKmsConfigRequest,
    DeleteKmsConfigRequest,
    EncryptVolumesRequest,
    GetKmsConfigRequest,
    KmsConfig,
    ListKmsConfigsRequest,
    ListKmsConfigsResponse,
    UpdateKmsConfigRequest,
    VerifyKmsConfigRequest,
    VerifyKmsConfigResponse,
)
from .types.ontap import (
    ExecuteOntapDeleteRequest,
    ExecuteOntapDeleteResponse,
    ExecuteOntapGetRequest,
    ExecuteOntapGetResponse,
    ExecuteOntapPatchRequest,
    ExecuteOntapPatchResponse,
    ExecuteOntapPostRequest,
    ExecuteOntapPostResponse,
)
from .types.quota_rule import (
    CreateQuotaRuleRequest,
    DeleteQuotaRuleRequest,
    GetQuotaRuleRequest,
    ListQuotaRulesRequest,
    ListQuotaRulesResponse,
    QuotaRule,
    UpdateQuotaRuleRequest,
)
from .types.replication import (
    CreateReplicationRequest,
    DeleteReplicationRequest,
    DestinationVolumeParameters,
    EstablishPeeringRequest,
    GetReplicationRequest,
    HybridPeeringDetails,
    ListReplicationsRequest,
    ListReplicationsResponse,
    Replication,
    ResumeReplicationRequest,
    ReverseReplicationDirectionRequest,
    StopReplicationRequest,
    SyncReplicationRequest,
    TransferStats,
    UpdateReplicationRequest,
)
from .types.snapshot import (
    CreateSnapshotRequest,
    DeleteSnapshotRequest,
    GetSnapshotRequest,
    ListSnapshotsRequest,
    ListSnapshotsResponse,
    Snapshot,
    UpdateSnapshotRequest,
)
from .types.storage_pool import (
    CreateStoragePoolRequest,
    DeleteStoragePoolRequest,
    GetStoragePoolRequest,
    ListStoragePoolsRequest,
    ListStoragePoolsResponse,
    Mode,
    StoragePool,
    SwitchActiveReplicaZoneRequest,
    UpdateStoragePoolRequest,
    ValidateDirectoryServiceRequest,
)
from .types.volume import (
    AccessType,
    BackupConfig,
    BlockDevice,
    CacheConfig,
    CacheParameters,
    CachePrePopulate,
    CreateVolumeRequest,
    DailySchedule,
    DeleteVolumeRequest,
    EstablishVolumePeeringRequest,
    ExportPolicy,
    GetVolumeRequest,
    HourlySchedule,
    HybridReplicationParameters,
    LargeCapacityConfig,
    ListVolumesRequest,
    ListVolumesResponse,
    MonthlySchedule,
    MountOption,
    Protocols,
    RestoreBackupFilesRequest,
    RestoreBackupFilesResponse,
    RestoreParameters,
    RestrictedAction,
    RevertVolumeRequest,
    SecurityStyle,
    SimpleExportPolicyRule,
    SMBSettings,
    SnapshotPolicy,
    TieringPolicy,
    UpdateVolumeRequest,
    Volume,
    WeeklySchedule,
)

__all__ = (
    "NetAppAsyncClient",
    "AccessType",
    "ActiveDirectory",
    "Backup",
    "BackupConfig",
    "BackupPolicy",
    "BackupVault",
    "BlockDevice",
    "CacheConfig",
    "CacheParameters",
    "CachePrePopulate",
    "CreateActiveDirectoryRequest",
    "CreateBackupPolicyRequest",
    "CreateBackupRequest",
    "CreateBackupVaultRequest",
    "CreateHostGroupRequest",
    "CreateKmsConfigRequest",
    "CreateQuotaRuleRequest",
    "CreateReplicationRequest",
    "CreateSnapshotRequest",
    "CreateStoragePoolRequest",
    "CreateVolumeRequest",
    "DailySchedule",
    "DeleteActiveDirectoryRequest",
    "DeleteBackupPolicyRequest",
    "DeleteBackupRequest",
    "DeleteBackupVaultRequest",
    "DeleteHostGroupRequest",
    "DeleteKmsConfigRequest",
    "DeleteQuotaRuleRequest",
    "DeleteReplicationRequest",
    "DeleteSnapshotRequest",
    "DeleteStoragePoolRequest",
    "DeleteVolumeRequest",
    "DestinationVolumeParameters",
    "DirectoryServiceType",
    "EncryptVolumesRequest",
    "EncryptionType",
    "EstablishPeeringRequest",
    "EstablishVolumePeeringRequest",
    "ExecuteOntapDeleteRequest",
    "ExecuteOntapDeleteResponse",
    "ExecuteOntapGetRequest",
    "ExecuteOntapGetResponse",
    "ExecuteOntapPatchRequest",
    "ExecuteOntapPatchResponse",
    "ExecuteOntapPostRequest",
    "ExecuteOntapPostResponse",
    "ExportPolicy",
    "FlexPerformance",
    "GetActiveDirectoryRequest",
    "GetBackupPolicyRequest",
    "GetBackupRequest",
    "GetBackupVaultRequest",
    "GetHostGroupRequest",
    "GetKmsConfigRequest",
    "GetQuotaRuleRequest",
    "GetReplicationRequest",
    "GetSnapshotRequest",
    "GetStoragePoolRequest",
    "GetVolumeRequest",
    "HostGroup",
    "HourlySchedule",
    "HybridPeeringDetails",
    "HybridReplicationParameters",
    "HybridReplicationSchedule",
    "KmsConfig",
    "LargeCapacityConfig",
    "ListActiveDirectoriesRequest",
    "ListActiveDirectoriesResponse",
    "ListBackupPoliciesRequest",
    "ListBackupPoliciesResponse",
    "ListBackupVaultsRequest",
    "ListBackupVaultsResponse",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ListHostGroupsRequest",
    "ListHostGroupsResponse",
    "ListKmsConfigsRequest",
    "ListKmsConfigsResponse",
    "ListQuotaRulesRequest",
    "ListQuotaRulesResponse",
    "ListReplicationsRequest",
    "ListReplicationsResponse",
    "ListSnapshotsRequest",
    "ListSnapshotsResponse",
    "ListStoragePoolsRequest",
    "ListStoragePoolsResponse",
    "ListVolumesRequest",
    "ListVolumesResponse",
    "LocationMetadata",
    "Mode",
    "MonthlySchedule",
    "MountOption",
    "NetAppClient",
    "OperationMetadata",
    "OsType",
    "Protocols",
    "QosType",
    "QuotaRule",
    "Replication",
    "RestoreBackupFilesRequest",
    "RestoreBackupFilesResponse",
    "RestoreParameters",
    "RestrictedAction",
    "ResumeReplicationRequest",
    "ReverseReplicationDirectionRequest",
    "RevertVolumeRequest",
    "SMBSettings",
    "ScaleType",
    "SecurityStyle",
    "ServiceLevel",
    "SimpleExportPolicyRule",
    "Snapshot",
    "SnapshotPolicy",
    "StopReplicationRequest",
    "StoragePool",
    "StoragePoolType",
    "SwitchActiveReplicaZoneRequest",
    "SyncReplicationRequest",
    "TieringPolicy",
    "TransferStats",
    "UpdateActiveDirectoryRequest",
    "UpdateBackupPolicyRequest",
    "UpdateBackupRequest",
    "UpdateBackupVaultRequest",
    "UpdateHostGroupRequest",
    "UpdateKmsConfigRequest",
    "UpdateQuotaRuleRequest",
    "UpdateReplicationRequest",
    "UpdateSnapshotRequest",
    "UpdateStoragePoolRequest",
    "UpdateVolumeRequest",
    "UserCommands",
    "ValidateDirectoryServiceRequest",
    "VerifyKmsConfigRequest",
    "VerifyKmsConfigResponse",
    "Volume",
    "WeeklySchedule",
)

api_core.check_python_version("google.cloud.netapp_v1")
api_core.check_dependency_versions("google.cloud.netapp_v1")
