# -*- coding: utf-8 -*-
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.backupdr import gapic_version as package_version

__version__ = package_version.__version__


from google.cloud.backupdr_v1.services.backup_dr.async_client import BackupDRAsyncClient
from google.cloud.backupdr_v1.services.backup_dr.client import BackupDRClient
from google.cloud.backupdr_v1.types.backupdr import (
    CreateManagementServerRequest,
    DeleteManagementServerRequest,
    GetManagementServerRequest,
    ListManagementServersRequest,
    ListManagementServersResponse,
    ManagementServer,
    ManagementURI,
    NetworkConfig,
    OperationMetadata,
    WorkforceIdentityBasedManagementURI,
    WorkforceIdentityBasedOAuth2ClientID,
)
from google.cloud.backupdr_v1.types.backupplan import (
    BackupPlan,
    BackupRule,
    BackupWindow,
    CreateBackupPlanRequest,
    DeleteBackupPlanRequest,
    GetBackupPlanRequest,
    ListBackupPlansRequest,
    ListBackupPlansResponse,
    StandardSchedule,
    WeekDayOfMonth,
)
from google.cloud.backupdr_v1.types.backupplanassociation import (
    BackupPlanAssociation,
    CreateBackupPlanAssociationRequest,
    DeleteBackupPlanAssociationRequest,
    GetBackupPlanAssociationRequest,
    ListBackupPlanAssociationsRequest,
    ListBackupPlanAssociationsResponse,
    RuleConfigInfo,
    TriggerBackupRequest,
)
from google.cloud.backupdr_v1.types.backupvault import (
    Backup,
    BackupApplianceBackupConfig,
    BackupApplianceLockInfo,
    BackupConfigInfo,
    BackupConfigState,
    BackupLock,
    BackupVault,
    BackupVaultView,
    BackupView,
    CreateBackupVaultRequest,
    DataSource,
    DataSourceBackupApplianceApplication,
    DataSourceGcpResource,
    DeleteBackupRequest,
    DeleteBackupVaultRequest,
    FetchUsableBackupVaultsRequest,
    FetchUsableBackupVaultsResponse,
    GcpBackupConfig,
    GcpResource,
    GetBackupRequest,
    GetBackupVaultRequest,
    GetDataSourceRequest,
    ListBackupsRequest,
    ListBackupsResponse,
    ListBackupVaultsRequest,
    ListBackupVaultsResponse,
    ListDataSourcesRequest,
    ListDataSourcesResponse,
    RestoreBackupRequest,
    RestoreBackupResponse,
    ServiceLockInfo,
    TargetResource,
    UpdateBackupRequest,
    UpdateBackupVaultRequest,
    UpdateDataSourceRequest,
)
from google.cloud.backupdr_v1.types.backupvault_ba import (
    BackupApplianceBackupProperties,
)
from google.cloud.backupdr_v1.types.backupvault_gce import (
    AcceleratorConfig,
    AccessConfig,
    AdvancedMachineFeatures,
    AliasIpRange,
    AllocationAffinity,
    AttachedDisk,
    ComputeInstanceBackupProperties,
    ComputeInstanceDataSourceProperties,
    ComputeInstanceRestoreProperties,
    ComputeInstanceTargetEnvironment,
    ConfidentialInstanceConfig,
    CustomerEncryptionKey,
    DisplayDevice,
    Entry,
    GuestOsFeature,
    InstanceParams,
    KeyRevocationActionType,
    Metadata,
    NetworkInterface,
    NetworkPerformanceConfig,
    Scheduling,
    SchedulingDuration,
    ServiceAccount,
    Tags,
)

__all__ = (
    "BackupDRClient",
    "BackupDRAsyncClient",
    "CreateManagementServerRequest",
    "DeleteManagementServerRequest",
    "GetManagementServerRequest",
    "ListManagementServersRequest",
    "ListManagementServersResponse",
    "ManagementServer",
    "ManagementURI",
    "NetworkConfig",
    "OperationMetadata",
    "WorkforceIdentityBasedManagementURI",
    "WorkforceIdentityBasedOAuth2ClientID",
    "BackupPlan",
    "BackupRule",
    "BackupWindow",
    "CreateBackupPlanRequest",
    "DeleteBackupPlanRequest",
    "GetBackupPlanRequest",
    "ListBackupPlansRequest",
    "ListBackupPlansResponse",
    "StandardSchedule",
    "WeekDayOfMonth",
    "BackupPlanAssociation",
    "CreateBackupPlanAssociationRequest",
    "DeleteBackupPlanAssociationRequest",
    "GetBackupPlanAssociationRequest",
    "ListBackupPlanAssociationsRequest",
    "ListBackupPlanAssociationsResponse",
    "RuleConfigInfo",
    "TriggerBackupRequest",
    "Backup",
    "BackupApplianceBackupConfig",
    "BackupApplianceLockInfo",
    "BackupConfigInfo",
    "BackupLock",
    "BackupVault",
    "CreateBackupVaultRequest",
    "DataSource",
    "DataSourceBackupApplianceApplication",
    "DataSourceGcpResource",
    "DeleteBackupRequest",
    "DeleteBackupVaultRequest",
    "FetchUsableBackupVaultsRequest",
    "FetchUsableBackupVaultsResponse",
    "GcpBackupConfig",
    "GcpResource",
    "GetBackupRequest",
    "GetBackupVaultRequest",
    "GetDataSourceRequest",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ListBackupVaultsRequest",
    "ListBackupVaultsResponse",
    "ListDataSourcesRequest",
    "ListDataSourcesResponse",
    "RestoreBackupRequest",
    "RestoreBackupResponse",
    "ServiceLockInfo",
    "TargetResource",
    "UpdateBackupRequest",
    "UpdateBackupVaultRequest",
    "UpdateDataSourceRequest",
    "BackupConfigState",
    "BackupVaultView",
    "BackupView",
    "BackupApplianceBackupProperties",
    "AcceleratorConfig",
    "AccessConfig",
    "AdvancedMachineFeatures",
    "AliasIpRange",
    "AllocationAffinity",
    "AttachedDisk",
    "ComputeInstanceBackupProperties",
    "ComputeInstanceDataSourceProperties",
    "ComputeInstanceRestoreProperties",
    "ComputeInstanceTargetEnvironment",
    "ConfidentialInstanceConfig",
    "CustomerEncryptionKey",
    "DisplayDevice",
    "Entry",
    "GuestOsFeature",
    "InstanceParams",
    "Metadata",
    "NetworkInterface",
    "NetworkPerformanceConfig",
    "Scheduling",
    "SchedulingDuration",
    "ServiceAccount",
    "Tags",
    "KeyRevocationActionType",
)
