# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.geminidataanalytics_v1beta import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.geminidataanalytics_v1beta.services.data_a2a_service",
    "google.cloud.geminidataanalytics_v1beta.services.data_agent_service",
    "google.cloud.geminidataanalytics_v1beta.services.data_chat_service",
    "google.cloud.geminidataanalytics_v1beta.types.agent_context",
    "google.cloud.geminidataanalytics_v1beta.types.context",
    "google.cloud.geminidataanalytics_v1beta.types.conversation",
    "google.cloud.geminidataanalytics_v1beta.types.credentials",
    "google.cloud.geminidataanalytics_v1beta.types.data_a2a_service",
    "google.cloud.geminidataanalytics_v1beta.types.data_agent",
    "google.cloud.geminidataanalytics_v1beta.types.data_agent_service",
    "google.cloud.geminidataanalytics_v1beta.types.data_analytics_agent",
    "google.cloud.geminidataanalytics_v1beta.types.data_chat_service",
    "google.cloud.geminidataanalytics_v1beta.types.datasource",
    "google.cloud.geminidataanalytics_v1beta.types.usage",
}


from .services.data_a2a_service import DataA2AServiceAsyncClient, DataA2AServiceClient
from .services.data_agent_service import (
    DataAgentServiceAsyncClient,
    DataAgentServiceClient,
)
from .services.data_chat_service import (
    DataChatServiceAsyncClient,
    DataChatServiceClient,
)
from .types.agent_context import AgentContextReference
from .types.context import (
    AnalysisOptions,
    BigQueryRoutine,
    BigQueryRoutineReference,
    ChartOptions,
    Citation,
    CitationAnchor,
    CitationSource,
    Context,
    ConversationOptions,
    DatasourceOptions,
    DynamicField,
    ExampleQuery,
    GlossaryTerm,
    LookerGoldenQuery,
    LookerQuery,
    MatchedQuery,
    QueryParameter,
    QueryParameterValues,
    UserFunctions,
)
from .types.conversation import (
    Conversation,
    CreateConversationRequest,
    DeleteConversationRequest,
    GetConversationRequest,
    ListConversationsRequest,
    ListConversationsResponse,
    UpdateConversationRequest,
)
from .types.credentials import Credentials, OAuthCredentials
from .types.data_a2a_service import (
    A2AArtifact,
    A2AMessage,
    A2ATask,
    AgentCapabilities,
    AgentCard,
    AgentCardSignature,
    AgentExtension,
    AgentInterface,
    AgentProvider,
    AgentSkill,
    APIKeySecurityScheme,
    AuthenticationInfo,
    AuthorizationCodeOAuthFlow,
    ClientCredentialsOAuthFlow,
    DataPart,
    FilePart,
    GetAgentCardRequest,
    HTTPAuthSecurityScheme,
    ImplicitOAuthFlow,
    MutualTlsSecurityScheme,
    OAuth2SecurityScheme,
    OAuthFlows,
    OpenIdConnectSecurityScheme,
    Part,
    PasswordOAuthFlow,
    PushNotificationConfig,
    Role,
    Security,
    SecurityScheme,
    SendMessageConfiguration,
    SendMessageRequest,
    SendMessageResponse,
    StreamResponse,
    StringList,
    TaskArtifactUpdateEvent,
    TaskState,
    TaskStatus,
    TaskStatusUpdateEvent,
)
from .types.data_agent import DataAgent
from .types.data_agent_service import (
    CreateDataAgentRequest,
    DeleteDataAgentRequest,
    GetDataAgentRequest,
    ListAccessibleDataAgentsRequest,
    ListAccessibleDataAgentsResponse,
    ListDataAgentsRequest,
    ListDataAgentsResponse,
    OperationMetadata,
    RetrieveAgentOpsObservabilityRequest,
    RetrieveAgentOpsObservabilityResponse,
    SetAgentOpsObservabilityMetadata,
    SetAgentOpsObservabilityRequest,
    SetAgentOpsObservabilityResponse,
    UpdateDataAgentRequest,
)
from .types.data_analytics_agent import DataAnalyticsAgent
from .types.data_chat_service import (
    AnalysisEvent,
    AnalysisMessage,
    AnalysisQuery,
    BigQueryJob,
    Blob,
    ChartMessage,
    ChartQuery,
    ChartResult,
    ChatRequest,
    ClarificationMessage,
    ClarificationQuestion,
    ClientManagedResourceContext,
    ConversationReference,
    DataAgentContext,
    DataMessage,
    DataQuery,
    DataResult,
    ErrorMessage,
    ExampleQueries,
    ExecutedQueryResult,
    GenerationOptions,
    ListMessagesRequest,
    ListMessagesResponse,
    LookerSettings,
    Message,
    ParameterizedSecureViewParameters,
    QueryDataContext,
    QueryDataRequest,
    QueryDataResponse,
    SchemaMessage,
    SchemaQuery,
    SchemaResult,
    StorageMessage,
    SystemMessage,
    TextMessage,
    UserMessage,
)
from .types.datasource import (
    AlloyDbDatabaseReference,
    AlloyDbReference,
    BigQueryPropertyGraphReference,
    BigQueryTableReference,
    BigQueryTableReferences,
    BigtableDatabaseReference,
    BigtableReference,
    CloudSqlDatabaseReference,
    CloudSqlReference,
    DatabaseTableReference,
    DataFilter,
    DataFilterType,
    Datasource,
    DatasourceReferences,
    Field,
    FirestoreDatabaseReference,
    FirestoreReference,
    LookerExploreReference,
    LookerExploreReferences,
    PrivateLookerInstanceInfo,
    Schema,
    SpannerDatabaseReference,
    SpannerReference,
    StudioDatasourceReference,
    StudioDatasourceReferences,
)
from .types.usage import TokenUsage

__all__ = (
    "DataA2AServiceAsyncClient",
    "DataAgentServiceAsyncClient",
    "DataChatServiceAsyncClient",
    "A2AArtifact",
    "A2AMessage",
    "A2ATask",
    "APIKeySecurityScheme",
    "AgentCapabilities",
    "AgentCard",
    "AgentCardSignature",
    "AgentContextReference",
    "AgentExtension",
    "AgentInterface",
    "AgentProvider",
    "AgentSkill",
    "AlloyDbDatabaseReference",
    "AlloyDbReference",
    "AnalysisEvent",
    "AnalysisMessage",
    "AnalysisOptions",
    "AnalysisQuery",
    "AuthenticationInfo",
    "AuthorizationCodeOAuthFlow",
    "BigQueryJob",
    "BigQueryPropertyGraphReference",
    "BigQueryRoutine",
    "BigQueryRoutineReference",
    "BigQueryTableReference",
    "BigQueryTableReferences",
    "BigtableDatabaseReference",
    "BigtableReference",
    "Blob",
    "ChartMessage",
    "ChartOptions",
    "ChartQuery",
    "ChartResult",
    "ChatRequest",
    "Citation",
    "CitationAnchor",
    "CitationSource",
    "ClarificationMessage",
    "ClarificationQuestion",
    "ClientCredentialsOAuthFlow",
    "ClientManagedResourceContext",
    "CloudSqlDatabaseReference",
    "CloudSqlReference",
    "Context",
    "Conversation",
    "ConversationOptions",
    "ConversationReference",
    "CreateConversationRequest",
    "CreateDataAgentRequest",
    "Credentials",
    "DataA2AServiceClient",
    "DataAgent",
    "DataAgentContext",
    "DataAgentServiceClient",
    "DataAnalyticsAgent",
    "DataChatServiceClient",
    "DataFilter",
    "DataFilterType",
    "DataMessage",
    "DataPart",
    "DataQuery",
    "DataResult",
    "DatabaseTableReference",
    "Datasource",
    "DatasourceOptions",
    "DatasourceReferences",
    "DeleteConversationRequest",
    "DeleteDataAgentRequest",
    "DynamicField",
    "ErrorMessage",
    "ExampleQueries",
    "ExampleQuery",
    "ExecutedQueryResult",
    "Field",
    "FilePart",
    "FirestoreDatabaseReference",
    "FirestoreReference",
    "GenerationOptions",
    "GetAgentCardRequest",
    "GetConversationRequest",
    "GetDataAgentRequest",
    "GlossaryTerm",
    "HTTPAuthSecurityScheme",
    "ImplicitOAuthFlow",
    "ListAccessibleDataAgentsRequest",
    "ListAccessibleDataAgentsResponse",
    "ListConversationsRequest",
    "ListConversationsResponse",
    "ListDataAgentsRequest",
    "ListDataAgentsResponse",
    "ListMessagesRequest",
    "ListMessagesResponse",
    "LookerExploreReference",
    "LookerExploreReferences",
    "LookerGoldenQuery",
    "LookerQuery",
    "LookerSettings",
    "MatchedQuery",
    "Message",
    "MutualTlsSecurityScheme",
    "OAuth2SecurityScheme",
    "OAuthCredentials",
    "OAuthFlows",
    "OpenIdConnectSecurityScheme",
    "OperationMetadata",
    "ParameterizedSecureViewParameters",
    "Part",
    "PasswordOAuthFlow",
    "PrivateLookerInstanceInfo",
    "PushNotificationConfig",
    "QueryDataContext",
    "QueryDataRequest",
    "QueryDataResponse",
    "QueryParameter",
    "QueryParameterValues",
    "RetrieveAgentOpsObservabilityRequest",
    "RetrieveAgentOpsObservabilityResponse",
    "Role",
    "Schema",
    "SchemaMessage",
    "SchemaQuery",
    "SchemaResult",
    "Security",
    "SecurityScheme",
    "SendMessageConfiguration",
    "SendMessageRequest",
    "SendMessageResponse",
    "SetAgentOpsObservabilityMetadata",
    "SetAgentOpsObservabilityRequest",
    "SetAgentOpsObservabilityResponse",
    "SpannerDatabaseReference",
    "SpannerReference",
    "StorageMessage",
    "StreamResponse",
    "StringList",
    "StudioDatasourceReference",
    "StudioDatasourceReferences",
    "SystemMessage",
    "TaskArtifactUpdateEvent",
    "TaskState",
    "TaskStatus",
    "TaskStatusUpdateEvent",
    "TextMessage",
    "TokenUsage",
    "UpdateConversationRequest",
    "UpdateDataAgentRequest",
    "UserFunctions",
    "UserMessage",
)

api_core.check_python_version("google.cloud.geminidataanalytics_v1beta")
api_core.check_dependency_versions("google.cloud.geminidataanalytics_v1beta")
