# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.ces_v1beta import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.ces_v1beta.services.agent_service",
    "google.cloud.ces_v1beta.services.evaluation_service",
    "google.cloud.ces_v1beta.services.session_service",
    "google.cloud.ces_v1beta.services.tool_service",
    "google.cloud.ces_v1beta.services.widget_service",
    "google.cloud.ces_v1beta.types.agent",
    "google.cloud.ces_v1beta.types.agent_card",
    "google.cloud.ces_v1beta.types.agent_service",
    "google.cloud.ces_v1beta.types.agent_tool",
    "google.cloud.ces_v1beta.types.agent_transfers",
    "google.cloud.ces_v1beta.types.app",
    "google.cloud.ces_v1beta.types.app_version",
    "google.cloud.ces_v1beta.types.auth",
    "google.cloud.ces_v1beta.types.bigquery_export",
    "google.cloud.ces_v1beta.types.changelog",
    "google.cloud.ces_v1beta.types.client_function",
    "google.cloud.ces_v1beta.types.common",
    "google.cloud.ces_v1beta.types.connector_tool",
    "google.cloud.ces_v1beta.types.connector_toolset",
    "google.cloud.ces_v1beta.types.conversation",
    "google.cloud.ces_v1beta.types.data_store",
    "google.cloud.ces_v1beta.types.data_store_tool",
    "google.cloud.ces_v1beta.types.deployment",
    "google.cloud.ces_v1beta.types.evaluation",
    "google.cloud.ces_v1beta.types.evaluation_metrics_config",
    "google.cloud.ces_v1beta.types.evaluation_service",
    "google.cloud.ces_v1beta.types.example",
    "google.cloud.ces_v1beta.types.fakes",
    "google.cloud.ces_v1beta.types.file_context",
    "google.cloud.ces_v1beta.types.file_search_tool",
    "google.cloud.ces_v1beta.types.golden_run",
    "google.cloud.ces_v1beta.types.google_search_tool",
    "google.cloud.ces_v1beta.types.guardrail",
    "google.cloud.ces_v1beta.types.mcp_tool",
    "google.cloud.ces_v1beta.types.mcp_toolset",
    "google.cloud.ces_v1beta.types.mocks",
    "google.cloud.ces_v1beta.types.omnichannel",
    "google.cloud.ces_v1beta.types.omnichannel_service",
    "google.cloud.ces_v1beta.types.open_api_tool",
    "google.cloud.ces_v1beta.types.open_api_toolset",
    "google.cloud.ces_v1beta.types.python_function",
    "google.cloud.ces_v1beta.types.schema",
    "google.cloud.ces_v1beta.types.search_suggestions",
    "google.cloud.ces_v1beta.types.security_settings",
    "google.cloud.ces_v1beta.types.session_service",
    "google.cloud.ces_v1beta.types.system_tool",
    "google.cloud.ces_v1beta.types.tool",
    "google.cloud.ces_v1beta.types.tool_service",
    "google.cloud.ces_v1beta.types.toolset",
    "google.cloud.ces_v1beta.types.toolset_tool",
    "google.cloud.ces_v1beta.types.widget_service",
    "google.cloud.ces_v1beta.types.widget_tool",
}


from .services.agent_service import AgentServiceAsyncClient, AgentServiceClient
from .services.evaluation_service import (
    EvaluationServiceAsyncClient,
    EvaluationServiceClient,
)
from .services.session_service import SessionServiceAsyncClient, SessionServiceClient
from .services.tool_service import ToolServiceAsyncClient, ToolServiceClient
from .services.widget_service import WidgetServiceAsyncClient, WidgetServiceClient
from .types.agent import Agent
from .types.agent_card import AgentCard, AgentInterface, AgentSkill, RemoteAgentTool
from .types.agent_service import (
    BatchDeleteConversationsRequest,
    BatchDeleteConversationsResponse,
    CreateAgentRequest,
    CreateAppRequest,
    CreateAppVersionRequest,
    CreateDeploymentRequest,
    CreateExampleRequest,
    CreateGuardrailRequest,
    CreateToolRequest,
    CreateToolsetRequest,
    DeleteAgentRequest,
    DeleteAppRequest,
    DeleteAppVersionRequest,
    DeleteConversationRequest,
    DeleteDeploymentRequest,
    DeleteExampleRequest,
    DeleteGuardrailRequest,
    DeleteToolRequest,
    DeleteToolsetRequest,
    ExportAppRequest,
    ExportAppResponse,
    GenerateAppResourceOperationMetadata,
    GenerateAppResourceRequest,
    GenerateAppResourceResponse,
    GetAgentRequest,
    GetAppRequest,
    GetAppVersionRequest,
    GetChangelogRequest,
    GetConversationRequest,
    GetDeploymentRequest,
    GetExampleRequest,
    GetGuardrailRequest,
    GetSecuritySettingsRequest,
    GetToolRequest,
    GetToolsetRequest,
    ImportAppRequest,
    ImportAppResponse,
    ListAgentsRequest,
    ListAgentsResponse,
    ListAppsRequest,
    ListAppsResponse,
    ListAppVersionsRequest,
    ListAppVersionsResponse,
    ListChangelogsRequest,
    ListChangelogsResponse,
    ListConversationsRequest,
    ListConversationsResponse,
    ListDeploymentsRequest,
    ListDeploymentsResponse,
    ListExamplesRequest,
    ListExamplesResponse,
    ListGuardrailsRequest,
    ListGuardrailsResponse,
    ListToolsetsRequest,
    ListToolsetsResponse,
    ListToolsRequest,
    ListToolsResponse,
    OperationMetadata,
    QualityReport,
    RestoreAppVersionRequest,
    RestoreAppVersionResponse,
    UpdateAgentRequest,
    UpdateAppRequest,
    UpdateDeploymentRequest,
    UpdateExampleRequest,
    UpdateGuardrailRequest,
    UpdateSecuritySettingsRequest,
    UpdateToolRequest,
    UpdateToolsetRequest,
)
from .types.agent_tool import AgentTool
from .types.agent_transfers import (
    ExpressionCondition,
    PythonCodeCondition,
    TransferRule,
)
from .types.app import (
    AmbientSoundConfig,
    App,
    AudioProcessingConfig,
    AudioRecordingConfig,
    BargeInConfig,
    ClientCertificateSettings,
    CloudLoggingSettings,
    ConversationLoggingSettings,
    DataStoreSettings,
    ErrorHandlingSettings,
    EvaluationMetricsThresholds,
    EvaluationPersona,
    EvaluationSettings,
    LanguageSettings,
    LoggingSettings,
    MetricAnalysisSettings,
    RedactionConfig,
    SynthesizeSpeechConfig,
    TimeZoneSettings,
    VpcScSettings,
)
from .types.app_version import AppSnapshot, AppVersion
from .types.auth import (
    ApiAuthentication,
    ApiKeyConfig,
    BearerTokenConfig,
    EndUserAuthConfig,
    OAuthConfig,
    ServiceAccountAuthConfig,
    ServiceAgentIdTokenAuthConfig,
)
from .types.bigquery_export import BigQueryExportSettings
from .types.changelog import Changelog
from .types.client_function import ClientFunction
from .types.common import (
    Callback,
    ChannelProfile,
    EvaluationRunCachingSettings,
    ExecutionType,
    ModelSettings,
    ServiceDirectoryConfig,
    Span,
    TlsConfig,
    TriggerAction,
)
from .types.connector_tool import Action, ConnectorTool
from .types.connector_toolset import ConnectorToolset
from .types.conversation import Conversation
from .types.data_store import DataStore
from .types.data_store_tool import DataStoreTool
from .types.deployment import (
    Deployment,
    ExperimentConfig,
    InstagramCredentials,
    WhatsAppCredentials,
)
from .types.evaluation import (
    AggregatedMetrics,
    Evaluation,
    EvaluationConfig,
    EvaluationDataset,
    EvaluationErrorInfo,
    EvaluationExpectation,
    EvaluationResult,
    EvaluationRun,
    LatencyReport,
    OptimizationConfig,
    PersonaRunConfig,
    RunEvaluationRequest,
    ScheduledEvaluationRun,
)
from .types.evaluation_metrics_config import EvaluationMetricsConfig
from .types.evaluation_service import (
    CreateEvaluationDatasetRequest,
    CreateEvaluationExpectationRequest,
    CreateEvaluationRequest,
    CreateScheduledEvaluationRunRequest,
    DeleteEvaluationDatasetRequest,
    DeleteEvaluationExpectationRequest,
    DeleteEvaluationRequest,
    DeleteEvaluationResultRequest,
    DeleteEvaluationRunOperationMetadata,
    DeleteEvaluationRunRequest,
    DeleteScheduledEvaluationRunRequest,
    ExportEvaluationResultsOperationMetadata,
    ExportEvaluationResultsRequest,
    ExportEvaluationResultsResponse,
    ExportEvaluationRunsOperationMetadata,
    ExportEvaluationRunsRequest,
    ExportEvaluationRunsResponse,
    ExportEvaluationsRequest,
    ExportEvaluationsResponse,
    ExportOptions,
    GenerateEvaluationOperationMetadata,
    GenerateEvaluationRequest,
    GetEvaluationDatasetRequest,
    GetEvaluationExpectationRequest,
    GetEvaluationRequest,
    GetEvaluationResultRequest,
    GetEvaluationRunRequest,
    GetScheduledEvaluationRunRequest,
    ImportEvaluationsOperationMetadata,
    ImportEvaluationsRequest,
    ImportEvaluationsResponse,
    ListEvaluationDatasetsRequest,
    ListEvaluationDatasetsResponse,
    ListEvaluationExpectationsRequest,
    ListEvaluationExpectationsResponse,
    ListEvaluationResultsRequest,
    ListEvaluationResultsResponse,
    ListEvaluationRunsRequest,
    ListEvaluationRunsResponse,
    ListEvaluationsRequest,
    ListEvaluationsResponse,
    ListScheduledEvaluationRunsRequest,
    ListScheduledEvaluationRunsResponse,
    RunEvaluationOperationMetadata,
    RunEvaluationResponse,
    RunEvaluationResultMetricsOperationMetadata,
    RunEvaluationResultMetricsRequest,
    RunEvaluationResultMetricsResponse,
    TestPersonaVoiceRequest,
    TestPersonaVoiceResponse,
    UpdateEvaluationDatasetRequest,
    UpdateEvaluationExpectationRequest,
    UpdateEvaluationRequest,
    UpdateScheduledEvaluationRunRequest,
    UploadEvaluationAudioRequest,
    UploadEvaluationAudioResponse,
)
from .types.example import (
    AgentTransfer,
    Blob,
    Chunk,
    Example,
    Image,
    Message,
    ToolCall,
    ToolResponse,
)
from .types.fakes import CodeBlock, EvaluationToolCallBehaviour, ToolFakeConfig
from .types.file_context import FileContext
from .types.file_search_tool import FileSearchTool
from .types.golden_run import GoldenRunMethod
from .types.google_search_tool import GoogleSearchTool
from .types.guardrail import Guardrail
from .types.mcp_tool import McpTool
from .types.mcp_toolset import McpToolDefinition, McpToolOverride, McpToolset
from .types.mocks import MockedToolCall
from .types.omnichannel import Omnichannel, OmnichannelIntegrationConfig
from .types.omnichannel_service import OmnichannelOperationMetadata
from .types.open_api_tool import OpenApiTool
from .types.open_api_toolset import OpenApiToolset
from .types.python_function import PythonFunction
from .types.schema import Schema
from .types.search_suggestions import GoogleSearchSuggestions, WebSearchQuery
from .types.security_settings import EndpointControlPolicy, SecuritySettings
from .types.session_service import (
    AudioEncoding,
    BidiSessionClientMessage,
    BidiSessionServerMessage,
    Citations,
    EndSession,
    Event,
    GoAway,
    InputAudioConfig,
    InterruptionSignal,
    MockConfig,
    OutputAudioConfig,
    RecognitionResult,
    RunSessionRequest,
    RunSessionResponse,
    SessionConfig,
    SessionInput,
    SessionOutput,
    ToolCalls,
    ToolResponses,
)
from .types.system_tool import SystemTool
from .types.tool import Tool
from .types.tool_service import (
    ExecuteToolRequest,
    ExecuteToolResponse,
    RetrieveToolSchemaRequest,
    RetrieveToolSchemaResponse,
    RetrieveToolsRequest,
    RetrieveToolsResponse,
)
from .types.toolset import Toolset
from .types.toolset_tool import ToolsetTool
from .types.widget_service import GenerateChatTokenRequest, GenerateChatTokenResponse
from .types.widget_tool import WidgetTool

__all__ = (
    "AgentServiceAsyncClient",
    "EvaluationServiceAsyncClient",
    "SessionServiceAsyncClient",
    "ToolServiceAsyncClient",
    "WidgetServiceAsyncClient",
    "Action",
    "Agent",
    "AgentCard",
    "AgentInterface",
    "AgentServiceClient",
    "AgentSkill",
    "AgentTool",
    "AgentTransfer",
    "AggregatedMetrics",
    "AmbientSoundConfig",
    "ApiAuthentication",
    "ApiKeyConfig",
    "App",
    "AppSnapshot",
    "AppVersion",
    "AudioEncoding",
    "AudioProcessingConfig",
    "AudioRecordingConfig",
    "BargeInConfig",
    "BatchDeleteConversationsRequest",
    "BatchDeleteConversationsResponse",
    "BearerTokenConfig",
    "BidiSessionClientMessage",
    "BidiSessionServerMessage",
    "BigQueryExportSettings",
    "Blob",
    "Callback",
    "Changelog",
    "ChannelProfile",
    "Chunk",
    "Citations",
    "ClientCertificateSettings",
    "ClientFunction",
    "CloudLoggingSettings",
    "CodeBlock",
    "ConnectorTool",
    "ConnectorToolset",
    "Conversation",
    "ConversationLoggingSettings",
    "CreateAgentRequest",
    "CreateAppRequest",
    "CreateAppVersionRequest",
    "CreateDeploymentRequest",
    "CreateEvaluationDatasetRequest",
    "CreateEvaluationExpectationRequest",
    "CreateEvaluationRequest",
    "CreateExampleRequest",
    "CreateGuardrailRequest",
    "CreateScheduledEvaluationRunRequest",
    "CreateToolRequest",
    "CreateToolsetRequest",
    "DataStore",
    "DataStoreSettings",
    "DataStoreTool",
    "DeleteAgentRequest",
    "DeleteAppRequest",
    "DeleteAppVersionRequest",
    "DeleteConversationRequest",
    "DeleteDeploymentRequest",
    "DeleteEvaluationDatasetRequest",
    "DeleteEvaluationExpectationRequest",
    "DeleteEvaluationRequest",
    "DeleteEvaluationResultRequest",
    "DeleteEvaluationRunOperationMetadata",
    "DeleteEvaluationRunRequest",
    "DeleteExampleRequest",
    "DeleteGuardrailRequest",
    "DeleteScheduledEvaluationRunRequest",
    "DeleteToolRequest",
    "DeleteToolsetRequest",
    "Deployment",
    "EndSession",
    "EndUserAuthConfig",
    "EndpointControlPolicy",
    "ErrorHandlingSettings",
    "Evaluation",
    "EvaluationConfig",
    "EvaluationDataset",
    "EvaluationErrorInfo",
    "EvaluationExpectation",
    "EvaluationMetricsConfig",
    "EvaluationMetricsThresholds",
    "EvaluationPersona",
    "EvaluationResult",
    "EvaluationRun",
    "EvaluationRunCachingSettings",
    "EvaluationServiceClient",
    "EvaluationSettings",
    "EvaluationToolCallBehaviour",
    "Event",
    "Example",
    "ExecuteToolRequest",
    "ExecuteToolResponse",
    "ExecutionType",
    "ExperimentConfig",
    "ExportAppRequest",
    "ExportAppResponse",
    "ExportEvaluationResultsOperationMetadata",
    "ExportEvaluationResultsRequest",
    "ExportEvaluationResultsResponse",
    "ExportEvaluationRunsOperationMetadata",
    "ExportEvaluationRunsRequest",
    "ExportEvaluationRunsResponse",
    "ExportEvaluationsRequest",
    "ExportEvaluationsResponse",
    "ExportOptions",
    "ExpressionCondition",
    "FileContext",
    "FileSearchTool",
    "GenerateAppResourceOperationMetadata",
    "GenerateAppResourceRequest",
    "GenerateAppResourceResponse",
    "GenerateChatTokenRequest",
    "GenerateChatTokenResponse",
    "GenerateEvaluationOperationMetadata",
    "GenerateEvaluationRequest",
    "GetAgentRequest",
    "GetAppRequest",
    "GetAppVersionRequest",
    "GetChangelogRequest",
    "GetConversationRequest",
    "GetDeploymentRequest",
    "GetEvaluationDatasetRequest",
    "GetEvaluationExpectationRequest",
    "GetEvaluationRequest",
    "GetEvaluationResultRequest",
    "GetEvaluationRunRequest",
    "GetExampleRequest",
    "GetGuardrailRequest",
    "GetScheduledEvaluationRunRequest",
    "GetSecuritySettingsRequest",
    "GetToolRequest",
    "GetToolsetRequest",
    "GoAway",
    "GoldenRunMethod",
    "GoogleSearchSuggestions",
    "GoogleSearchTool",
    "Guardrail",
    "Image",
    "ImportAppRequest",
    "ImportAppResponse",
    "ImportEvaluationsOperationMetadata",
    "ImportEvaluationsRequest",
    "ImportEvaluationsResponse",
    "InputAudioConfig",
    "InstagramCredentials",
    "InterruptionSignal",
    "LanguageSettings",
    "LatencyReport",
    "ListAgentsRequest",
    "ListAgentsResponse",
    "ListAppVersionsRequest",
    "ListAppVersionsResponse",
    "ListAppsRequest",
    "ListAppsResponse",
    "ListChangelogsRequest",
    "ListChangelogsResponse",
    "ListConversationsRequest",
    "ListConversationsResponse",
    "ListDeploymentsRequest",
    "ListDeploymentsResponse",
    "ListEvaluationDatasetsRequest",
    "ListEvaluationDatasetsResponse",
    "ListEvaluationExpectationsRequest",
    "ListEvaluationExpectationsResponse",
    "ListEvaluationResultsRequest",
    "ListEvaluationResultsResponse",
    "ListEvaluationRunsRequest",
    "ListEvaluationRunsResponse",
    "ListEvaluationsRequest",
    "ListEvaluationsResponse",
    "ListExamplesRequest",
    "ListExamplesResponse",
    "ListGuardrailsRequest",
    "ListGuardrailsResponse",
    "ListScheduledEvaluationRunsRequest",
    "ListScheduledEvaluationRunsResponse",
    "ListToolsRequest",
    "ListToolsResponse",
    "ListToolsetsRequest",
    "ListToolsetsResponse",
    "LoggingSettings",
    "McpTool",
    "McpToolDefinition",
    "McpToolOverride",
    "McpToolset",
    "Message",
    "MetricAnalysisSettings",
    "MockConfig",
    "MockedToolCall",
    "ModelSettings",
    "OAuthConfig",
    "Omnichannel",
    "OmnichannelIntegrationConfig",
    "OmnichannelOperationMetadata",
    "OpenApiTool",
    "OpenApiToolset",
    "OperationMetadata",
    "OptimizationConfig",
    "OutputAudioConfig",
    "PersonaRunConfig",
    "PythonCodeCondition",
    "PythonFunction",
    "QualityReport",
    "RecognitionResult",
    "RedactionConfig",
    "RemoteAgentTool",
    "RestoreAppVersionRequest",
    "RestoreAppVersionResponse",
    "RetrieveToolSchemaRequest",
    "RetrieveToolSchemaResponse",
    "RetrieveToolsRequest",
    "RetrieveToolsResponse",
    "RunEvaluationOperationMetadata",
    "RunEvaluationRequest",
    "RunEvaluationResponse",
    "RunEvaluationResultMetricsOperationMetadata",
    "RunEvaluationResultMetricsRequest",
    "RunEvaluationResultMetricsResponse",
    "RunSessionRequest",
    "RunSessionResponse",
    "ScheduledEvaluationRun",
    "Schema",
    "SecuritySettings",
    "ServiceAccountAuthConfig",
    "ServiceAgentIdTokenAuthConfig",
    "ServiceDirectoryConfig",
    "SessionConfig",
    "SessionInput",
    "SessionOutput",
    "SessionServiceClient",
    "Span",
    "SynthesizeSpeechConfig",
    "SystemTool",
    "TestPersonaVoiceRequest",
    "TestPersonaVoiceResponse",
    "TimeZoneSettings",
    "TlsConfig",
    "Tool",
    "ToolCall",
    "ToolCalls",
    "ToolFakeConfig",
    "ToolResponse",
    "ToolResponses",
    "ToolServiceClient",
    "Toolset",
    "ToolsetTool",
    "TransferRule",
    "TriggerAction",
    "UpdateAgentRequest",
    "UpdateAppRequest",
    "UpdateDeploymentRequest",
    "UpdateEvaluationDatasetRequest",
    "UpdateEvaluationExpectationRequest",
    "UpdateEvaluationRequest",
    "UpdateExampleRequest",
    "UpdateGuardrailRequest",
    "UpdateScheduledEvaluationRunRequest",
    "UpdateSecuritySettingsRequest",
    "UpdateToolRequest",
    "UpdateToolsetRequest",
    "UploadEvaluationAudioRequest",
    "UploadEvaluationAudioResponse",
    "VpcScSettings",
    "WebSearchQuery",
    "WhatsAppCredentials",
    "WidgetServiceClient",
    "WidgetTool",
)

api_core.check_python_version("google.cloud.ces_v1beta")
api_core.check_dependency_versions("google.cloud.ces_v1beta")
