# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.dialogflow_v2 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.dialogflow_v2.services.agents",
    "google.cloud.dialogflow_v2.services.answer_records",
    "google.cloud.dialogflow_v2.services.contexts",
    "google.cloud.dialogflow_v2.services.conversation_datasets",
    "google.cloud.dialogflow_v2.services.conversation_models",
    "google.cloud.dialogflow_v2.services.conversation_profiles",
    "google.cloud.dialogflow_v2.services.conversations",
    "google.cloud.dialogflow_v2.services.documents",
    "google.cloud.dialogflow_v2.services.encryption_spec_service",
    "google.cloud.dialogflow_v2.services.entity_types",
    "google.cloud.dialogflow_v2.services.environments",
    "google.cloud.dialogflow_v2.services.fulfillments",
    "google.cloud.dialogflow_v2.services.generator_evaluations",
    "google.cloud.dialogflow_v2.services.generators",
    "google.cloud.dialogflow_v2.services.intents",
    "google.cloud.dialogflow_v2.services.knowledge_bases",
    "google.cloud.dialogflow_v2.services.participants",
    "google.cloud.dialogflow_v2.services.session_entity_types",
    "google.cloud.dialogflow_v2.services.sessions",
    "google.cloud.dialogflow_v2.services.sip_trunks",
    "google.cloud.dialogflow_v2.services.tools",
    "google.cloud.dialogflow_v2.services.versions",
    "google.cloud.dialogflow_v2.types.agent",
    "google.cloud.dialogflow_v2.types.agent_coaching_instruction",
    "google.cloud.dialogflow_v2.types.answer_record",
    "google.cloud.dialogflow_v2.types.audio_config",
    "google.cloud.dialogflow_v2.types.ces_app",
    "google.cloud.dialogflow_v2.types.ces_tool",
    "google.cloud.dialogflow_v2.types.context",
    "google.cloud.dialogflow_v2.types.conversation",
    "google.cloud.dialogflow_v2.types.conversation_dataset",
    "google.cloud.dialogflow_v2.types.conversation_event",
    "google.cloud.dialogflow_v2.types.conversation_model",
    "google.cloud.dialogflow_v2.types.conversation_profile",
    "google.cloud.dialogflow_v2.types.document",
    "google.cloud.dialogflow_v2.types.encryption_spec",
    "google.cloud.dialogflow_v2.types.entity_type",
    "google.cloud.dialogflow_v2.types.environment",
    "google.cloud.dialogflow_v2.types.fulfillment",
    "google.cloud.dialogflow_v2.types.gcs",
    "google.cloud.dialogflow_v2.types.generator",
    "google.cloud.dialogflow_v2.types.generator_evaluation",
    "google.cloud.dialogflow_v2.types.human_agent_assistant_event",
    "google.cloud.dialogflow_v2.types.intent",
    "google.cloud.dialogflow_v2.types.knowledge_base",
    "google.cloud.dialogflow_v2.types.operations",
    "google.cloud.dialogflow_v2.types.participant",
    "google.cloud.dialogflow_v2.types.session",
    "google.cloud.dialogflow_v2.types.session_entity_type",
    "google.cloud.dialogflow_v2.types.sip_trunk",
    "google.cloud.dialogflow_v2.types.tool",
    "google.cloud.dialogflow_v2.types.tool_call",
    "google.cloud.dialogflow_v2.types.toolset",
    "google.cloud.dialogflow_v2.types.validation_result",
    "google.cloud.dialogflow_v2.types.version",
    "google.cloud.dialogflow_v2.types.webhook",
}


from .services.agents import AgentsAsyncClient, AgentsClient
from .services.answer_records import AnswerRecordsAsyncClient, AnswerRecordsClient
from .services.contexts import ContextsAsyncClient, ContextsClient
from .services.conversation_datasets import (
    ConversationDatasetsAsyncClient,
    ConversationDatasetsClient,
)
from .services.conversation_models import (
    ConversationModelsAsyncClient,
    ConversationModelsClient,
)
from .services.conversation_profiles import (
    ConversationProfilesAsyncClient,
    ConversationProfilesClient,
)
from .services.conversations import ConversationsAsyncClient, ConversationsClient
from .services.documents import DocumentsAsyncClient, DocumentsClient
from .services.encryption_spec_service import (
    EncryptionSpecServiceAsyncClient,
    EncryptionSpecServiceClient,
)
from .services.entity_types import EntityTypesAsyncClient, EntityTypesClient
from .services.environments import EnvironmentsAsyncClient, EnvironmentsClient
from .services.fulfillments import FulfillmentsAsyncClient, FulfillmentsClient
from .services.generator_evaluations import (
    GeneratorEvaluationsAsyncClient,
    GeneratorEvaluationsClient,
)
from .services.generators import GeneratorsAsyncClient, GeneratorsClient
from .services.intents import IntentsAsyncClient, IntentsClient
from .services.knowledge_bases import KnowledgeBasesAsyncClient, KnowledgeBasesClient
from .services.participants import ParticipantsAsyncClient, ParticipantsClient
from .services.session_entity_types import (
    SessionEntityTypesAsyncClient,
    SessionEntityTypesClient,
)
from .services.sessions import SessionsAsyncClient, SessionsClient
from .services.sip_trunks import SipTrunksAsyncClient, SipTrunksClient
from .services.tools import ToolsAsyncClient, ToolsClient
from .services.versions import VersionsAsyncClient, VersionsClient
from .types.agent import (
    Agent,
    DeleteAgentRequest,
    ExportAgentRequest,
    ExportAgentResponse,
    GetAgentRequest,
    GetValidationResultRequest,
    ImportAgentRequest,
    RestoreAgentRequest,
    SearchAgentsRequest,
    SearchAgentsResponse,
    SetAgentRequest,
    TrainAgentRequest,
)
from .types.agent_coaching_instruction import AgentCoachingInstruction
from .types.answer_record import (
    AgentAssistantFeedback,
    AgentAssistantRecord,
    AnswerFeedback,
    AnswerRecord,
    ListAnswerRecordsRequest,
    ListAnswerRecordsResponse,
    UpdateAnswerRecordRequest,
)
from .types.audio_config import (
    AudioEncoding,
    CustomPronunciationParams,
    InputAudioConfig,
    OutputAudioConfig,
    OutputAudioEncoding,
    SpeechContext,
    SpeechModelVariant,
    SpeechToTextConfig,
    SpeechWordInfo,
    SsmlVoiceGender,
    SynthesizeSpeechConfig,
    TelephonyDtmf,
    TelephonyDtmfEvents,
    VoiceSelectionParams,
)
from .types.ces_app import CesAppSpec
from .types.ces_tool import CesToolSpec
from .types.context import (
    Context,
    CreateContextRequest,
    DeleteAllContextsRequest,
    DeleteContextRequest,
    GetContextRequest,
    ListContextsRequest,
    ListContextsResponse,
    UpdateContextRequest,
)
from .types.conversation import (
    CompleteConversationRequest,
    Conversation,
    ConversationPhoneNumber,
    CreateConversationRequest,
    GenerateStatelessSuggestionRequest,
    GenerateStatelessSuggestionResponse,
    GenerateStatelessSummaryRequest,
    GenerateStatelessSummaryResponse,
    GenerateSuggestionsRequest,
    GetConversationRequest,
    IngestContextReferencesRequest,
    IngestContextReferencesResponse,
    ListConversationsRequest,
    ListConversationsResponse,
    ListMessagesRequest,
    ListMessagesResponse,
    SearchKnowledgeAnswer,
    SearchKnowledgeDebugInfo,
    SearchKnowledgeRequest,
    SearchKnowledgeResponse,
    SuggestConversationSummaryRequest,
    SuggestConversationSummaryResponse,
)
from .types.conversation_dataset import (
    ConversationDataset,
    ConversationInfo,
    CreateConversationDatasetOperationMetadata,
    CreateConversationDatasetRequest,
    DeleteConversationDatasetOperationMetadata,
    DeleteConversationDatasetRequest,
    GetConversationDatasetRequest,
    ImportConversationDataOperationMetadata,
    ImportConversationDataOperationResponse,
    ImportConversationDataRequest,
    InputConfig,
    ListConversationDatasetsRequest,
    ListConversationDatasetsResponse,
)
from .types.conversation_event import ConversationEvent
from .types.conversation_model import (
    ArticleSuggestionModelMetadata,
    ConversationModel,
    ConversationModelEvaluation,
    CreateConversationModelEvaluationOperationMetadata,
    CreateConversationModelEvaluationRequest,
    CreateConversationModelOperationMetadata,
    CreateConversationModelRequest,
    DeleteConversationModelOperationMetadata,
    DeleteConversationModelRequest,
    DeployConversationModelOperationMetadata,
    DeployConversationModelRequest,
    EvaluationConfig,
    GetConversationModelEvaluationRequest,
    GetConversationModelRequest,
    InputDataset,
    ListConversationModelEvaluationsRequest,
    ListConversationModelEvaluationsResponse,
    ListConversationModelsRequest,
    ListConversationModelsResponse,
    SmartReplyMetrics,
    SmartReplyModelMetadata,
    UndeployConversationModelOperationMetadata,
    UndeployConversationModelRequest,
)
from .types.conversation_profile import (
    AutomatedAgentConfig,
    ClearSuggestionFeatureConfigOperationMetadata,
    ClearSuggestionFeatureConfigRequest,
    ConversationProfile,
    CreateConversationProfileRequest,
    DeleteConversationProfileRequest,
    GetConversationProfileRequest,
    HumanAgentAssistantConfig,
    HumanAgentHandoffConfig,
    ListConversationProfilesRequest,
    ListConversationProfilesResponse,
    LoggingConfig,
    NotificationConfig,
    SetSuggestionFeatureConfigOperationMetadata,
    SetSuggestionFeatureConfigRequest,
    SipConfig,
    SuggestionFeature,
    UpdateConversationProfileRequest,
)
from .types.document import (
    CreateDocumentRequest,
    DeleteDocumentRequest,
    Document,
    ExportDocumentRequest,
    ExportOperationMetadata,
    GetDocumentRequest,
    ImportDocumentsRequest,
    ImportDocumentsResponse,
    ImportDocumentTemplate,
    KnowledgeOperationMetadata,
    ListDocumentsRequest,
    ListDocumentsResponse,
    ReloadDocumentRequest,
    UpdateDocumentRequest,
)
from .types.encryption_spec import (
    EncryptionSpec,
    GetEncryptionSpecRequest,
    InitializeEncryptionSpecMetadata,
    InitializeEncryptionSpecRequest,
    InitializeEncryptionSpecResponse,
)
from .types.entity_type import (
    BatchCreateEntitiesRequest,
    BatchDeleteEntitiesRequest,
    BatchDeleteEntityTypesRequest,
    BatchUpdateEntitiesRequest,
    BatchUpdateEntityTypesRequest,
    BatchUpdateEntityTypesResponse,
    CreateEntityTypeRequest,
    DeleteEntityTypeRequest,
    EntityType,
    EntityTypeBatch,
    GetEntityTypeRequest,
    ListEntityTypesRequest,
    ListEntityTypesResponse,
    UpdateEntityTypeRequest,
)
from .types.environment import (
    CreateEnvironmentRequest,
    DeleteEnvironmentRequest,
    Environment,
    EnvironmentHistory,
    GetEnvironmentHistoryRequest,
    GetEnvironmentRequest,
    ListEnvironmentsRequest,
    ListEnvironmentsResponse,
    TextToSpeechSettings,
    UpdateEnvironmentRequest,
)
from .types.fulfillment import (
    Fulfillment,
    GetFulfillmentRequest,
    UpdateFulfillmentRequest,
)
from .types.gcs import GcsDestination, GcsSources
from .types.generator import (
    AgentCoachingContext,
    AgentCoachingSuggestion,
    ConversationContext,
    CreateGeneratorRequest,
    DeleteGeneratorRequest,
    FewShotExample,
    FreeFormContext,
    FreeFormSuggestion,
    Generator,
    GeneratorSuggestion,
    GetGeneratorRequest,
    InferenceParameter,
    ListGeneratorsRequest,
    ListGeneratorsResponse,
    MessageEntry,
    RaiSettings,
    SuggestionDedupingConfig,
    SummarizationContext,
    SummarizationSection,
    SummarizationSectionList,
    SummarySuggestion,
    TriggerEvent,
    UpdateGeneratorRequest,
)
from .types.generator_evaluation import (
    CreateGeneratorEvaluationRequest,
    DeleteGeneratorEvaluationRequest,
    EvaluationStatus,
    GeneratorEvaluation,
    GeneratorEvaluationConfig,
    GetGeneratorEvaluationRequest,
    ListGeneratorEvaluationsRequest,
    ListGeneratorEvaluationsResponse,
    SummarizationEvaluationMetrics,
)
from .types.human_agent_assistant_event import HumanAgentAssistantEvent
from .types.intent import (
    BatchDeleteIntentsRequest,
    BatchUpdateIntentsRequest,
    BatchUpdateIntentsResponse,
    CreateIntentRequest,
    DeleteIntentRequest,
    GetIntentRequest,
    Intent,
    IntentBatch,
    IntentView,
    ListIntentsRequest,
    ListIntentsResponse,
    UpdateIntentRequest,
)
from .types.knowledge_base import (
    CreateKnowledgeBaseRequest,
    DeleteKnowledgeBaseRequest,
    GetKnowledgeBaseRequest,
    KnowledgeBase,
    ListKnowledgeBasesRequest,
    ListKnowledgeBasesResponse,
    UpdateKnowledgeBaseRequest,
)
from .types.operations import GeneratorEvaluationOperationMetadata
from .types.participant import (
    AnalyzeContentRequest,
    AnalyzeContentResponse,
    AnnotatedMessagePart,
    ArticleAnswer,
    AssistQueryParameters,
    AudioInput,
    AutomatedAgentReply,
    CreateParticipantRequest,
    DatastoreResponseReason,
    DialogflowAssistAnswer,
    DtmfParameters,
    FaqAnswer,
    GenerateSuggestionsResponse,
    GetParticipantRequest,
    IngestedContextReferenceDebugInfo,
    InputTextConfig,
    IntentSuggestion,
    KnowledgeAssistAnswer,
    KnowledgeAssistDebugInfo,
    ListParticipantsRequest,
    ListParticipantsResponse,
    Message,
    MessageAnnotation,
    OutputAudio,
    Participant,
    ServiceLatency,
    SmartReplyAnswer,
    StreamingAnalyzeContentRequest,
    StreamingAnalyzeContentResponse,
    SuggestArticlesRequest,
    SuggestArticlesResponse,
    SuggestFaqAnswersRequest,
    SuggestFaqAnswersResponse,
    SuggestionInput,
    SuggestionResult,
    SuggestKnowledgeAssistRequest,
    SuggestKnowledgeAssistResponse,
    SuggestSmartRepliesRequest,
    SuggestSmartRepliesResponse,
    UpdateParticipantRequest,
)
from .types.session import (
    CloudConversationDebuggingInfo,
    DetectIntentRequest,
    DetectIntentResponse,
    EventInput,
    QueryInput,
    QueryParameters,
    QueryResult,
    Sentiment,
    SentimentAnalysisRequestConfig,
    SentimentAnalysisResult,
    StreamingDetectIntentRequest,
    StreamingDetectIntentResponse,
    StreamingRecognitionResult,
    TextInput,
)
from .types.session_entity_type import (
    CreateSessionEntityTypeRequest,
    DeleteSessionEntityTypeRequest,
    GetSessionEntityTypeRequest,
    ListSessionEntityTypesRequest,
    ListSessionEntityTypesResponse,
    SessionEntityType,
    UpdateSessionEntityTypeRequest,
)
from .types.sip_trunk import (
    Connection,
    CreateSipTrunkRequest,
    DeleteSipTrunkRequest,
    GetSipTrunkRequest,
    ListSipTrunksRequest,
    ListSipTrunksResponse,
    SipTrunk,
    UpdateSipTrunkRequest,
)
from .types.tool import (
    CreateToolRequest,
    DeleteToolRequest,
    GetToolRequest,
    ListToolsRequest,
    ListToolsResponse,
    Tool,
    UpdateToolRequest,
)
from .types.tool_call import ToolCall, ToolCallResult
from .types.toolset import ToolsetTool
from .types.validation_result import ValidationError, ValidationResult
from .types.version import (
    CreateVersionRequest,
    DeleteVersionRequest,
    GetVersionRequest,
    ListVersionsRequest,
    ListVersionsResponse,
    UpdateVersionRequest,
    Version,
)
from .types.webhook import OriginalDetectIntentRequest, WebhookRequest, WebhookResponse

__all__ = (
    "AgentsAsyncClient",
    "AnswerRecordsAsyncClient",
    "ContextsAsyncClient",
    "ConversationDatasetsAsyncClient",
    "ConversationModelsAsyncClient",
    "ConversationProfilesAsyncClient",
    "ConversationsAsyncClient",
    "DocumentsAsyncClient",
    "EncryptionSpecServiceAsyncClient",
    "EntityTypesAsyncClient",
    "EnvironmentsAsyncClient",
    "FulfillmentsAsyncClient",
    "GeneratorEvaluationsAsyncClient",
    "GeneratorsAsyncClient",
    "IntentsAsyncClient",
    "KnowledgeBasesAsyncClient",
    "ParticipantsAsyncClient",
    "SessionEntityTypesAsyncClient",
    "SessionsAsyncClient",
    "SipTrunksAsyncClient",
    "ToolsAsyncClient",
    "VersionsAsyncClient",
    "Agent",
    "AgentAssistantFeedback",
    "AgentAssistantRecord",
    "AgentCoachingContext",
    "AgentCoachingInstruction",
    "AgentCoachingSuggestion",
    "AgentsClient",
    "AnalyzeContentRequest",
    "AnalyzeContentResponse",
    "AnnotatedMessagePart",
    "AnswerFeedback",
    "AnswerRecord",
    "AnswerRecordsClient",
    "ArticleAnswer",
    "ArticleSuggestionModelMetadata",
    "AssistQueryParameters",
    "AudioEncoding",
    "AudioInput",
    "AutomatedAgentConfig",
    "AutomatedAgentReply",
    "BatchCreateEntitiesRequest",
    "BatchDeleteEntitiesRequest",
    "BatchDeleteEntityTypesRequest",
    "BatchDeleteIntentsRequest",
    "BatchUpdateEntitiesRequest",
    "BatchUpdateEntityTypesRequest",
    "BatchUpdateEntityTypesResponse",
    "BatchUpdateIntentsRequest",
    "BatchUpdateIntentsResponse",
    "CesAppSpec",
    "CesToolSpec",
    "ClearSuggestionFeatureConfigOperationMetadata",
    "ClearSuggestionFeatureConfigRequest",
    "CloudConversationDebuggingInfo",
    "CompleteConversationRequest",
    "Connection",
    "Context",
    "ContextsClient",
    "Conversation",
    "ConversationContext",
    "ConversationDataset",
    "ConversationDatasetsClient",
    "ConversationEvent",
    "ConversationInfo",
    "ConversationModel",
    "ConversationModelEvaluation",
    "ConversationModelsClient",
    "ConversationPhoneNumber",
    "ConversationProfile",
    "ConversationProfilesClient",
    "ConversationsClient",
    "CreateContextRequest",
    "CreateConversationDatasetOperationMetadata",
    "CreateConversationDatasetRequest",
    "CreateConversationModelEvaluationOperationMetadata",
    "CreateConversationModelEvaluationRequest",
    "CreateConversationModelOperationMetadata",
    "CreateConversationModelRequest",
    "CreateConversationProfileRequest",
    "CreateConversationRequest",
    "CreateDocumentRequest",
    "CreateEntityTypeRequest",
    "CreateEnvironmentRequest",
    "CreateGeneratorEvaluationRequest",
    "CreateGeneratorRequest",
    "CreateIntentRequest",
    "CreateKnowledgeBaseRequest",
    "CreateParticipantRequest",
    "CreateSessionEntityTypeRequest",
    "CreateSipTrunkRequest",
    "CreateToolRequest",
    "CreateVersionRequest",
    "CustomPronunciationParams",
    "DatastoreResponseReason",
    "DeleteAgentRequest",
    "DeleteAllContextsRequest",
    "DeleteContextRequest",
    "DeleteConversationDatasetOperationMetadata",
    "DeleteConversationDatasetRequest",
    "DeleteConversationModelOperationMetadata",
    "DeleteConversationModelRequest",
    "DeleteConversationProfileRequest",
    "DeleteDocumentRequest",
    "DeleteEntityTypeRequest",
    "DeleteEnvironmentRequest",
    "DeleteGeneratorEvaluationRequest",
    "DeleteGeneratorRequest",
    "DeleteIntentRequest",
    "DeleteKnowledgeBaseRequest",
    "DeleteSessionEntityTypeRequest",
    "DeleteSipTrunkRequest",
    "DeleteToolRequest",
    "DeleteVersionRequest",
    "DeployConversationModelOperationMetadata",
    "DeployConversationModelRequest",
    "DetectIntentRequest",
    "DetectIntentResponse",
    "DialogflowAssistAnswer",
    "Document",
    "DocumentsClient",
    "DtmfParameters",
    "EncryptionSpec",
    "EncryptionSpecServiceClient",
    "EntityType",
    "EntityTypeBatch",
    "EntityTypesClient",
    "Environment",
    "EnvironmentHistory",
    "EnvironmentsClient",
    "EvaluationConfig",
    "EvaluationStatus",
    "EventInput",
    "ExportAgentRequest",
    "ExportAgentResponse",
    "ExportDocumentRequest",
    "ExportOperationMetadata",
    "FaqAnswer",
    "FewShotExample",
    "FreeFormContext",
    "FreeFormSuggestion",
    "Fulfillment",
    "FulfillmentsClient",
    "GcsDestination",
    "GcsSources",
    "GenerateStatelessSuggestionRequest",
    "GenerateStatelessSuggestionResponse",
    "GenerateStatelessSummaryRequest",
    "GenerateStatelessSummaryResponse",
    "GenerateSuggestionsRequest",
    "GenerateSuggestionsResponse",
    "Generator",
    "GeneratorEvaluation",
    "GeneratorEvaluationConfig",
    "GeneratorEvaluationOperationMetadata",
    "GeneratorEvaluationsClient",
    "GeneratorSuggestion",
    "GeneratorsClient",
    "GetAgentRequest",
    "GetContextRequest",
    "GetConversationDatasetRequest",
    "GetConversationModelEvaluationRequest",
    "GetConversationModelRequest",
    "GetConversationProfileRequest",
    "GetConversationRequest",
    "GetDocumentRequest",
    "GetEncryptionSpecRequest",
    "GetEntityTypeRequest",
    "GetEnvironmentHistoryRequest",
    "GetEnvironmentRequest",
    "GetFulfillmentRequest",
    "GetGeneratorEvaluationRequest",
    "GetGeneratorRequest",
    "GetIntentRequest",
    "GetKnowledgeBaseRequest",
    "GetParticipantRequest",
    "GetSessionEntityTypeRequest",
    "GetSipTrunkRequest",
    "GetToolRequest",
    "GetValidationResultRequest",
    "GetVersionRequest",
    "HumanAgentAssistantConfig",
    "HumanAgentAssistantEvent",
    "HumanAgentHandoffConfig",
    "ImportAgentRequest",
    "ImportConversationDataOperationMetadata",
    "ImportConversationDataOperationResponse",
    "ImportConversationDataRequest",
    "ImportDocumentTemplate",
    "ImportDocumentsRequest",
    "ImportDocumentsResponse",
    "InferenceParameter",
    "IngestContextReferencesRequest",
    "IngestContextReferencesResponse",
    "IngestedContextReferenceDebugInfo",
    "InitializeEncryptionSpecMetadata",
    "InitializeEncryptionSpecRequest",
    "InitializeEncryptionSpecResponse",
    "InputAudioConfig",
    "InputConfig",
    "InputDataset",
    "InputTextConfig",
    "Intent",
    "IntentBatch",
    "IntentSuggestion",
    "IntentView",
    "IntentsClient",
    "KnowledgeAssistAnswer",
    "KnowledgeAssistDebugInfo",
    "KnowledgeBase",
    "KnowledgeBasesClient",
    "KnowledgeOperationMetadata",
    "ListAnswerRecordsRequest",
    "ListAnswerRecordsResponse",
    "ListContextsRequest",
    "ListContextsResponse",
    "ListConversationDatasetsRequest",
    "ListConversationDatasetsResponse",
    "ListConversationModelEvaluationsRequest",
    "ListConversationModelEvaluationsResponse",
    "ListConversationModelsRequest",
    "ListConversationModelsResponse",
    "ListConversationProfilesRequest",
    "ListConversationProfilesResponse",
    "ListConversationsRequest",
    "ListConversationsResponse",
    "ListDocumentsRequest",
    "ListDocumentsResponse",
    "ListEntityTypesRequest",
    "ListEntityTypesResponse",
    "ListEnvironmentsRequest",
    "ListEnvironmentsResponse",
    "ListGeneratorEvaluationsRequest",
    "ListGeneratorEvaluationsResponse",
    "ListGeneratorsRequest",
    "ListGeneratorsResponse",
    "ListIntentsRequest",
    "ListIntentsResponse",
    "ListKnowledgeBasesRequest",
    "ListKnowledgeBasesResponse",
    "ListMessagesRequest",
    "ListMessagesResponse",
    "ListParticipantsRequest",
    "ListParticipantsResponse",
    "ListSessionEntityTypesRequest",
    "ListSessionEntityTypesResponse",
    "ListSipTrunksRequest",
    "ListSipTrunksResponse",
    "ListToolsRequest",
    "ListToolsResponse",
    "ListVersionsRequest",
    "ListVersionsResponse",
    "LoggingConfig",
    "Message",
    "MessageAnnotation",
    "MessageEntry",
    "NotificationConfig",
    "OriginalDetectIntentRequest",
    "OutputAudio",
    "OutputAudioConfig",
    "OutputAudioEncoding",
    "Participant",
    "ParticipantsClient",
    "QueryInput",
    "QueryParameters",
    "QueryResult",
    "RaiSettings",
    "ReloadDocumentRequest",
    "RestoreAgentRequest",
    "SearchAgentsRequest",
    "SearchAgentsResponse",
    "SearchKnowledgeAnswer",
    "SearchKnowledgeDebugInfo",
    "SearchKnowledgeRequest",
    "SearchKnowledgeResponse",
    "Sentiment",
    "SentimentAnalysisRequestConfig",
    "SentimentAnalysisResult",
    "ServiceLatency",
    "SessionEntityType",
    "SessionEntityTypesClient",
    "SessionsClient",
    "SetAgentRequest",
    "SetSuggestionFeatureConfigOperationMetadata",
    "SetSuggestionFeatureConfigRequest",
    "SipConfig",
    "SipTrunk",
    "SipTrunksClient",
    "SmartReplyAnswer",
    "SmartReplyMetrics",
    "SmartReplyModelMetadata",
    "SpeechContext",
    "SpeechModelVariant",
    "SpeechToTextConfig",
    "SpeechWordInfo",
    "SsmlVoiceGender",
    "StreamingAnalyzeContentRequest",
    "StreamingAnalyzeContentResponse",
    "StreamingDetectIntentRequest",
    "StreamingDetectIntentResponse",
    "StreamingRecognitionResult",
    "SuggestArticlesRequest",
    "SuggestArticlesResponse",
    "SuggestConversationSummaryRequest",
    "SuggestConversationSummaryResponse",
    "SuggestFaqAnswersRequest",
    "SuggestFaqAnswersResponse",
    "SuggestKnowledgeAssistRequest",
    "SuggestKnowledgeAssistResponse",
    "SuggestSmartRepliesRequest",
    "SuggestSmartRepliesResponse",
    "SuggestionDedupingConfig",
    "SuggestionFeature",
    "SuggestionInput",
    "SuggestionResult",
    "SummarizationContext",
    "SummarizationEvaluationMetrics",
    "SummarizationSection",
    "SummarizationSectionList",
    "SummarySuggestion",
    "SynthesizeSpeechConfig",
    "TelephonyDtmf",
    "TelephonyDtmfEvents",
    "TextInput",
    "TextToSpeechSettings",
    "Tool",
    "ToolCall",
    "ToolCallResult",
    "ToolsClient",
    "ToolsetTool",
    "TrainAgentRequest",
    "TriggerEvent",
    "UndeployConversationModelOperationMetadata",
    "UndeployConversationModelRequest",
    "UpdateAnswerRecordRequest",
    "UpdateContextRequest",
    "UpdateConversationProfileRequest",
    "UpdateDocumentRequest",
    "UpdateEntityTypeRequest",
    "UpdateEnvironmentRequest",
    "UpdateFulfillmentRequest",
    "UpdateGeneratorRequest",
    "UpdateIntentRequest",
    "UpdateKnowledgeBaseRequest",
    "UpdateParticipantRequest",
    "UpdateSessionEntityTypeRequest",
    "UpdateSipTrunkRequest",
    "UpdateToolRequest",
    "UpdateVersionRequest",
    "ValidationError",
    "ValidationResult",
    "Version",
    "VersionsClient",
    "VoiceSelectionParams",
    "WebhookRequest",
    "WebhookResponse",
)

api_core.check_python_version("google.cloud.dialogflow_v2")
api_core.check_dependency_versions("google.cloud.dialogflow_v2")
