# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.backupdr_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.backupdr_v1.services.backup_dr",
    "google.cloud.backupdr_v1.services.backup_dr_protection_summary",
    "google.cloud.backupdr_v1.types.backupdr",
    "google.cloud.backupdr_v1.types.backupplan",
    "google.cloud.backupdr_v1.types.backupplanassociation",
    "google.cloud.backupdr_v1.types.backupvault",
    "google.cloud.backupdr_v1.types.backupvault_alloydb",
    "google.cloud.backupdr_v1.types.backupvault_ba",
    "google.cloud.backupdr_v1.types.backupvault_cloudsql",
    "google.cloud.backupdr_v1.types.backupvault_disk",
    "google.cloud.backupdr_v1.types.backupvault_gce",
    "google.cloud.backupdr_v1.types.datasourcereference",
    "google.cloud.backupdr_v1.types.protection_summary",
}


from .services.backup_dr import BackupDRAsyncClient, BackupDRClient
from .services.backup_dr_protection_summary import (
    BackupDrProtectionSummaryAsyncClient,
    BackupDrProtectionSummaryClient,
)
from .types.backupdr import (
    CreateManagementServerRequest,
    DeleteManagementServerRequest,
    GetManagementServerRequest,
    InitializeServiceRequest,
    InitializeServiceResponse,
    ListManagementServersRequest,
    ListManagementServersResponse,
    ManagementServer,
    ManagementURI,
    NetworkConfig,
    OperationMetadata,
    WorkforceIdentityBasedManagementURI,
    WorkforceIdentityBasedOAuth2ClientID,
)
from .types.backupplan import (
    BackupPlan,
    BackupPlanRevision,
    BackupRule,
    BackupWindow,
    CreateBackupPlanRequest,
    DeleteBackupPlanRequest,
    GetBackupPlanRequest,
    GetBackupPlanRevisionRequest,
    ListBackupPlanRevisionsRequest,
    ListBackupPlanRevisionsResponse,
    ListBackupPlansRequest,
    ListBackupPlansResponse,
    StandardSchedule,
    UpdateBackupPlanRequest,
    WeekDayOfMonth,
)
from .types.backupplanassociation import (
    BackupPlanAssociation,
    CreateBackupPlanAssociationRequest,
    DeleteBackupPlanAssociationRequest,
    FetchBackupPlanAssociationsForResourceTypeRequest,
    FetchBackupPlanAssociationsForResourceTypeResponse,
    GetBackupPlanAssociationRequest,
    ListBackupPlanAssociationsRequest,
    ListBackupPlanAssociationsResponse,
    RuleConfigInfo,
    TriggerBackupRequest,
    UpdateBackupPlanAssociationRequest,
)
from .types.backupvault import (
    Backup,
    BackupApplianceBackupConfig,
    BackupApplianceLockInfo,
    BackupConfigInfo,
    BackupConfigState,
    BackupGcpResource,
    BackupLock,
    BackupVault,
    BackupVaultView,
    BackupView,
    CreateBackupVaultRequest,
    DataSource,
    DataSourceBackupApplianceApplication,
    DataSourceGcpResource,
    DeleteBackupRequest,
    DeleteBackupVaultRequest,
    FetchBackupsForResourceTypeRequest,
    FetchBackupsForResourceTypeResponse,
    FetchUsableBackupVaultsRequest,
    FetchUsableBackupVaultsResponse,
    GcpBackupConfig,
    GcpResource,
    GetBackupRequest,
    GetBackupVaultRequest,
    GetDataSourceRequest,
    ListBackupsRequest,
    ListBackupsResponse,
    ListBackupVaultsRequest,
    ListBackupVaultsResponse,
    ListDataSourcesRequest,
    ListDataSourcesResponse,
    RestoreBackupRequest,
    RestoreBackupResponse,
    ServiceLockInfo,
    TargetResource,
    UpdateBackupRequest,
    UpdateBackupVaultRequest,
    UpdateDataSourceRequest,
)
from .types.backupvault_alloydb import (
    AlloyDBClusterBackupPlanAssociationProperties,
    AlloyDbClusterBackupProperties,
    AlloyDBClusterDataSourceProperties,
)
from .types.backupvault_ba import BackupApplianceBackupProperties
from .types.backupvault_cloudsql import (
    CloudSqlInstanceBackupPlanAssociationProperties,
    CloudSqlInstanceBackupProperties,
    CloudSqlInstanceDataSourceProperties,
    CloudSqlInstanceDataSourceReferenceProperties,
    CloudSqlInstanceInitializationConfig,
)
from .types.backupvault_disk import (
    DiskBackupProperties,
    DiskDataSourceProperties,
    DiskRestoreProperties,
    DiskTargetEnvironment,
    RegionDiskTargetEnvironment,
)
from .types.backupvault_gce import (
    AcceleratorConfig,
    AccessConfig,
    AdvancedMachineFeatures,
    AliasIpRange,
    AllocationAffinity,
    AttachedDisk,
    ComputeInstanceBackupProperties,
    ComputeInstanceDataSourceProperties,
    ComputeInstanceRestoreProperties,
    ComputeInstanceTargetEnvironment,
    ConfidentialInstanceConfig,
    CustomerEncryptionKey,
    DisplayDevice,
    Entry,
    GuestOsFeature,
    InstanceParams,
    KeyRevocationActionType,
    Metadata,
    NetworkInterface,
    NetworkPerformanceConfig,
    Scheduling,
    SchedulingDuration,
    ServiceAccount,
    Tags,
)
from .types.datasourcereference import (
    DataSourceBackupConfigInfo,
    DataSourceGcpResourceInfo,
    DataSourceReference,
    FetchDataSourceReferencesForResourceTypeRequest,
    FetchDataSourceReferencesForResourceTypeResponse,
    GetDataSourceReferenceRequest,
    ListDataSourceReferencesRequest,
    ListDataSourceReferencesResponse,
)
from .types.protection_summary import (
    BackupConfigDetails,
    BackupDrPlanConfig,
    BackupDrPlanRule,
    BackupDrTemplateConfig,
    BackupLocation,
    ListResourceBackupConfigsRequest,
    ListResourceBackupConfigsResponse,
    PitrSettings,
    ResourceBackupConfig,
)

__all__ = (
    "BackupDRAsyncClient",
    "BackupDrProtectionSummaryAsyncClient",
    "AcceleratorConfig",
    "AccessConfig",
    "AdvancedMachineFeatures",
    "AliasIpRange",
    "AllocationAffinity",
    "AlloyDBClusterBackupPlanAssociationProperties",
    "AlloyDBClusterDataSourceProperties",
    "AlloyDbClusterBackupProperties",
    "AttachedDisk",
    "Backup",
    "BackupApplianceBackupConfig",
    "BackupApplianceBackupProperties",
    "BackupApplianceLockInfo",
    "BackupConfigDetails",
    "BackupConfigInfo",
    "BackupConfigState",
    "BackupDRClient",
    "BackupDrPlanConfig",
    "BackupDrPlanRule",
    "BackupDrProtectionSummaryClient",
    "BackupDrTemplateConfig",
    "BackupGcpResource",
    "BackupLocation",
    "BackupLock",
    "BackupPlan",
    "BackupPlanAssociation",
    "BackupPlanRevision",
    "BackupRule",
    "BackupVault",
    "BackupVaultView",
    "BackupView",
    "BackupWindow",
    "CloudSqlInstanceBackupPlanAssociationProperties",
    "CloudSqlInstanceBackupProperties",
    "CloudSqlInstanceDataSourceProperties",
    "CloudSqlInstanceDataSourceReferenceProperties",
    "CloudSqlInstanceInitializationConfig",
    "ComputeInstanceBackupProperties",
    "ComputeInstanceDataSourceProperties",
    "ComputeInstanceRestoreProperties",
    "ComputeInstanceTargetEnvironment",
    "ConfidentialInstanceConfig",
    "CreateBackupPlanAssociationRequest",
    "CreateBackupPlanRequest",
    "CreateBackupVaultRequest",
    "CreateManagementServerRequest",
    "CustomerEncryptionKey",
    "DataSource",
    "DataSourceBackupApplianceApplication",
    "DataSourceBackupConfigInfo",
    "DataSourceGcpResource",
    "DataSourceGcpResourceInfo",
    "DataSourceReference",
    "DeleteBackupPlanAssociationRequest",
    "DeleteBackupPlanRequest",
    "DeleteBackupRequest",
    "DeleteBackupVaultRequest",
    "DeleteManagementServerRequest",
    "DiskBackupProperties",
    "DiskDataSourceProperties",
    "DiskRestoreProperties",
    "DiskTargetEnvironment",
    "DisplayDevice",
    "Entry",
    "FetchBackupPlanAssociationsForResourceTypeRequest",
    "FetchBackupPlanAssociationsForResourceTypeResponse",
    "FetchBackupsForResourceTypeRequest",
    "FetchBackupsForResourceTypeResponse",
    "FetchDataSourceReferencesForResourceTypeRequest",
    "FetchDataSourceReferencesForResourceTypeResponse",
    "FetchUsableBackupVaultsRequest",
    "FetchUsableBackupVaultsResponse",
    "GcpBackupConfig",
    "GcpResource",
    "GetBackupPlanAssociationRequest",
    "GetBackupPlanRequest",
    "GetBackupPlanRevisionRequest",
    "GetBackupRequest",
    "GetBackupVaultRequest",
    "GetDataSourceReferenceRequest",
    "GetDataSourceRequest",
    "GetManagementServerRequest",
    "GuestOsFeature",
    "InitializeServiceRequest",
    "InitializeServiceResponse",
    "InstanceParams",
    "KeyRevocationActionType",
    "ListBackupPlanAssociationsRequest",
    "ListBackupPlanAssociationsResponse",
    "ListBackupPlanRevisionsRequest",
    "ListBackupPlanRevisionsResponse",
    "ListBackupPlansRequest",
    "ListBackupPlansResponse",
    "ListBackupVaultsRequest",
    "ListBackupVaultsResponse",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ListDataSourceReferencesRequest",
    "ListDataSourceReferencesResponse",
    "ListDataSourcesRequest",
    "ListDataSourcesResponse",
    "ListManagementServersRequest",
    "ListManagementServersResponse",
    "ListResourceBackupConfigsRequest",
    "ListResourceBackupConfigsResponse",
    "ManagementServer",
    "ManagementURI",
    "Metadata",
    "NetworkConfig",
    "NetworkInterface",
    "NetworkPerformanceConfig",
    "OperationMetadata",
    "PitrSettings",
    "RegionDiskTargetEnvironment",
    "ResourceBackupConfig",
    "RestoreBackupRequest",
    "RestoreBackupResponse",
    "RuleConfigInfo",
    "Scheduling",
    "SchedulingDuration",
    "ServiceAccount",
    "ServiceLockInfo",
    "StandardSchedule",
    "Tags",
    "TargetResource",
    "TriggerBackupRequest",
    "UpdateBackupPlanAssociationRequest",
    "UpdateBackupPlanRequest",
    "UpdateBackupRequest",
    "UpdateBackupVaultRequest",
    "UpdateDataSourceRequest",
    "WeekDayOfMonth",
    "WorkforceIdentityBasedManagementURI",
    "WorkforceIdentityBasedOAuth2ClientID",
)

api_core.check_python_version("google.cloud.backupdr_v1")
api_core.check_dependency_versions("google.cloud.backupdr_v1")
