handleGHRelease: true
manifest: true
tagPullRequestNumber: true

branches:
  - branch: main
    handleGHRelease: true
    tagPullRequestNumber: true
    manifest: true
    manifestFile: .release-please-bulk-manifest.json
    manifestConfig: release-please-bulk-config.json
  - branch: main
    handleGHRelease: true
    tagPullRequestNumber: true
    manifest: true
    manifestFile: .release-please-individual-manifest.json
    manifestConfig: release-please-individual-config.json
