# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.gke_multicloud_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.gke_multicloud_v1.services.attached_clusters",
    "google.cloud.gke_multicloud_v1.services.aws_clusters",
    "google.cloud.gke_multicloud_v1.services.azure_clusters",
    "google.cloud.gke_multicloud_v1.types.attached_resources",
    "google.cloud.gke_multicloud_v1.types.attached_service",
    "google.cloud.gke_multicloud_v1.types.aws_resources",
    "google.cloud.gke_multicloud_v1.types.aws_service",
    "google.cloud.gke_multicloud_v1.types.azure_resources",
    "google.cloud.gke_multicloud_v1.types.azure_service",
    "google.cloud.gke_multicloud_v1.types.common_resources",
}


from .services.attached_clusters import (
    AttachedClustersAsyncClient,
    AttachedClustersClient,
)
from .services.aws_clusters import AwsClustersAsyncClient, AwsClustersClient
from .services.azure_clusters import AzureClustersAsyncClient, AzureClustersClient
from .types.attached_resources import (
    AttachedCluster,
    AttachedClusterError,
    AttachedClusterGroup,
    AttachedClustersAuthorization,
    AttachedClusterUser,
    AttachedOidcConfig,
    AttachedPlatformVersionInfo,
    AttachedProxyConfig,
    AttachedServerConfig,
    KubernetesSecret,
    Label,
    SystemComponentsConfig,
    Toleration,
)
from .types.attached_service import (
    CreateAttachedClusterRequest,
    DeleteAttachedClusterRequest,
    GenerateAttachedClusterAgentTokenRequest,
    GenerateAttachedClusterAgentTokenResponse,
    GenerateAttachedClusterInstallManifestRequest,
    GenerateAttachedClusterInstallManifestResponse,
    GetAttachedClusterRequest,
    GetAttachedServerConfigRequest,
    ImportAttachedClusterRequest,
    ListAttachedClustersRequest,
    ListAttachedClustersResponse,
    UpdateAttachedClusterRequest,
)
from .types.aws_resources import (
    AwsAuthorization,
    AwsAutoscalingGroupMetricsCollection,
    AwsCluster,
    AwsClusterError,
    AwsClusterGroup,
    AwsClusterNetworking,
    AwsClusterUser,
    AwsConfigEncryption,
    AwsControlPlane,
    AwsDatabaseEncryption,
    AwsInstancePlacement,
    AwsJsonWebKeys,
    AwsK8sVersionInfo,
    AwsNodeConfig,
    AwsNodeManagement,
    AwsNodePool,
    AwsNodePoolAutoscaling,
    AwsNodePoolError,
    AwsOpenIdConfig,
    AwsProxyConfig,
    AwsServerConfig,
    AwsServicesAuthentication,
    AwsSshConfig,
    AwsVolumeTemplate,
    SpotConfig,
    SurgeSettings,
    UpdateSettings,
)
from .types.aws_service import (
    CreateAwsClusterRequest,
    CreateAwsNodePoolRequest,
    DeleteAwsClusterRequest,
    DeleteAwsNodePoolRequest,
    GenerateAwsAccessTokenRequest,
    GenerateAwsAccessTokenResponse,
    GenerateAwsClusterAgentTokenRequest,
    GenerateAwsClusterAgentTokenResponse,
    GetAwsClusterRequest,
    GetAwsJsonWebKeysRequest,
    GetAwsNodePoolRequest,
    GetAwsOpenIdConfigRequest,
    GetAwsServerConfigRequest,
    ListAwsClustersRequest,
    ListAwsClustersResponse,
    ListAwsNodePoolsRequest,
    ListAwsNodePoolsResponse,
    RollbackAwsNodePoolUpdateRequest,
    UpdateAwsClusterRequest,
    UpdateAwsNodePoolRequest,
)
from .types.azure_resources import (
    AzureAuthorization,
    AzureClient,
    AzureCluster,
    AzureClusterError,
    AzureClusterGroup,
    AzureClusterNetworking,
    AzureClusterResources,
    AzureClusterUser,
    AzureConfigEncryption,
    AzureControlPlane,
    AzureDatabaseEncryption,
    AzureDiskTemplate,
    AzureJsonWebKeys,
    AzureK8sVersionInfo,
    AzureNodeConfig,
    AzureNodeManagement,
    AzureNodePool,
    AzureNodePoolAutoscaling,
    AzureNodePoolError,
    AzureOpenIdConfig,
    AzureProxyConfig,
    AzureServerConfig,
    AzureServicesAuthentication,
    AzureSshConfig,
    ReplicaPlacement,
)
from .types.azure_service import (
    CreateAzureClientRequest,
    CreateAzureClusterRequest,
    CreateAzureNodePoolRequest,
    DeleteAzureClientRequest,
    DeleteAzureClusterRequest,
    DeleteAzureNodePoolRequest,
    GenerateAzureAccessTokenRequest,
    GenerateAzureAccessTokenResponse,
    GenerateAzureClusterAgentTokenRequest,
    GenerateAzureClusterAgentTokenResponse,
    GetAzureClientRequest,
    GetAzureClusterRequest,
    GetAzureJsonWebKeysRequest,
    GetAzureNodePoolRequest,
    GetAzureOpenIdConfigRequest,
    GetAzureServerConfigRequest,
    ListAzureClientsRequest,
    ListAzureClientsResponse,
    ListAzureClustersRequest,
    ListAzureClustersResponse,
    ListAzureNodePoolsRequest,
    ListAzureNodePoolsResponse,
    UpdateAzureClusterRequest,
    UpdateAzureNodePoolRequest,
)
from .types.common_resources import (
    BinaryAuthorization,
    CloudMonitoringConfig,
    Fleet,
    Jwk,
    LoggingComponentConfig,
    LoggingConfig,
    ManagedPrometheusConfig,
    MaxPodsConstraint,
    MonitoringConfig,
    NodeKubeletConfig,
    NodeTaint,
    OperationMetadata,
    SecurityPostureConfig,
    WorkloadIdentityConfig,
)

__all__ = (
    "AttachedClustersAsyncClient",
    "AwsClustersAsyncClient",
    "AzureClustersAsyncClient",
    "AttachedCluster",
    "AttachedClusterError",
    "AttachedClusterGroup",
    "AttachedClusterUser",
    "AttachedClustersAuthorization",
    "AttachedClustersClient",
    "AttachedOidcConfig",
    "AttachedPlatformVersionInfo",
    "AttachedProxyConfig",
    "AttachedServerConfig",
    "AwsAuthorization",
    "AwsAutoscalingGroupMetricsCollection",
    "AwsCluster",
    "AwsClusterError",
    "AwsClusterGroup",
    "AwsClusterNetworking",
    "AwsClusterUser",
    "AwsClustersClient",
    "AwsConfigEncryption",
    "AwsControlPlane",
    "AwsDatabaseEncryption",
    "AwsInstancePlacement",
    "AwsJsonWebKeys",
    "AwsK8sVersionInfo",
    "AwsNodeConfig",
    "AwsNodeManagement",
    "AwsNodePool",
    "AwsNodePoolAutoscaling",
    "AwsNodePoolError",
    "AwsOpenIdConfig",
    "AwsProxyConfig",
    "AwsServerConfig",
    "AwsServicesAuthentication",
    "AwsSshConfig",
    "AwsVolumeTemplate",
    "AzureAuthorization",
    "AzureClient",
    "AzureCluster",
    "AzureClusterError",
    "AzureClusterGroup",
    "AzureClusterNetworking",
    "AzureClusterResources",
    "AzureClusterUser",
    "AzureClustersClient",
    "AzureConfigEncryption",
    "AzureControlPlane",
    "AzureDatabaseEncryption",
    "AzureDiskTemplate",
    "AzureJsonWebKeys",
    "AzureK8sVersionInfo",
    "AzureNodeConfig",
    "AzureNodeManagement",
    "AzureNodePool",
    "AzureNodePoolAutoscaling",
    "AzureNodePoolError",
    "AzureOpenIdConfig",
    "AzureProxyConfig",
    "AzureServerConfig",
    "AzureServicesAuthentication",
    "AzureSshConfig",
    "BinaryAuthorization",
    "CloudMonitoringConfig",
    "CreateAttachedClusterRequest",
    "CreateAwsClusterRequest",
    "CreateAwsNodePoolRequest",
    "CreateAzureClientRequest",
    "CreateAzureClusterRequest",
    "CreateAzureNodePoolRequest",
    "DeleteAttachedClusterRequest",
    "DeleteAwsClusterRequest",
    "DeleteAwsNodePoolRequest",
    "DeleteAzureClientRequest",
    "DeleteAzureClusterRequest",
    "DeleteAzureNodePoolRequest",
    "Fleet",
    "GenerateAttachedClusterAgentTokenRequest",
    "GenerateAttachedClusterAgentTokenResponse",
    "GenerateAttachedClusterInstallManifestRequest",
    "GenerateAttachedClusterInstallManifestResponse",
    "GenerateAwsAccessTokenRequest",
    "GenerateAwsAccessTokenResponse",
    "GenerateAwsClusterAgentTokenRequest",
    "GenerateAwsClusterAgentTokenResponse",
    "GenerateAzureAccessTokenRequest",
    "GenerateAzureAccessTokenResponse",
    "GenerateAzureClusterAgentTokenRequest",
    "GenerateAzureClusterAgentTokenResponse",
    "GetAttachedClusterRequest",
    "GetAttachedServerConfigRequest",
    "GetAwsClusterRequest",
    "GetAwsJsonWebKeysRequest",
    "GetAwsNodePoolRequest",
    "GetAwsOpenIdConfigRequest",
    "GetAwsServerConfigRequest",
    "GetAzureClientRequest",
    "GetAzureClusterRequest",
    "GetAzureJsonWebKeysRequest",
    "GetAzureNodePoolRequest",
    "GetAzureOpenIdConfigRequest",
    "GetAzureServerConfigRequest",
    "ImportAttachedClusterRequest",
    "Jwk",
    "KubernetesSecret",
    "Label",
    "ListAttachedClustersRequest",
    "ListAttachedClustersResponse",
    "ListAwsClustersRequest",
    "ListAwsClustersResponse",
    "ListAwsNodePoolsRequest",
    "ListAwsNodePoolsResponse",
    "ListAzureClientsRequest",
    "ListAzureClientsResponse",
    "ListAzureClustersRequest",
    "ListAzureClustersResponse",
    "ListAzureNodePoolsRequest",
    "ListAzureNodePoolsResponse",
    "LoggingComponentConfig",
    "LoggingConfig",
    "ManagedPrometheusConfig",
    "MaxPodsConstraint",
    "MonitoringConfig",
    "NodeKubeletConfig",
    "NodeTaint",
    "OperationMetadata",
    "ReplicaPlacement",
    "RollbackAwsNodePoolUpdateRequest",
    "SecurityPostureConfig",
    "SpotConfig",
    "SurgeSettings",
    "SystemComponentsConfig",
    "Toleration",
    "UpdateAttachedClusterRequest",
    "UpdateAwsClusterRequest",
    "UpdateAwsNodePoolRequest",
    "UpdateAzureClusterRequest",
    "UpdateAzureNodePoolRequest",
    "UpdateSettings",
    "WorkloadIdentityConfig",
)

api_core.check_python_version("google.cloud.gke_multicloud_v1")
api_core.check_dependency_versions("google.cloud.gke_multicloud_v1")
