# -*- coding: utf-8 -*-
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.dataproc_v1 import gapic_version as package_version

__version__ = package_version.__version__


from .services.autoscaling_policy_service import (
    AutoscalingPolicyServiceAsyncClient,
    AutoscalingPolicyServiceClient,
)
from .services.batch_controller import BatchControllerAsyncClient, BatchControllerClient
from .services.cluster_controller import (
    ClusterControllerAsyncClient,
    ClusterControllerClient,
)
from .services.job_controller import JobControllerAsyncClient, JobControllerClient
from .services.node_group_controller import (
    NodeGroupControllerAsyncClient,
    NodeGroupControllerClient,
)
from .services.workflow_template_service import (
    WorkflowTemplateServiceAsyncClient,
    WorkflowTemplateServiceClient,
)
from .types.autoscaling_policies import (
    AutoscalingPolicy,
    BasicAutoscalingAlgorithm,
    BasicYarnAutoscalingConfig,
    CreateAutoscalingPolicyRequest,
    DeleteAutoscalingPolicyRequest,
    GetAutoscalingPolicyRequest,
    InstanceGroupAutoscalingPolicyConfig,
    ListAutoscalingPoliciesRequest,
    ListAutoscalingPoliciesResponse,
    UpdateAutoscalingPolicyRequest,
)
from .types.batches import (
    Batch,
    CreateBatchRequest,
    DeleteBatchRequest,
    GetBatchRequest,
    ListBatchesRequest,
    ListBatchesResponse,
    PySparkBatch,
    SparkBatch,
    SparkRBatch,
    SparkSqlBatch,
)
from .types.clusters import (
    AcceleratorConfig,
    AutoscalingConfig,
    AuxiliaryNodeGroup,
    AuxiliaryServicesConfig,
    Cluster,
    ClusterConfig,
    ClusterMetrics,
    ClusterStatus,
    ConfidentialInstanceConfig,
    CreateClusterRequest,
    DataprocMetricConfig,
    DeleteClusterRequest,
    DiagnoseClusterRequest,
    DiagnoseClusterResults,
    DiskConfig,
    EncryptionConfig,
    EndpointConfig,
    GceClusterConfig,
    GetClusterRequest,
    IdentityConfig,
    InstanceFlexibilityPolicy,
    InstanceGroupConfig,
    InstanceReference,
    KerberosConfig,
    LifecycleConfig,
    ListClustersRequest,
    ListClustersResponse,
    ManagedGroupConfig,
    MetastoreConfig,
    NodeGroup,
    NodeGroupAffinity,
    NodeInitializationAction,
    ReservationAffinity,
    SecurityConfig,
    ShieldedInstanceConfig,
    SoftwareConfig,
    StartClusterRequest,
    StopClusterRequest,
    UpdateClusterRequest,
    VirtualClusterConfig,
)
from .types.jobs import (
    CancelJobRequest,
    DeleteJobRequest,
    DriverSchedulingConfig,
    GetJobRequest,
    HadoopJob,
    HiveJob,
    Job,
    JobMetadata,
    JobPlacement,
    JobReference,
    JobScheduling,
    JobStatus,
    ListJobsRequest,
    ListJobsResponse,
    LoggingConfig,
    PigJob,
    PrestoJob,
    PySparkJob,
    QueryList,
    SparkJob,
    SparkRJob,
    SparkSqlJob,
    SubmitJobRequest,
    TrinoJob,
    UpdateJobRequest,
    YarnApplication,
)
from .types.node_groups import (
    CreateNodeGroupRequest,
    GetNodeGroupRequest,
    ResizeNodeGroupRequest,
)
from .types.operations import (
    BatchOperationMetadata,
    ClusterOperationMetadata,
    ClusterOperationStatus,
    NodeGroupOperationMetadata,
)
from .types.shared import (
    Component,
    EnvironmentConfig,
    ExecutionConfig,
    FailureAction,
    GkeClusterConfig,
    GkeNodePoolConfig,
    GkeNodePoolTarget,
    KubernetesClusterConfig,
    KubernetesSoftwareConfig,
    PeripheralsConfig,
    RuntimeConfig,
    RuntimeInfo,
    SparkHistoryServerConfig,
    UsageMetrics,
    UsageSnapshot,
)
from .types.workflow_templates import (
    ClusterOperation,
    ClusterSelector,
    CreateWorkflowTemplateRequest,
    DeleteWorkflowTemplateRequest,
    GetWorkflowTemplateRequest,
    InstantiateInlineWorkflowTemplateRequest,
    InstantiateWorkflowTemplateRequest,
    ListWorkflowTemplatesRequest,
    ListWorkflowTemplatesResponse,
    ManagedCluster,
    OrderedJob,
    ParameterValidation,
    RegexValidation,
    TemplateParameter,
    UpdateWorkflowTemplateRequest,
    ValueValidation,
    WorkflowGraph,
    WorkflowMetadata,
    WorkflowNode,
    WorkflowTemplate,
    WorkflowTemplatePlacement,
)

__all__ = (
    "AutoscalingPolicyServiceAsyncClient",
    "BatchControllerAsyncClient",
    "ClusterControllerAsyncClient",
    "JobControllerAsyncClient",
    "NodeGroupControllerAsyncClient",
    "WorkflowTemplateServiceAsyncClient",
    "AcceleratorConfig",
    "AutoscalingConfig",
    "AutoscalingPolicy",
    "AutoscalingPolicyServiceClient",
    "AuxiliaryNodeGroup",
    "AuxiliaryServicesConfig",
    "BasicAutoscalingAlgorithm",
    "BasicYarnAutoscalingConfig",
    "Batch",
    "BatchControllerClient",
    "BatchOperationMetadata",
    "CancelJobRequest",
    "Cluster",
    "ClusterConfig",
    "ClusterControllerClient",
    "ClusterMetrics",
    "ClusterOperation",
    "ClusterOperationMetadata",
    "ClusterOperationStatus",
    "ClusterSelector",
    "ClusterStatus",
    "Component",
    "ConfidentialInstanceConfig",
    "CreateAutoscalingPolicyRequest",
    "CreateBatchRequest",
    "CreateClusterRequest",
    "CreateNodeGroupRequest",
    "CreateWorkflowTemplateRequest",
    "DataprocMetricConfig",
    "DeleteAutoscalingPolicyRequest",
    "DeleteBatchRequest",
    "DeleteClusterRequest",
    "DeleteJobRequest",
    "DeleteWorkflowTemplateRequest",
    "DiagnoseClusterRequest",
    "DiagnoseClusterResults",
    "DiskConfig",
    "DriverSchedulingConfig",
    "EncryptionConfig",
    "EndpointConfig",
    "EnvironmentConfig",
    "ExecutionConfig",
    "FailureAction",
    "GceClusterConfig",
    "GetAutoscalingPolicyRequest",
    "GetBatchRequest",
    "GetClusterRequest",
    "GetJobRequest",
    "GetNodeGroupRequest",
    "GetWorkflowTemplateRequest",
    "GkeClusterConfig",
    "GkeNodePoolConfig",
    "GkeNodePoolTarget",
    "HadoopJob",
    "HiveJob",
    "IdentityConfig",
    "InstanceFlexibilityPolicy",
    "InstanceGroupAutoscalingPolicyConfig",
    "InstanceGroupConfig",
    "InstanceReference",
    "InstantiateInlineWorkflowTemplateRequest",
    "InstantiateWorkflowTemplateRequest",
    "Job",
    "JobControllerClient",
    "JobMetadata",
    "JobPlacement",
    "JobReference",
    "JobScheduling",
    "JobStatus",
    "KerberosConfig",
    "KubernetesClusterConfig",
    "KubernetesSoftwareConfig",
    "LifecycleConfig",
    "ListAutoscalingPoliciesRequest",
    "ListAutoscalingPoliciesResponse",
    "ListBatchesRequest",
    "ListBatchesResponse",
    "ListClustersRequest",
    "ListClustersResponse",
    "ListJobsRequest",
    "ListJobsResponse",
    "ListWorkflowTemplatesRequest",
    "ListWorkflowTemplatesResponse",
    "LoggingConfig",
    "ManagedCluster",
    "ManagedGroupConfig",
    "MetastoreConfig",
    "NodeGroup",
    "NodeGroupAffinity",
    "NodeGroupControllerClient",
    "NodeGroupOperationMetadata",
    "NodeInitializationAction",
    "OrderedJob",
    "ParameterValidation",
    "PeripheralsConfig",
    "PigJob",
    "PrestoJob",
    "PySparkBatch",
    "PySparkJob",
    "QueryList",
    "RegexValidation",
    "ReservationAffinity",
    "ResizeNodeGroupRequest",
    "RuntimeConfig",
    "RuntimeInfo",
    "SecurityConfig",
    "ShieldedInstanceConfig",
    "SoftwareConfig",
    "SparkBatch",
    "SparkHistoryServerConfig",
    "SparkJob",
    "SparkRBatch",
    "SparkRJob",
    "SparkSqlBatch",
    "SparkSqlJob",
    "StartClusterRequest",
    "StopClusterRequest",
    "SubmitJobRequest",
    "TemplateParameter",
    "TrinoJob",
    "UpdateAutoscalingPolicyRequest",
    "UpdateClusterRequest",
    "UpdateJobRequest",
    "UpdateWorkflowTemplateRequest",
    "UsageMetrics",
    "UsageSnapshot",
    "ValueValidation",
    "VirtualClusterConfig",
    "WorkflowGraph",
    "WorkflowMetadata",
    "WorkflowNode",
    "WorkflowTemplate",
    "WorkflowTemplatePlacement",
    "WorkflowTemplateServiceClient",
    "YarnApplication",
)
