# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.chronicle_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.chronicle_v1.services.big_query_export_service",
    "google.cloud.chronicle_v1.services.dashboard_chart_service",
    "google.cloud.chronicle_v1.services.dashboard_query_service",
    "google.cloud.chronicle_v1.services.data_access_control_service",
    "google.cloud.chronicle_v1.services.data_table_service",
    "google.cloud.chronicle_v1.services.entity_service",
    "google.cloud.chronicle_v1.services.featured_content_native_dashboard_service",
    "google.cloud.chronicle_v1.services.findings_refinement_service",
    "google.cloud.chronicle_v1.services.instance_service",
    "google.cloud.chronicle_v1.services.native_dashboard_service",
    "google.cloud.chronicle_v1.services.reference_list_service",
    "google.cloud.chronicle_v1.services.rule_execution_error_service",
    "google.cloud.chronicle_v1.services.rule_service",
    "google.cloud.chronicle_v1.types.big_query_export",
    "google.cloud.chronicle_v1.types.dashboard_chart",
    "google.cloud.chronicle_v1.types.dashboard_query",
    "google.cloud.chronicle_v1.types.data_access_control",
    "google.cloud.chronicle_v1.types.data_table",
    "google.cloud.chronicle_v1.types.entity",
    "google.cloud.chronicle_v1.types.featured_content_metadata",
    "google.cloud.chronicle_v1.types.featured_content_native_dashboard",
    "google.cloud.chronicle_v1.types.findings_refinement",
    "google.cloud.chronicle_v1.types.instance",
    "google.cloud.chronicle_v1.types.native_dashboard",
    "google.cloud.chronicle_v1.types.reference_list",
    "google.cloud.chronicle_v1.types.rule",
    "google.cloud.chronicle_v1.types.rule_execution_error",
}


from .services.big_query_export_service import (
    BigQueryExportServiceAsyncClient,
    BigQueryExportServiceClient,
)
from .services.dashboard_chart_service import (
    DashboardChartServiceAsyncClient,
    DashboardChartServiceClient,
)
from .services.dashboard_query_service import (
    DashboardQueryServiceAsyncClient,
    DashboardQueryServiceClient,
)
from .services.data_access_control_service import (
    DataAccessControlServiceAsyncClient,
    DataAccessControlServiceClient,
)
from .services.data_table_service import (
    DataTableServiceAsyncClient,
    DataTableServiceClient,
)
from .services.entity_service import EntityServiceAsyncClient, EntityServiceClient
from .services.featured_content_native_dashboard_service import (
    FeaturedContentNativeDashboardServiceAsyncClient,
    FeaturedContentNativeDashboardServiceClient,
)
from .services.findings_refinement_service import (
    FindingsRefinementServiceAsyncClient,
    FindingsRefinementServiceClient,
)
from .services.instance_service import InstanceServiceAsyncClient, InstanceServiceClient
from .services.native_dashboard_service import (
    NativeDashboardServiceAsyncClient,
    NativeDashboardServiceClient,
)
from .services.reference_list_service import (
    ReferenceListServiceAsyncClient,
    ReferenceListServiceClient,
)
from .services.rule_execution_error_service import (
    RuleExecutionErrorServiceAsyncClient,
    RuleExecutionErrorServiceClient,
)
from .services.rule_service import RuleServiceAsyncClient, RuleServiceClient
from .types.big_query_export import (
    BigQueryExport,
    BigQueryExportPackage,
    DataSourceExportSettings,
    GetBigQueryExportRequest,
    LatestExportJobState,
    ProvisionBigQueryExportRequest,
    UpdateBigQueryExportRequest,
)
from .types.dashboard_chart import (
    AxisType,
    BatchGetDashboardChartsRequest,
    BatchGetDashboardChartsResponse,
    Button,
    ButtonStyle,
    DashboardChart,
    GetDashboardChartRequest,
    LegendAlign,
    LegendOrient,
    Markdown,
    MetricDisplayTrend,
    MetricFormat,
    MetricTrendType,
    PlotMode,
    PointSizeType,
    RenderType,
    SeriesStackStrategy,
    SeriesType,
    TileType,
    ToolTipTrigger,
    VisualMapType,
)
from .types.dashboard_query import (
    AdvancedFilterConfig,
    ColumnMetadata,
    DashboardFilter,
    DashboardQuery,
    DataSource,
    ExecuteDashboardQueryRequest,
    ExecuteDashboardQueryResponse,
    FilterOperator,
    FilterOperatorAndValues,
    GetDashboardQueryRequest,
    InAppLink,
    LanguageFeature,
    QueryRuntimeError,
    TimestampMetadata,
    TimeUnit,
)
from .types.data_access_control import (
    CreateDataAccessLabelRequest,
    CreateDataAccessScopeRequest,
    DataAccessLabel,
    DataAccessLabelReference,
    DataAccessScope,
    DeleteDataAccessLabelRequest,
    DeleteDataAccessScopeRequest,
    GetDataAccessLabelRequest,
    GetDataAccessScopeRequest,
    IngestionLabel,
    ListDataAccessLabelsRequest,
    ListDataAccessLabelsResponse,
    ListDataAccessScopesRequest,
    ListDataAccessScopesResponse,
    UpdateDataAccessLabelRequest,
    UpdateDataAccessScopeRequest,
)
from .types.data_table import (
    BulkCreateDataTableRowsRequest,
    BulkCreateDataTableRowsResponse,
    BulkGetDataTableRowsRequest,
    BulkGetDataTableRowsResponse,
    BulkReplaceDataTableRowsRequest,
    BulkReplaceDataTableRowsResponse,
    BulkUpdateDataTableRowsRequest,
    BulkUpdateDataTableRowsResponse,
    CreateDataTableRequest,
    CreateDataTableRowRequest,
    DataTable,
    DataTableColumnInfo,
    DataTableOperationErrors,
    DataTableRow,
    DataTableScopeInfo,
    DataTableUpdateSource,
    DeleteDataTableRequest,
    DeleteDataTableRowRequest,
    GetDataTableOperationErrorsRequest,
    GetDataTableRequest,
    GetDataTableRowRequest,
    ListDataTableRowsRequest,
    ListDataTableRowsResponse,
    ListDataTablesRequest,
    ListDataTablesResponse,
    UpdateDataTableRequest,
    UpdateDataTableRowRequest,
)
from .types.entity import (
    CreateWatchlistRequest,
    DeleteWatchlistRequest,
    GetWatchlistRequest,
    ListWatchlistsRequest,
    ListWatchlistsResponse,
    UpdateWatchlistRequest,
    Watchlist,
    WatchlistUserPreferences,
)
from .types.featured_content_metadata import FeaturedContentMetadata
from .types.featured_content_native_dashboard import (
    FeaturedContentNativeDashboard,
    GetFeaturedContentNativeDashboardRequest,
    InstallFeaturedContentNativeDashboardRequest,
    InstallFeaturedContentNativeDashboardResponse,
    ListFeaturedContentNativeDashboardsRequest,
    ListFeaturedContentNativeDashboardsResponse,
)
from .types.findings_refinement import (
    ComputeAllFindingsRefinementActivitiesRequest,
    ComputeAllFindingsRefinementActivitiesResponse,
    ComputeFindingsRefinementActivityRequest,
    ComputeFindingsRefinementActivityResponse,
    CreateFindingsRefinementRequest,
    DetectionExclusionActivity,
    DetectionExclusionApplication,
    FindingsRefinement,
    FindingsRefinementActivity,
    FindingsRefinementDeployment,
    FindingsRefinementType,
    GetFindingsRefinementDeploymentRequest,
    GetFindingsRefinementRequest,
    ListAllFindingsRefinementDeploymentsRequest,
    ListAllFindingsRefinementDeploymentsResponse,
    ListFindingsRefinementsRequest,
    ListFindingsRefinementsResponse,
    OutcomeFilter,
    UpdateFindingsRefinementDeploymentRequest,
    UpdateFindingsRefinementRequest,
)
from .types.instance import GetInstanceRequest, Instance
from .types.native_dashboard import (
    AddChartRequest,
    AddChartResponse,
    CreateNativeDashboardRequest,
    DashboardAccess,
    DashboardDefinition,
    DashboardType,
    DashboardUserData,
    DeleteNativeDashboardRequest,
    DuplicateChartRequest,
    DuplicateChartResponse,
    DuplicateNativeDashboardRequest,
    EditChartRequest,
    EditChartResponse,
    ExportNativeDashboardsRequest,
    ExportNativeDashboardsResponse,
    GetNativeDashboardRequest,
    ImportExportStatus,
    ImportNativeDashboardsInlineSource,
    ImportNativeDashboardsRequest,
    ImportNativeDashboardsResponse,
    InlineDestination,
    ListNativeDashboardsRequest,
    ListNativeDashboardsResponse,
    NativeDashboard,
    NativeDashboardView,
    NativeDashboardWithChartsAndQueries,
    RemoveChartRequest,
    UpdateNativeDashboardRequest,
)
from .types.reference_list import (
    CreateReferenceListRequest,
    GetReferenceListRequest,
    ListReferenceListsRequest,
    ListReferenceListsResponse,
    ReferenceList,
    ReferenceListEntry,
    ReferenceListError,
    ReferenceListScope,
    ReferenceListSyntaxType,
    ReferenceListView,
    ScopeInfo,
    UpdateReferenceListRequest,
    VerifyReferenceListRequest,
    VerifyReferenceListResponse,
)
from .types.rule import (
    CompilationDiagnostic,
    CompilationPosition,
    CreateRetrohuntRequest,
    CreateRuleRequest,
    DeleteRuleRequest,
    GetRetrohuntRequest,
    GetRuleDeploymentRequest,
    GetRuleRequest,
    InputsUsed,
    ListRetrohuntsRequest,
    ListRetrohuntsResponse,
    ListRuleDeploymentsRequest,
    ListRuleDeploymentsResponse,
    ListRuleRevisionsRequest,
    ListRuleRevisionsResponse,
    ListRulesRequest,
    ListRulesResponse,
    Retrohunt,
    RetrohuntMetadata,
    Rule,
    RuleDeployment,
    RuleType,
    RuleView,
    RunFrequency,
    Severity,
    UpdateRuleDeploymentRequest,
    UpdateRuleRequest,
    VerifyRuleTextRequest,
    VerifyRuleTextResponse,
)
from .types.rule_execution_error import (
    ListRuleExecutionErrorsRequest,
    ListRuleExecutionErrorsResponse,
    RuleExecutionError,
)

__all__ = (
    "BigQueryExportServiceAsyncClient",
    "DashboardChartServiceAsyncClient",
    "DashboardQueryServiceAsyncClient",
    "DataAccessControlServiceAsyncClient",
    "DataTableServiceAsyncClient",
    "EntityServiceAsyncClient",
    "FeaturedContentNativeDashboardServiceAsyncClient",
    "FindingsRefinementServiceAsyncClient",
    "InstanceServiceAsyncClient",
    "NativeDashboardServiceAsyncClient",
    "ReferenceListServiceAsyncClient",
    "RuleExecutionErrorServiceAsyncClient",
    "RuleServiceAsyncClient",
    "AddChartRequest",
    "AddChartResponse",
    "AdvancedFilterConfig",
    "AxisType",
    "BatchGetDashboardChartsRequest",
    "BatchGetDashboardChartsResponse",
    "BigQueryExport",
    "BigQueryExportPackage",
    "BigQueryExportServiceClient",
    "BulkCreateDataTableRowsRequest",
    "BulkCreateDataTableRowsResponse",
    "BulkGetDataTableRowsRequest",
    "BulkGetDataTableRowsResponse",
    "BulkReplaceDataTableRowsRequest",
    "BulkReplaceDataTableRowsResponse",
    "BulkUpdateDataTableRowsRequest",
    "BulkUpdateDataTableRowsResponse",
    "Button",
    "ButtonStyle",
    "ColumnMetadata",
    "CompilationDiagnostic",
    "CompilationPosition",
    "ComputeAllFindingsRefinementActivitiesRequest",
    "ComputeAllFindingsRefinementActivitiesResponse",
    "ComputeFindingsRefinementActivityRequest",
    "ComputeFindingsRefinementActivityResponse",
    "CreateDataAccessLabelRequest",
    "CreateDataAccessScopeRequest",
    "CreateDataTableRequest",
    "CreateDataTableRowRequest",
    "CreateFindingsRefinementRequest",
    "CreateNativeDashboardRequest",
    "CreateReferenceListRequest",
    "CreateRetrohuntRequest",
    "CreateRuleRequest",
    "CreateWatchlistRequest",
    "DashboardAccess",
    "DashboardChart",
    "DashboardChartServiceClient",
    "DashboardDefinition",
    "DashboardFilter",
    "DashboardQuery",
    "DashboardQueryServiceClient",
    "DashboardType",
    "DashboardUserData",
    "DataAccessControlServiceClient",
    "DataAccessLabel",
    "DataAccessLabelReference",
    "DataAccessScope",
    "DataSource",
    "DataSourceExportSettings",
    "DataTable",
    "DataTableColumnInfo",
    "DataTableOperationErrors",
    "DataTableRow",
    "DataTableScopeInfo",
    "DataTableServiceClient",
    "DataTableUpdateSource",
    "DeleteDataAccessLabelRequest",
    "DeleteDataAccessScopeRequest",
    "DeleteDataTableRequest",
    "DeleteDataTableRowRequest",
    "DeleteNativeDashboardRequest",
    "DeleteRuleRequest",
    "DeleteWatchlistRequest",
    "DetectionExclusionActivity",
    "DetectionExclusionApplication",
    "DuplicateChartRequest",
    "DuplicateChartResponse",
    "DuplicateNativeDashboardRequest",
    "EditChartRequest",
    "EditChartResponse",
    "EntityServiceClient",
    "ExecuteDashboardQueryRequest",
    "ExecuteDashboardQueryResponse",
    "ExportNativeDashboardsRequest",
    "ExportNativeDashboardsResponse",
    "FeaturedContentMetadata",
    "FeaturedContentNativeDashboard",
    "FeaturedContentNativeDashboardServiceClient",
    "FilterOperator",
    "FilterOperatorAndValues",
    "FindingsRefinement",
    "FindingsRefinementActivity",
    "FindingsRefinementDeployment",
    "FindingsRefinementServiceClient",
    "FindingsRefinementType",
    "GetBigQueryExportRequest",
    "GetDashboardChartRequest",
    "GetDashboardQueryRequest",
    "GetDataAccessLabelRequest",
    "GetDataAccessScopeRequest",
    "GetDataTableOperationErrorsRequest",
    "GetDataTableRequest",
    "GetDataTableRowRequest",
    "GetFeaturedContentNativeDashboardRequest",
    "GetFindingsRefinementDeploymentRequest",
    "GetFindingsRefinementRequest",
    "GetInstanceRequest",
    "GetNativeDashboardRequest",
    "GetReferenceListRequest",
    "GetRetrohuntRequest",
    "GetRuleDeploymentRequest",
    "GetRuleRequest",
    "GetWatchlistRequest",
    "ImportExportStatus",
    "ImportNativeDashboardsInlineSource",
    "ImportNativeDashboardsRequest",
    "ImportNativeDashboardsResponse",
    "InAppLink",
    "IngestionLabel",
    "InlineDestination",
    "InputsUsed",
    "InstallFeaturedContentNativeDashboardRequest",
    "InstallFeaturedContentNativeDashboardResponse",
    "Instance",
    "InstanceServiceClient",
    "LanguageFeature",
    "LatestExportJobState",
    "LegendAlign",
    "LegendOrient",
    "ListAllFindingsRefinementDeploymentsRequest",
    "ListAllFindingsRefinementDeploymentsResponse",
    "ListDataAccessLabelsRequest",
    "ListDataAccessLabelsResponse",
    "ListDataAccessScopesRequest",
    "ListDataAccessScopesResponse",
    "ListDataTableRowsRequest",
    "ListDataTableRowsResponse",
    "ListDataTablesRequest",
    "ListDataTablesResponse",
    "ListFeaturedContentNativeDashboardsRequest",
    "ListFeaturedContentNativeDashboardsResponse",
    "ListFindingsRefinementsRequest",
    "ListFindingsRefinementsResponse",
    "ListNativeDashboardsRequest",
    "ListNativeDashboardsResponse",
    "ListReferenceListsRequest",
    "ListReferenceListsResponse",
    "ListRetrohuntsRequest",
    "ListRetrohuntsResponse",
    "ListRuleDeploymentsRequest",
    "ListRuleDeploymentsResponse",
    "ListRuleExecutionErrorsRequest",
    "ListRuleExecutionErrorsResponse",
    "ListRuleRevisionsRequest",
    "ListRuleRevisionsResponse",
    "ListRulesRequest",
    "ListRulesResponse",
    "ListWatchlistsRequest",
    "ListWatchlistsResponse",
    "Markdown",
    "MetricDisplayTrend",
    "MetricFormat",
    "MetricTrendType",
    "NativeDashboard",
    "NativeDashboardServiceClient",
    "NativeDashboardView",
    "NativeDashboardWithChartsAndQueries",
    "OutcomeFilter",
    "PlotMode",
    "PointSizeType",
    "ProvisionBigQueryExportRequest",
    "QueryRuntimeError",
    "ReferenceList",
    "ReferenceListEntry",
    "ReferenceListError",
    "ReferenceListScope",
    "ReferenceListServiceClient",
    "ReferenceListSyntaxType",
    "ReferenceListView",
    "RemoveChartRequest",
    "RenderType",
    "Retrohunt",
    "RetrohuntMetadata",
    "Rule",
    "RuleDeployment",
    "RuleExecutionError",
    "RuleExecutionErrorServiceClient",
    "RuleServiceClient",
    "RuleType",
    "RuleView",
    "RunFrequency",
    "ScopeInfo",
    "SeriesStackStrategy",
    "SeriesType",
    "Severity",
    "TileType",
    "TimeUnit",
    "TimestampMetadata",
    "ToolTipTrigger",
    "UpdateBigQueryExportRequest",
    "UpdateDataAccessLabelRequest",
    "UpdateDataAccessScopeRequest",
    "UpdateDataTableRequest",
    "UpdateDataTableRowRequest",
    "UpdateFindingsRefinementDeploymentRequest",
    "UpdateFindingsRefinementRequest",
    "UpdateNativeDashboardRequest",
    "UpdateReferenceListRequest",
    "UpdateRuleDeploymentRequest",
    "UpdateRuleRequest",
    "UpdateWatchlistRequest",
    "VerifyReferenceListRequest",
    "VerifyReferenceListResponse",
    "VerifyRuleTextRequest",
    "VerifyRuleTextResponse",
    "VisualMapType",
    "Watchlist",
    "WatchlistUserPreferences",
)

api_core.check_python_version("google.cloud.chronicle_v1")
api_core.check_dependency_versions("google.cloud.chronicle_v1")
