[mypy]
namespace_packages = True
ignore_missing_imports = False

# Helps mypy navigate the "google" namespace more reliably in 3.10+
explicit_package_bases = True

# Performance: reuse results from previous runs to speed up "nox"
incremental = True

exclude = (?x)(
    ^third_party/
  | tests/unit/resources/
  | tests/unit/gapic/
  )

# TODO(https://github.com/googleapis/gapic-generator-python/issues/2563):
# Dependencies that historically lacks py.typed markers
[mypy-google.iam.*]
ignore_missing_imports = True

[mypy-google.type.*]
ignore_missing_imports = True


# ==============================================================================
# PACKAGE-SPECIFIC OVERRIDES
# ==============================================================================

# --- google-cloud-core ---
[mypy-google.protobuf.*]
ignore_missing_imports = True

# --- bigframes ---
[mypy-cloudpickle.*]
ignore_missing_imports = True
[mypy-flask]
ignore_missing_imports = True
[mypy-pydata_google_auth]
ignore_missing_imports = True
[mypy-google.colab]
ignore_missing_imports = True
[mypy-pytz]
ignore_missing_imports = True
[mypy-pyarrow.*]
ignore_missing_imports = True
[mypy-ibis.*]
ignore_missing_imports = True
[mypy-ipywidgets]
ignore_missing_imports = True
[mypy-google.cloud.pubsub]
ignore_missing_imports = True
[mypy-google.cloud.bigtable]
ignore_missing_imports = True
[mypy-anywidget]
ignore_missing_imports = True

# --- google-cloud-bigtable ---
[mypy-google.cloud.bigtable.*]
check_untyped_defs = True
warn_unreachable = True
disallow_any_generics = True
ignore_errors = True

[mypy-google.cloud.bigtable.data.*]
ignore_errors = False

[mypy-grpc.*]
ignore_missing_imports = True
[mypy-google.auth.*]
ignore_missing_imports = True
[mypy-google.longrunning.*]
ignore_missing_imports = True
[mypy-google.oauth2.*]
ignore_missing_imports = True
[mypy-google.rpc.*]
ignore_missing_imports = True
[mypy-proto.*]
ignore_missing_imports = True
[mypy-pytest]
ignore_missing_imports = True

# --- google-cloud-datastore ---
[mypy-google.cloud.datastore._app_engine_key_pb2]
ignore_errors = True

# TODO(https://github.com/googleapis/gapic-generator-python/issues/2410):
# Remove once this generator bug is fixed
[mypy-google.cloud.datastore_v1.services.datastore.async_client]
ignore_errors = True

[mypy-google.cloud.datastore_v1.services.datastore.client]
ignore_errors = True
