# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.backstory import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.backstory.types.collection",
    "google.backstory.types.data_access",
    "google.backstory.types.entity",
    "google.backstory.types.entity_risk",
    "google.backstory.types.id",
    "google.backstory.types.udm",
}


from .types.collection import (
    Collection,
    DataTableRowInfo,
    Element,
    EntityGraphEnrichment,
    LatencyMetrics,
    Reference,
    ResponsePlatformInfo,
    SoarAlertMetadata,
)
from .types.data_access import DataAccessIngestionLabel, DataAccessLabels
from .types.entity import AtiPrioritization, Entity, EntityMetadata, Metric, Relation
from .types.entity_risk import EntityRisk, RiskDelta
from .types.id import Id
from .types.udm import (
    UDM,
    X509,
    AnalyticsMetadata,
    AppCompatMetadata,
    Artifact,
    ArtifactClient,
    Asset,
    AttackDetails,
    Attribute,
    Authentication,
    BoolSequence,
    Browser,
    BytesSequence,
    Certificate,
    Cloud,
    Dhcp,
    Dns,
    DNSRecord,
    Domain,
    DoubleSequence,
    Email,
    ExifInfo,
    Extensions,
    Favicon,
    File,
    FileMetadata,
    FileMetadataCodesign,
    FileMetadataImports,
    FileMetadataPE,
    FileMetadataPeResourceInfo,
    FileMetadataSection,
    FileMetadataSignatureInfo,
    FindingVariable,
    Ftp,
    Group,
    GroupedFields,
    Hardware,
    Http,
    Int64Sequence,
    Investigation,
    Label,
    LinuxUtmp,
    Location,
    Metadata,
    Network,
    Noun,
    NtfsFileMetadata,
    OutlookMetadata,
    PDFInfo,
    PeFileMetadata,
    Permission,
    PlatformSoftware,
    PopularityRank,
    PrefetchFileMetadata,
    Prevalence,
    Priority,
    Process,
    ProxyInfo,
    Reason,
    Registry,
    Reputation,
    Resource,
    ResourceUsage,
    Role,
    ScheduledAnacronTask,
    ScheduledCronTask,
    ScheduledTask,
    SecurityResult,
    Service,
    SignatureInfo,
    SignerInfo,
    Smtp,
    Software,
    Srum,
    SSLCertificate,
    Status,
    StringSequence,
    StringToInt64MapEntry,
    SystemEventDetails,
    Tags,
    ThreatVerdict,
    TimeOff,
    Tls,
    Tracker,
    Tunnels,
    Uint64Sequence,
    Url,
    User,
    UserAssist,
    UsnJournal,
    Verdict,
    Volume,
    Vulnerabilities,
    Vulnerability,
    WindowsEventLog,
    WindowsScheduledTask,
    WmiPersistenceItem,
)

__all__ = (
    "AnalyticsMetadata",
    "AppCompatMetadata",
    "Artifact",
    "ArtifactClient",
    "Asset",
    "AtiPrioritization",
    "AttackDetails",
    "Attribute",
    "Authentication",
    "BoolSequence",
    "Browser",
    "BytesSequence",
    "Certificate",
    "Cloud",
    "Collection",
    "DNSRecord",
    "DataAccessIngestionLabel",
    "DataAccessLabels",
    "DataTableRowInfo",
    "Dhcp",
    "Dns",
    "Domain",
    "DoubleSequence",
    "Element",
    "Email",
    "Entity",
    "EntityGraphEnrichment",
    "EntityMetadata",
    "EntityRisk",
    "ExifInfo",
    "Extensions",
    "Favicon",
    "File",
    "FileMetadata",
    "FileMetadataCodesign",
    "FileMetadataImports",
    "FileMetadataPE",
    "FileMetadataPeResourceInfo",
    "FileMetadataSection",
    "FileMetadataSignatureInfo",
    "FindingVariable",
    "Ftp",
    "Group",
    "GroupedFields",
    "Hardware",
    "Http",
    "Id",
    "Int64Sequence",
    "Investigation",
    "Label",
    "LatencyMetrics",
    "LinuxUtmp",
    "Location",
    "Metadata",
    "Metric",
    "Network",
    "Noun",
    "NtfsFileMetadata",
    "OutlookMetadata",
    "PDFInfo",
    "PeFileMetadata",
    "Permission",
    "PlatformSoftware",
    "PopularityRank",
    "PrefetchFileMetadata",
    "Prevalence",
    "Priority",
    "Process",
    "ProxyInfo",
    "Reason",
    "Reference",
    "Registry",
    "Relation",
    "Reputation",
    "Resource",
    "ResourceUsage",
    "ResponsePlatformInfo",
    "RiskDelta",
    "Role",
    "SSLCertificate",
    "ScheduledAnacronTask",
    "ScheduledCronTask",
    "ScheduledTask",
    "SecurityResult",
    "Service",
    "SignatureInfo",
    "SignerInfo",
    "Smtp",
    "SoarAlertMetadata",
    "Software",
    "Srum",
    "Status",
    "StringSequence",
    "StringToInt64MapEntry",
    "SystemEventDetails",
    "Tags",
    "ThreatVerdict",
    "TimeOff",
    "Tls",
    "Tracker",
    "Tunnels",
    "UDM",
    "Uint64Sequence",
    "Url",
    "User",
    "UserAssist",
    "UsnJournal",
    "Verdict",
    "Volume",
    "Vulnerabilities",
    "Vulnerability",
    "WindowsEventLog",
    "WindowsScheduledTask",
    "WmiPersistenceItem",
    "X509",
)

api_core.check_python_version("google.backstory")
api_core.check_dependency_versions("google.backstory")
