# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.dataflow_v1beta3 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.dataflow_v1beta3.services.flex_templates_service",
    "google.cloud.dataflow_v1beta3.services.jobs_v1_beta3",
    "google.cloud.dataflow_v1beta3.services.messages_v1_beta3",
    "google.cloud.dataflow_v1beta3.services.metrics_v1_beta3",
    "google.cloud.dataflow_v1beta3.services.snapshots_v1_beta3",
    "google.cloud.dataflow_v1beta3.services.templates_service",
    "google.cloud.dataflow_v1beta3.types.environment",
    "google.cloud.dataflow_v1beta3.types.jobs",
    "google.cloud.dataflow_v1beta3.types.messages",
    "google.cloud.dataflow_v1beta3.types.metrics",
    "google.cloud.dataflow_v1beta3.types.snapshots",
    "google.cloud.dataflow_v1beta3.types.streaming",
    "google.cloud.dataflow_v1beta3.types.templates",
}


from .services.flex_templates_service import (
    FlexTemplatesServiceAsyncClient,
    FlexTemplatesServiceClient,
)
from .services.jobs_v1_beta3 import JobsV1Beta3AsyncClient, JobsV1Beta3Client
from .services.messages_v1_beta3 import (
    MessagesV1Beta3AsyncClient,
    MessagesV1Beta3Client,
)
from .services.metrics_v1_beta3 import MetricsV1Beta3AsyncClient, MetricsV1Beta3Client
from .services.snapshots_v1_beta3 import (
    SnapshotsV1Beta3AsyncClient,
    SnapshotsV1Beta3Client,
)
from .services.templates_service import (
    TemplatesServiceAsyncClient,
    TemplatesServiceClient,
)
from .types.environment import (
    AutoscalingAlgorithm,
    AutoscalingSettings,
    DataSamplingConfig,
    DebugOptions,
    DefaultPackageSet,
    Disk,
    Environment,
    FlexResourceSchedulingGoal,
    JobType,
    Package,
    SdkHarnessContainerImage,
    ShuffleMode,
    StreamingMode,
    TaskRunnerSettings,
    TeardownPolicy,
    WorkerIPAddressConfiguration,
    WorkerPool,
    WorkerSettings,
)
from .types.jobs import (
    BigQueryIODetails,
    BigTableIODetails,
    CheckActiveJobsRequest,
    CheckActiveJobsResponse,
    CreateJobRequest,
    DatastoreIODetails,
    DisplayData,
    ExecutionStageState,
    ExecutionStageSummary,
    FailedLocation,
    FileIODetails,
    GetJobRequest,
    Job,
    JobExecutionInfo,
    JobExecutionStageInfo,
    JobMetadata,
    JobState,
    JobView,
    KindType,
    ListJobsRequest,
    ListJobsResponse,
    PipelineDescription,
    PubSubIODetails,
    RuntimeUpdatableParams,
    SdkBug,
    SdkVersion,
    ServiceResources,
    SnapshotJobRequest,
    SpannerIODetails,
    Step,
    TransformSummary,
    UpdateJobRequest,
)
from .types.messages import (
    AutoscalingEvent,
    JobMessage,
    JobMessageImportance,
    ListJobMessagesRequest,
    ListJobMessagesResponse,
    StructuredMessage,
)
from .types.metrics import (
    ExecutionState,
    GetJobExecutionDetailsRequest,
    GetJobMetricsRequest,
    GetStageExecutionDetailsRequest,
    HotKeyDebuggingInfo,
    JobExecutionDetails,
    JobMetrics,
    MetricStructuredName,
    MetricUpdate,
    ProgressTimeseries,
    StageExecutionDetails,
    StageSummary,
    Straggler,
    StragglerInfo,
    StragglerSummary,
    StreamingStragglerInfo,
    WorkerDetails,
    WorkItemDetails,
)
from .types.snapshots import (
    DeleteSnapshotRequest,
    DeleteSnapshotResponse,
    GetSnapshotRequest,
    ListSnapshotsRequest,
    ListSnapshotsResponse,
    PubsubSnapshotMetadata,
    Snapshot,
    SnapshotState,
)
from .types.streaming import (
    ComputationTopology,
    CustomSourceLocation,
    DataDiskAssignment,
    KeyRangeDataDiskAssignment,
    KeyRangeLocation,
    MountedDataDisk,
    PubsubLocation,
    StateFamilyConfig,
    StreamingApplianceSnapshotConfig,
    StreamingComputationRanges,
    StreamingSideInputLocation,
    StreamingStageLocation,
    StreamLocation,
    TopologyConfig,
)
from .types.templates import (
    ContainerSpec,
    CreateJobFromTemplateRequest,
    DynamicTemplateLaunchParams,
    FlexTemplateRuntimeEnvironment,
    GetTemplateRequest,
    GetTemplateResponse,
    InvalidTemplateParameters,
    LaunchFlexTemplateParameter,
    LaunchFlexTemplateRequest,
    LaunchFlexTemplateResponse,
    LaunchTemplateParameters,
    LaunchTemplateRequest,
    LaunchTemplateResponse,
    ParameterMetadata,
    ParameterMetadataEnumOption,
    ParameterType,
    RuntimeEnvironment,
    RuntimeMetadata,
    SDKInfo,
    TemplateMetadata,
)

__all__ = (
    "FlexTemplatesServiceAsyncClient",
    "JobsV1Beta3AsyncClient",
    "MessagesV1Beta3AsyncClient",
    "MetricsV1Beta3AsyncClient",
    "SnapshotsV1Beta3AsyncClient",
    "TemplatesServiceAsyncClient",
    "AutoscalingAlgorithm",
    "AutoscalingEvent",
    "AutoscalingSettings",
    "BigQueryIODetails",
    "BigTableIODetails",
    "CheckActiveJobsRequest",
    "CheckActiveJobsResponse",
    "ComputationTopology",
    "ContainerSpec",
    "CreateJobFromTemplateRequest",
    "CreateJobRequest",
    "CustomSourceLocation",
    "DataDiskAssignment",
    "DataSamplingConfig",
    "DatastoreIODetails",
    "DebugOptions",
    "DefaultPackageSet",
    "DeleteSnapshotRequest",
    "DeleteSnapshotResponse",
    "Disk",
    "DisplayData",
    "DynamicTemplateLaunchParams",
    "Environment",
    "ExecutionStageState",
    "ExecutionStageSummary",
    "ExecutionState",
    "FailedLocation",
    "FileIODetails",
    "FlexResourceSchedulingGoal",
    "FlexTemplateRuntimeEnvironment",
    "FlexTemplatesServiceClient",
    "GetJobExecutionDetailsRequest",
    "GetJobMetricsRequest",
    "GetJobRequest",
    "GetSnapshotRequest",
    "GetStageExecutionDetailsRequest",
    "GetTemplateRequest",
    "GetTemplateResponse",
    "HotKeyDebuggingInfo",
    "InvalidTemplateParameters",
    "Job",
    "JobExecutionDetails",
    "JobExecutionInfo",
    "JobExecutionStageInfo",
    "JobMessage",
    "JobMessageImportance",
    "JobMetadata",
    "JobMetrics",
    "JobState",
    "JobType",
    "JobView",
    "JobsV1Beta3Client",
    "KeyRangeDataDiskAssignment",
    "KeyRangeLocation",
    "KindType",
    "LaunchFlexTemplateParameter",
    "LaunchFlexTemplateRequest",
    "LaunchFlexTemplateResponse",
    "LaunchTemplateParameters",
    "LaunchTemplateRequest",
    "LaunchTemplateResponse",
    "ListJobMessagesRequest",
    "ListJobMessagesResponse",
    "ListJobsRequest",
    "ListJobsResponse",
    "ListSnapshotsRequest",
    "ListSnapshotsResponse",
    "MessagesV1Beta3Client",
    "MetricStructuredName",
    "MetricUpdate",
    "MetricsV1Beta3Client",
    "MountedDataDisk",
    "Package",
    "ParameterMetadata",
    "ParameterMetadataEnumOption",
    "ParameterType",
    "PipelineDescription",
    "ProgressTimeseries",
    "PubSubIODetails",
    "PubsubLocation",
    "PubsubSnapshotMetadata",
    "RuntimeEnvironment",
    "RuntimeMetadata",
    "RuntimeUpdatableParams",
    "SDKInfo",
    "SdkBug",
    "SdkHarnessContainerImage",
    "SdkVersion",
    "ServiceResources",
    "ShuffleMode",
    "Snapshot",
    "SnapshotJobRequest",
    "SnapshotState",
    "SnapshotsV1Beta3Client",
    "SpannerIODetails",
    "StageExecutionDetails",
    "StageSummary",
    "StateFamilyConfig",
    "Step",
    "Straggler",
    "StragglerInfo",
    "StragglerSummary",
    "StreamLocation",
    "StreamingApplianceSnapshotConfig",
    "StreamingComputationRanges",
    "StreamingMode",
    "StreamingSideInputLocation",
    "StreamingStageLocation",
    "StreamingStragglerInfo",
    "StructuredMessage",
    "TaskRunnerSettings",
    "TeardownPolicy",
    "TemplateMetadata",
    "TemplatesServiceClient",
    "TopologyConfig",
    "TransformSummary",
    "UpdateJobRequest",
    "WorkItemDetails",
    "WorkerDetails",
    "WorkerIPAddressConfiguration",
    "WorkerPool",
    "WorkerSettings",
)

api_core.check_python_version("google.cloud.dataflow_v1beta3")
api_core.check_dependency_versions("google.cloud.dataflow_v1beta3")
