# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.dataplex_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.dataplex_v1.services.business_glossary_service",
    "google.cloud.dataplex_v1.services.catalog_service",
    "google.cloud.dataplex_v1.services.cmek_service",
    "google.cloud.dataplex_v1.services.content_service",
    "google.cloud.dataplex_v1.services.data_product_service",
    "google.cloud.dataplex_v1.services.data_scan_service",
    "google.cloud.dataplex_v1.services.data_taxonomy_service",
    "google.cloud.dataplex_v1.services.dataplex_service",
    "google.cloud.dataplex_v1.services.metadata_service",
    "google.cloud.dataplex_v1.types.analyze",
    "google.cloud.dataplex_v1.types.approval_workflow",
    "google.cloud.dataplex_v1.types.business_glossary",
    "google.cloud.dataplex_v1.types.catalog",
    "google.cloud.dataplex_v1.types.cmek",
    "google.cloud.dataplex_v1.types.content",
    "google.cloud.dataplex_v1.types.data_discovery",
    "google.cloud.dataplex_v1.types.data_documentation",
    "google.cloud.dataplex_v1.types.data_products",
    "google.cloud.dataplex_v1.types.data_profile",
    "google.cloud.dataplex_v1.types.data_quality",
    "google.cloud.dataplex_v1.types.data_quality_rule_template",
    "google.cloud.dataplex_v1.types.data_taxonomy",
    "google.cloud.dataplex_v1.types.datascans",
    "google.cloud.dataplex_v1.types.datascans_common",
    "google.cloud.dataplex_v1.types.logs",
    "google.cloud.dataplex_v1.types.metadata_",
    "google.cloud.dataplex_v1.types.processing",
    "google.cloud.dataplex_v1.types.resources",
    "google.cloud.dataplex_v1.types.security",
    "google.cloud.dataplex_v1.types.service",
    "google.cloud.dataplex_v1.types.tasks",
}


from .services.business_glossary_service import (
    BusinessGlossaryServiceAsyncClient,
    BusinessGlossaryServiceClient,
)
from .services.catalog_service import CatalogServiceAsyncClient, CatalogServiceClient
from .services.cmek_service import CmekServiceAsyncClient, CmekServiceClient
from .services.content_service import ContentServiceAsyncClient, ContentServiceClient
from .services.data_product_service import (
    DataProductServiceAsyncClient,
    DataProductServiceClient,
)
from .services.data_scan_service import (
    DataScanServiceAsyncClient,
    DataScanServiceClient,
)
from .services.data_taxonomy_service import (
    DataTaxonomyServiceAsyncClient,
    DataTaxonomyServiceClient,
)
from .services.dataplex_service import DataplexServiceAsyncClient, DataplexServiceClient
from .services.metadata_service import MetadataServiceAsyncClient, MetadataServiceClient
from .types.analyze import Content, Environment, Session
from .types.approval_workflow import ChangeRequest, DataProductAccessRequest
from .types.business_glossary import (
    CreateGlossaryCategoryRequest,
    CreateGlossaryRequest,
    CreateGlossaryTermRequest,
    DeleteGlossaryCategoryRequest,
    DeleteGlossaryRequest,
    DeleteGlossaryTermRequest,
    GetGlossaryCategoryRequest,
    GetGlossaryRequest,
    GetGlossaryTermRequest,
    Glossary,
    GlossaryCategory,
    GlossaryTerm,
    ListGlossariesRequest,
    ListGlossariesResponse,
    ListGlossaryCategoriesRequest,
    ListGlossaryCategoriesResponse,
    ListGlossaryTermsRequest,
    ListGlossaryTermsResponse,
    UpdateGlossaryCategoryRequest,
    UpdateGlossaryRequest,
    UpdateGlossaryTermRequest,
)
from .types.catalog import (
    Aspect,
    AspectSource,
    AspectType,
    CancelMetadataJobRequest,
    CreateAspectTypeRequest,
    CreateEntryGroupRequest,
    CreateEntryLinkRequest,
    CreateEntryRequest,
    CreateEntryTypeRequest,
    CreateMetadataFeedRequest,
    CreateMetadataJobRequest,
    DeleteAspectTypeRequest,
    DeleteEntryGroupRequest,
    DeleteEntryLinkRequest,
    DeleteEntryRequest,
    DeleteEntryTypeRequest,
    DeleteMetadataFeedRequest,
    Entry,
    EntryGroup,
    EntryLink,
    EntrySource,
    EntryType,
    EntryView,
    GetAspectTypeRequest,
    GetEntryGroupRequest,
    GetEntryLinkRequest,
    GetEntryRequest,
    GetEntryTypeRequest,
    GetMetadataFeedRequest,
    GetMetadataJobRequest,
    ImportItem,
    ListAspectTypesRequest,
    ListAspectTypesResponse,
    ListEntriesRequest,
    ListEntriesResponse,
    ListEntryGroupsRequest,
    ListEntryGroupsResponse,
    ListEntryTypesRequest,
    ListEntryTypesResponse,
    ListMetadataFeedsRequest,
    ListMetadataFeedsResponse,
    ListMetadataJobsRequest,
    ListMetadataJobsResponse,
    LookupContextRequest,
    LookupContextResponse,
    LookupEntryLinksRequest,
    LookupEntryLinksResponse,
    LookupEntryRequest,
    MetadataFeed,
    MetadataJob,
    ModifyEntryRequest,
    SearchEntriesRequest,
    SearchEntriesResponse,
    SearchEntriesResult,
    TransferStatus,
    UpdateAspectTypeRequest,
    UpdateEntryGroupRequest,
    UpdateEntryLinkRequest,
    UpdateEntryRequest,
    UpdateEntryTypeRequest,
    UpdateMetadataFeedRequest,
)
from .types.cmek import (
    CreateEncryptionConfigRequest,
    DeleteEncryptionConfigRequest,
    EncryptionConfig,
    GetEncryptionConfigRequest,
    ListEncryptionConfigsRequest,
    ListEncryptionConfigsResponse,
    UpdateEncryptionConfigRequest,
)
from .types.data_discovery import DataDiscoveryResult, DataDiscoverySpec
from .types.data_documentation import DataDocumentationResult, DataDocumentationSpec
from .types.data_products import (
    CreateDataAssetRequest,
    CreateDataProductRequest,
    DataAsset,
    DataProduct,
    DeleteDataAssetRequest,
    DeleteDataProductRequest,
    GetDataAssetRequest,
    GetDataProductRequest,
    ListDataAssetsRequest,
    ListDataAssetsResponse,
    ListDataProductsRequest,
    ListDataProductsResponse,
    RequestDataProductAccessRequest,
    RequestDataProductAccessResponse,
    UpdateDataAssetRequest,
    UpdateDataProductRequest,
)
from .types.data_profile import DataProfileResult, DataProfileSpec
from .types.data_quality import (
    DataQualityColumnResult,
    DataQualityDimension,
    DataQualityDimensionResult,
    DataQualityResult,
    DataQualityRule,
    DataQualityRuleResult,
    DataQualitySpec,
)
from .types.data_quality_rule_template import DataQualityRuleTemplate
from .types.data_taxonomy import (
    CreateDataAttributeBindingRequest,
    CreateDataAttributeRequest,
    CreateDataTaxonomyRequest,
    DataAttribute,
    DataAttributeBinding,
    DataTaxonomy,
    DeleteDataAttributeBindingRequest,
    DeleteDataAttributeRequest,
    DeleteDataTaxonomyRequest,
    GetDataAttributeBindingRequest,
    GetDataAttributeRequest,
    GetDataTaxonomyRequest,
    ListDataAttributeBindingsRequest,
    ListDataAttributeBindingsResponse,
    ListDataAttributesRequest,
    ListDataAttributesResponse,
    ListDataTaxonomiesRequest,
    ListDataTaxonomiesResponse,
    UpdateDataAttributeBindingRequest,
    UpdateDataAttributeRequest,
    UpdateDataTaxonomyRequest,
)
from .types.datascans import (
    CancelDataScanJobRequest,
    CancelDataScanJobResponse,
    CreateDataScanRequest,
    DataScan,
    DataScanJob,
    DataScanType,
    DeleteDataScanRequest,
    ExecutionIdentity,
    GenerateDataQualityRulesRequest,
    GenerateDataQualityRulesResponse,
    GetDataScanJobRequest,
    GetDataScanRequest,
    ListDataScanJobsRequest,
    ListDataScanJobsResponse,
    ListDataScansRequest,
    ListDataScansResponse,
    RunDataScanRequest,
    RunDataScanResponse,
    UpdateDataScanRequest,
)
from .types.datascans_common import DataScanCatalogPublishingStatus
from .types.logs import (
    BusinessGlossaryEvent,
    DataQualityScanRuleResult,
    DataScanEvent,
    DiscoveryEvent,
    EntryLinkEvent,
    GovernanceEvent,
    JobEvent,
    SessionEvent,
)
from .types.metadata_ import (
    CreateEntityRequest,
    CreatePartitionRequest,
    DeleteEntityRequest,
    DeletePartitionRequest,
    Entity,
    GetEntityRequest,
    GetPartitionRequest,
    ListEntitiesRequest,
    ListEntitiesResponse,
    ListPartitionsRequest,
    ListPartitionsResponse,
    Partition,
    Schema,
    StorageAccess,
    StorageFormat,
    StorageSystem,
    UpdateEntityRequest,
)
from .types.processing import DataSource, ScannedData, Trigger
from .types.resources import Action, Asset, AssetStatus, Lake, State, Zone
from .types.security import DataAccessSpec, ResourceAccessSpec
from .types.service import (
    CancelJobRequest,
    CreateAssetRequest,
    CreateLakeRequest,
    CreateTaskRequest,
    CreateZoneRequest,
    DeleteAssetRequest,
    DeleteLakeRequest,
    DeleteTaskRequest,
    DeleteZoneRequest,
    GetAssetRequest,
    GetJobRequest,
    GetLakeRequest,
    GetTaskRequest,
    GetZoneRequest,
    ListActionsResponse,
    ListAssetActionsRequest,
    ListAssetsRequest,
    ListAssetsResponse,
    ListJobsRequest,
    ListJobsResponse,
    ListLakeActionsRequest,
    ListLakesRequest,
    ListLakesResponse,
    ListTasksRequest,
    ListTasksResponse,
    ListZoneActionsRequest,
    ListZonesRequest,
    ListZonesResponse,
    OperationMetadata,
    RunTaskRequest,
    RunTaskResponse,
    UpdateAssetRequest,
    UpdateLakeRequest,
    UpdateTaskRequest,
    UpdateZoneRequest,
)
from .types.tasks import Job, Task

__all__ = (
    "BusinessGlossaryServiceAsyncClient",
    "CatalogServiceAsyncClient",
    "CmekServiceAsyncClient",
    "ContentServiceAsyncClient",
    "DataProductServiceAsyncClient",
    "DataScanServiceAsyncClient",
    "DataTaxonomyServiceAsyncClient",
    "DataplexServiceAsyncClient",
    "MetadataServiceAsyncClient",
    "Action",
    "Aspect",
    "AspectSource",
    "AspectType",
    "Asset",
    "AssetStatus",
    "BusinessGlossaryEvent",
    "BusinessGlossaryServiceClient",
    "CancelDataScanJobRequest",
    "CancelDataScanJobResponse",
    "CancelJobRequest",
    "CancelMetadataJobRequest",
    "CatalogServiceClient",
    "ChangeRequest",
    "CmekServiceClient",
    "Content",
    "ContentServiceClient",
    "CreateAspectTypeRequest",
    "CreateAssetRequest",
    "CreateDataAssetRequest",
    "CreateDataAttributeBindingRequest",
    "CreateDataAttributeRequest",
    "CreateDataProductRequest",
    "CreateDataScanRequest",
    "CreateDataTaxonomyRequest",
    "CreateEncryptionConfigRequest",
    "CreateEntityRequest",
    "CreateEntryGroupRequest",
    "CreateEntryLinkRequest",
    "CreateEntryRequest",
    "CreateEntryTypeRequest",
    "CreateGlossaryCategoryRequest",
    "CreateGlossaryRequest",
    "CreateGlossaryTermRequest",
    "CreateLakeRequest",
    "CreateMetadataFeedRequest",
    "CreateMetadataJobRequest",
    "CreatePartitionRequest",
    "CreateTaskRequest",
    "CreateZoneRequest",
    "DataAccessSpec",
    "DataAsset",
    "DataAttribute",
    "DataAttributeBinding",
    "DataDiscoveryResult",
    "DataDiscoverySpec",
    "DataDocumentationResult",
    "DataDocumentationSpec",
    "DataProduct",
    "DataProductAccessRequest",
    "DataProductServiceClient",
    "DataProfileResult",
    "DataProfileSpec",
    "DataQualityColumnResult",
    "DataQualityDimension",
    "DataQualityDimensionResult",
    "DataQualityResult",
    "DataQualityRule",
    "DataQualityRuleResult",
    "DataQualityRuleTemplate",
    "DataQualityScanRuleResult",
    "DataQualitySpec",
    "DataScan",
    "DataScanCatalogPublishingStatus",
    "DataScanEvent",
    "DataScanJob",
    "DataScanServiceClient",
    "DataScanType",
    "DataSource",
    "DataTaxonomy",
    "DataTaxonomyServiceClient",
    "DataplexServiceClient",
    "DeleteAspectTypeRequest",
    "DeleteAssetRequest",
    "DeleteDataAssetRequest",
    "DeleteDataAttributeBindingRequest",
    "DeleteDataAttributeRequest",
    "DeleteDataProductRequest",
    "DeleteDataScanRequest",
    "DeleteDataTaxonomyRequest",
    "DeleteEncryptionConfigRequest",
    "DeleteEntityRequest",
    "DeleteEntryGroupRequest",
    "DeleteEntryLinkRequest",
    "DeleteEntryRequest",
    "DeleteEntryTypeRequest",
    "DeleteGlossaryCategoryRequest",
    "DeleteGlossaryRequest",
    "DeleteGlossaryTermRequest",
    "DeleteLakeRequest",
    "DeleteMetadataFeedRequest",
    "DeletePartitionRequest",
    "DeleteTaskRequest",
    "DeleteZoneRequest",
    "DiscoveryEvent",
    "EncryptionConfig",
    "Entity",
    "Entry",
    "EntryGroup",
    "EntryLink",
    "EntryLinkEvent",
    "EntrySource",
    "EntryType",
    "EntryView",
    "Environment",
    "ExecutionIdentity",
    "GenerateDataQualityRulesRequest",
    "GenerateDataQualityRulesResponse",
    "GetAspectTypeRequest",
    "GetAssetRequest",
    "GetDataAssetRequest",
    "GetDataAttributeBindingRequest",
    "GetDataAttributeRequest",
    "GetDataProductRequest",
    "GetDataScanJobRequest",
    "GetDataScanRequest",
    "GetDataTaxonomyRequest",
    "GetEncryptionConfigRequest",
    "GetEntityRequest",
    "GetEntryGroupRequest",
    "GetEntryLinkRequest",
    "GetEntryRequest",
    "GetEntryTypeRequest",
    "GetGlossaryCategoryRequest",
    "GetGlossaryRequest",
    "GetGlossaryTermRequest",
    "GetJobRequest",
    "GetLakeRequest",
    "GetMetadataFeedRequest",
    "GetMetadataJobRequest",
    "GetPartitionRequest",
    "GetTaskRequest",
    "GetZoneRequest",
    "Glossary",
    "GlossaryCategory",
    "GlossaryTerm",
    "GovernanceEvent",
    "ImportItem",
    "Job",
    "JobEvent",
    "Lake",
    "ListActionsResponse",
    "ListAspectTypesRequest",
    "ListAspectTypesResponse",
    "ListAssetActionsRequest",
    "ListAssetsRequest",
    "ListAssetsResponse",
    "ListDataAssetsRequest",
    "ListDataAssetsResponse",
    "ListDataAttributeBindingsRequest",
    "ListDataAttributeBindingsResponse",
    "ListDataAttributesRequest",
    "ListDataAttributesResponse",
    "ListDataProductsRequest",
    "ListDataProductsResponse",
    "ListDataScanJobsRequest",
    "ListDataScanJobsResponse",
    "ListDataScansRequest",
    "ListDataScansResponse",
    "ListDataTaxonomiesRequest",
    "ListDataTaxonomiesResponse",
    "ListEncryptionConfigsRequest",
    "ListEncryptionConfigsResponse",
    "ListEntitiesRequest",
    "ListEntitiesResponse",
    "ListEntriesRequest",
    "ListEntriesResponse",
    "ListEntryGroupsRequest",
    "ListEntryGroupsResponse",
    "ListEntryTypesRequest",
    "ListEntryTypesResponse",
    "ListGlossariesRequest",
    "ListGlossariesResponse",
    "ListGlossaryCategoriesRequest",
    "ListGlossaryCategoriesResponse",
    "ListGlossaryTermsRequest",
    "ListGlossaryTermsResponse",
    "ListJobsRequest",
    "ListJobsResponse",
    "ListLakeActionsRequest",
    "ListLakesRequest",
    "ListLakesResponse",
    "ListMetadataFeedsRequest",
    "ListMetadataFeedsResponse",
    "ListMetadataJobsRequest",
    "ListMetadataJobsResponse",
    "ListPartitionsRequest",
    "ListPartitionsResponse",
    "ListTasksRequest",
    "ListTasksResponse",
    "ListZoneActionsRequest",
    "ListZonesRequest",
    "ListZonesResponse",
    "LookupContextRequest",
    "LookupContextResponse",
    "LookupEntryLinksRequest",
    "LookupEntryLinksResponse",
    "LookupEntryRequest",
    "MetadataFeed",
    "MetadataJob",
    "MetadataServiceClient",
    "ModifyEntryRequest",
    "OperationMetadata",
    "Partition",
    "RequestDataProductAccessRequest",
    "RequestDataProductAccessResponse",
    "ResourceAccessSpec",
    "RunDataScanRequest",
    "RunDataScanResponse",
    "RunTaskRequest",
    "RunTaskResponse",
    "ScannedData",
    "Schema",
    "SearchEntriesRequest",
    "SearchEntriesResponse",
    "SearchEntriesResult",
    "Session",
    "SessionEvent",
    "State",
    "StorageAccess",
    "StorageFormat",
    "StorageSystem",
    "Task",
    "TransferStatus",
    "Trigger",
    "UpdateAspectTypeRequest",
    "UpdateAssetRequest",
    "UpdateDataAssetRequest",
    "UpdateDataAttributeBindingRequest",
    "UpdateDataAttributeRequest",
    "UpdateDataProductRequest",
    "UpdateDataScanRequest",
    "UpdateDataTaxonomyRequest",
    "UpdateEncryptionConfigRequest",
    "UpdateEntityRequest",
    "UpdateEntryGroupRequest",
    "UpdateEntryLinkRequest",
    "UpdateEntryRequest",
    "UpdateEntryTypeRequest",
    "UpdateGlossaryCategoryRequest",
    "UpdateGlossaryRequest",
    "UpdateGlossaryTermRequest",
    "UpdateLakeRequest",
    "UpdateMetadataFeedRequest",
    "UpdateTaskRequest",
    "UpdateZoneRequest",
    "Zone",
)

api_core.check_python_version("google.cloud.dataplex_v1")
api_core.check_dependency_versions("google.cloud.dataplex_v1")
