# -*- coding: utf-8 -*-
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.channel import gapic_version as package_version

__version__ = package_version.__version__


from google.cloud.channel_v1.services.cloud_channel_reports_service.async_client import (
    CloudChannelReportsServiceAsyncClient,
)
from google.cloud.channel_v1.services.cloud_channel_reports_service.client import (
    CloudChannelReportsServiceClient,
)
from google.cloud.channel_v1.services.cloud_channel_service.async_client import (
    CloudChannelServiceAsyncClient,
)
from google.cloud.channel_v1.services.cloud_channel_service.client import (
    CloudChannelServiceClient,
)
from google.cloud.channel_v1.types.channel_partner_links import (
    ChannelPartnerLink,
    ChannelPartnerLinkState,
    ChannelPartnerLinkView,
)
from google.cloud.channel_v1.types.common import (
    AdminUser,
    CloudIdentityInfo,
    EduData,
    Value,
)
from google.cloud.channel_v1.types.customers import ContactInfo, Customer
from google.cloud.channel_v1.types.entitlement_changes import EntitlementChange
from google.cloud.channel_v1.types.entitlements import (
    AssociationInfo,
    CommitmentSettings,
    Entitlement,
    Parameter,
    ProvisionedService,
    RenewalSettings,
    TransferableSku,
    TransferEligibility,
    TrialSettings,
)
from google.cloud.channel_v1.types.offers import (
    Constraints,
    CustomerConstraints,
    Offer,
    ParameterDefinition,
    PaymentPlan,
    PaymentType,
    Period,
    PeriodType,
    Plan,
    Price,
    PriceByResource,
    PricePhase,
    PriceTier,
    PromotionalOrderType,
    ResourceType,
)
from google.cloud.channel_v1.types.operations import OperationMetadata
from google.cloud.channel_v1.types.products import (
    MarketingInfo,
    Media,
    MediaType,
    Product,
    Sku,
)
from google.cloud.channel_v1.types.reports_service import (
    Column,
    DateRange,
    FetchReportResultsRequest,
    FetchReportResultsResponse,
    ListReportsRequest,
    ListReportsResponse,
    Report,
    ReportJob,
    ReportResultsMetadata,
    ReportStatus,
    ReportValue,
    Row,
    RunReportJobRequest,
    RunReportJobResponse,
)
from google.cloud.channel_v1.types.repricing import (
    ChannelPartnerRepricingConfig,
    ConditionalOverride,
    CustomerRepricingConfig,
    PercentageAdjustment,
    RebillingBasis,
    RepricingAdjustment,
    RepricingCondition,
    RepricingConfig,
    SkuGroupCondition,
)
from google.cloud.channel_v1.types.service import (
    ActivateEntitlementRequest,
    BillableSku,
    CancelEntitlementRequest,
    ChangeOfferRequest,
    ChangeParametersRequest,
    ChangeRenewalSettingsRequest,
    CheckCloudIdentityAccountsExistRequest,
    CheckCloudIdentityAccountsExistResponse,
    CloudIdentityCustomerAccount,
    CreateChannelPartnerLinkRequest,
    CreateChannelPartnerRepricingConfigRequest,
    CreateCustomerRepricingConfigRequest,
    CreateCustomerRequest,
    CreateEntitlementRequest,
    DeleteChannelPartnerRepricingConfigRequest,
    DeleteCustomerRepricingConfigRequest,
    DeleteCustomerRequest,
    GetChannelPartnerLinkRequest,
    GetChannelPartnerRepricingConfigRequest,
    GetCustomerRepricingConfigRequest,
    GetCustomerRequest,
    GetEntitlementRequest,
    ImportCustomerRequest,
    ListChannelPartnerLinksRequest,
    ListChannelPartnerLinksResponse,
    ListChannelPartnerRepricingConfigsRequest,
    ListChannelPartnerRepricingConfigsResponse,
    ListCustomerRepricingConfigsRequest,
    ListCustomerRepricingConfigsResponse,
    ListCustomersRequest,
    ListCustomersResponse,
    ListEntitlementChangesRequest,
    ListEntitlementChangesResponse,
    ListEntitlementsRequest,
    ListEntitlementsResponse,
    ListOffersRequest,
    ListOffersResponse,
    ListProductsRequest,
    ListProductsResponse,
    ListPurchasableOffersRequest,
    ListPurchasableOffersResponse,
    ListPurchasableSkusRequest,
    ListPurchasableSkusResponse,
    ListSkuGroupBillableSkusRequest,
    ListSkuGroupBillableSkusResponse,
    ListSkuGroupsRequest,
    ListSkuGroupsResponse,
    ListSkusRequest,
    ListSkusResponse,
    ListSubscribersRequest,
    ListSubscribersResponse,
    ListTransferableOffersRequest,
    ListTransferableOffersResponse,
    ListTransferableSkusRequest,
    ListTransferableSkusResponse,
    LookupOfferRequest,
    ProvisionCloudIdentityRequest,
    PurchasableOffer,
    PurchasableSku,
    RegisterSubscriberRequest,
    RegisterSubscriberResponse,
    SkuGroup,
    StartPaidServiceRequest,
    SuspendEntitlementRequest,
    TransferableOffer,
    TransferEntitlementsRequest,
    TransferEntitlementsResponse,
    TransferEntitlementsToGoogleRequest,
    UnregisterSubscriberRequest,
    UnregisterSubscriberResponse,
    UpdateChannelPartnerLinkRequest,
    UpdateChannelPartnerRepricingConfigRequest,
    UpdateCustomerRepricingConfigRequest,
    UpdateCustomerRequest,
)
from google.cloud.channel_v1.types.subscriber_event import (
    CustomerEvent,
    EntitlementEvent,
    SubscriberEvent,
)

__all__ = (
    "CloudChannelReportsServiceClient",
    "CloudChannelReportsServiceAsyncClient",
    "CloudChannelServiceClient",
    "CloudChannelServiceAsyncClient",
    "ChannelPartnerLink",
    "ChannelPartnerLinkState",
    "ChannelPartnerLinkView",
    "AdminUser",
    "CloudIdentityInfo",
    "EduData",
    "Value",
    "ContactInfo",
    "Customer",
    "EntitlementChange",
    "AssociationInfo",
    "CommitmentSettings",
    "Entitlement",
    "Parameter",
    "ProvisionedService",
    "RenewalSettings",
    "TransferableSku",
    "TransferEligibility",
    "TrialSettings",
    "Constraints",
    "CustomerConstraints",
    "Offer",
    "ParameterDefinition",
    "Period",
    "Plan",
    "Price",
    "PriceByResource",
    "PricePhase",
    "PriceTier",
    "PaymentPlan",
    "PaymentType",
    "PeriodType",
    "PromotionalOrderType",
    "ResourceType",
    "OperationMetadata",
    "MarketingInfo",
    "Media",
    "Product",
    "Sku",
    "MediaType",
    "Column",
    "DateRange",
    "FetchReportResultsRequest",
    "FetchReportResultsResponse",
    "ListReportsRequest",
    "ListReportsResponse",
    "Report",
    "ReportJob",
    "ReportResultsMetadata",
    "ReportStatus",
    "ReportValue",
    "Row",
    "RunReportJobRequest",
    "RunReportJobResponse",
    "ChannelPartnerRepricingConfig",
    "ConditionalOverride",
    "CustomerRepricingConfig",
    "PercentageAdjustment",
    "RepricingAdjustment",
    "RepricingCondition",
    "RepricingConfig",
    "SkuGroupCondition",
    "RebillingBasis",
    "ActivateEntitlementRequest",
    "BillableSku",
    "CancelEntitlementRequest",
    "ChangeOfferRequest",
    "ChangeParametersRequest",
    "ChangeRenewalSettingsRequest",
    "CheckCloudIdentityAccountsExistRequest",
    "CheckCloudIdentityAccountsExistResponse",
    "CloudIdentityCustomerAccount",
    "CreateChannelPartnerLinkRequest",
    "CreateChannelPartnerRepricingConfigRequest",
    "CreateCustomerRepricingConfigRequest",
    "CreateCustomerRequest",
    "CreateEntitlementRequest",
    "DeleteChannelPartnerRepricingConfigRequest",
    "DeleteCustomerRepricingConfigRequest",
    "DeleteCustomerRequest",
    "GetChannelPartnerLinkRequest",
    "GetChannelPartnerRepricingConfigRequest",
    "GetCustomerRepricingConfigRequest",
    "GetCustomerRequest",
    "GetEntitlementRequest",
    "ImportCustomerRequest",
    "ListChannelPartnerLinksRequest",
    "ListChannelPartnerLinksResponse",
    "ListChannelPartnerRepricingConfigsRequest",
    "ListChannelPartnerRepricingConfigsResponse",
    "ListCustomerRepricingConfigsRequest",
    "ListCustomerRepricingConfigsResponse",
    "ListCustomersRequest",
    "ListCustomersResponse",
    "ListEntitlementChangesRequest",
    "ListEntitlementChangesResponse",
    "ListEntitlementsRequest",
    "ListEntitlementsResponse",
    "ListOffersRequest",
    "ListOffersResponse",
    "ListProductsRequest",
    "ListProductsResponse",
    "ListPurchasableOffersRequest",
    "ListPurchasableOffersResponse",
    "ListPurchasableSkusRequest",
    "ListPurchasableSkusResponse",
    "ListSkuGroupBillableSkusRequest",
    "ListSkuGroupBillableSkusResponse",
    "ListSkuGroupsRequest",
    "ListSkuGroupsResponse",
    "ListSkusRequest",
    "ListSkusResponse",
    "ListSubscribersRequest",
    "ListSubscribersResponse",
    "ListTransferableOffersRequest",
    "ListTransferableOffersResponse",
    "ListTransferableSkusRequest",
    "ListTransferableSkusResponse",
    "LookupOfferRequest",
    "ProvisionCloudIdentityRequest",
    "PurchasableOffer",
    "PurchasableSku",
    "RegisterSubscriberRequest",
    "RegisterSubscriberResponse",
    "SkuGroup",
    "StartPaidServiceRequest",
    "SuspendEntitlementRequest",
    "TransferableOffer",
    "TransferEntitlementsRequest",
    "TransferEntitlementsResponse",
    "TransferEntitlementsToGoogleRequest",
    "UnregisterSubscriberRequest",
    "UnregisterSubscriberResponse",
    "UpdateChannelPartnerLinkRequest",
    "UpdateChannelPartnerRepricingConfigRequest",
    "UpdateCustomerRepricingConfigRequest",
    "UpdateCustomerRequest",
    "CustomerEvent",
    "EntitlementEvent",
    "SubscriberEvent",
)
