# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.bigtable_admin_v2 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.bigtable_admin_v2.services.bigtable_instance_admin",
    "google.cloud.bigtable_admin_v2.services.bigtable_table_admin",
    "google.cloud.bigtable_admin_v2.types.bigtable_instance_admin",
    "google.cloud.bigtable_admin_v2.types.bigtable_table_admin",
    "google.cloud.bigtable_admin_v2.types.common",
    "google.cloud.bigtable_admin_v2.types.instance",
    "google.cloud.bigtable_admin_v2.types.table",
    "google.cloud.bigtable_admin_v2.types.types",
}


from .services.bigtable_instance_admin import (
    BigtableInstanceAdminAsyncClient,
    BigtableInstanceAdminClient,
)
from .services.bigtable_table_admin import (
    BaseBigtableTableAdminAsyncClient,
    BaseBigtableTableAdminClient,
)
from .types.bigtable_instance_admin import (
    CreateAppProfileRequest,
    CreateClusterMetadata,
    CreateClusterRequest,
    CreateInstanceMetadata,
    CreateInstanceRequest,
    CreateLogicalViewMetadata,
    CreateLogicalViewRequest,
    CreateMaterializedViewMetadata,
    CreateMaterializedViewRequest,
    DeleteAppProfileRequest,
    DeleteClusterRequest,
    DeleteInstanceRequest,
    DeleteLogicalViewRequest,
    DeleteMaterializedViewRequest,
    GetAppProfileRequest,
    GetClusterRequest,
    GetInstanceRequest,
    GetLogicalViewRequest,
    GetMaterializedViewRequest,
    ListAppProfilesRequest,
    ListAppProfilesResponse,
    ListClustersRequest,
    ListClustersResponse,
    ListHotTabletsRequest,
    ListHotTabletsResponse,
    ListInstancesRequest,
    ListInstancesResponse,
    ListLogicalViewsRequest,
    ListLogicalViewsResponse,
    ListMaterializedViewsRequest,
    ListMaterializedViewsResponse,
    PartialUpdateClusterMetadata,
    PartialUpdateClusterRequest,
    PartialUpdateInstanceRequest,
    UpdateAppProfileMetadata,
    UpdateAppProfileRequest,
    UpdateClusterMetadata,
    UpdateInstanceMetadata,
    UpdateLogicalViewMetadata,
    UpdateLogicalViewRequest,
    UpdateMaterializedViewMetadata,
    UpdateMaterializedViewRequest,
)
from .types.bigtable_table_admin import (
    CheckConsistencyRequest,
    CheckConsistencyResponse,
    CopyBackupMetadata,
    CopyBackupRequest,
    CreateAuthorizedViewMetadata,
    CreateAuthorizedViewRequest,
    CreateBackupMetadata,
    CreateBackupRequest,
    CreateSchemaBundleMetadata,
    CreateSchemaBundleRequest,
    CreateTableFromSnapshotMetadata,
    CreateTableFromSnapshotRequest,
    CreateTableRequest,
    DataBoostReadLocalWrites,
    DeleteAuthorizedViewRequest,
    DeleteBackupRequest,
    DeleteSchemaBundleRequest,
    DeleteSnapshotRequest,
    DeleteTableRequest,
    DropRowRangeRequest,
    GenerateConsistencyTokenRequest,
    GenerateConsistencyTokenResponse,
    GetAuthorizedViewRequest,
    GetBackupRequest,
    GetSchemaBundleRequest,
    GetSnapshotRequest,
    GetTableRequest,
    ListAuthorizedViewsRequest,
    ListAuthorizedViewsResponse,
    ListBackupsRequest,
    ListBackupsResponse,
    ListSchemaBundlesRequest,
    ListSchemaBundlesResponse,
    ListSnapshotsRequest,
    ListSnapshotsResponse,
    ListTablesRequest,
    ListTablesResponse,
    ModifyColumnFamiliesRequest,
    OptimizeRestoredTableMetadata,
    RestoreTableMetadata,
    RestoreTableRequest,
    SnapshotTableMetadata,
    SnapshotTableRequest,
    StandardReadRemoteWrites,
    UndeleteTableMetadata,
    UndeleteTableRequest,
    UpdateAuthorizedViewMetadata,
    UpdateAuthorizedViewRequest,
    UpdateBackupRequest,
    UpdateSchemaBundleMetadata,
    UpdateSchemaBundleRequest,
    UpdateTableMetadata,
    UpdateTableRequest,
)
from .types.common import OperationProgress, StorageType
from .types.instance import (
    AppProfile,
    AutoscalingLimits,
    AutoscalingTargets,
    Cluster,
    HotTablet,
    Instance,
    LogicalView,
    MaterializedView,
)
from .types.table import (
    AuthorizedView,
    Backup,
    BackupInfo,
    ChangeStreamConfig,
    ColumnFamily,
    EncryptionInfo,
    GcRule,
    ProtoSchema,
    RestoreInfo,
    RestoreSourceType,
    SchemaBundle,
    Snapshot,
    Table,
    TieredStorageConfig,
    TieredStorageRule,
)
from .types.types import Type

__all__ = (
    "BaseBigtableTableAdminAsyncClient",
    "BigtableInstanceAdminAsyncClient",
    "AppProfile",
    "AuthorizedView",
    "AutoscalingLimits",
    "AutoscalingTargets",
    "Backup",
    "BackupInfo",
    "BaseBigtableTableAdminClient",
    "BigtableInstanceAdminClient",
    "ChangeStreamConfig",
    "CheckConsistencyRequest",
    "CheckConsistencyResponse",
    "Cluster",
    "ColumnFamily",
    "CopyBackupMetadata",
    "CopyBackupRequest",
    "CreateAppProfileRequest",
    "CreateAuthorizedViewMetadata",
    "CreateAuthorizedViewRequest",
    "CreateBackupMetadata",
    "CreateBackupRequest",
    "CreateClusterMetadata",
    "CreateClusterRequest",
    "CreateInstanceMetadata",
    "CreateInstanceRequest",
    "CreateLogicalViewMetadata",
    "CreateLogicalViewRequest",
    "CreateMaterializedViewMetadata",
    "CreateMaterializedViewRequest",
    "CreateSchemaBundleMetadata",
    "CreateSchemaBundleRequest",
    "CreateTableFromSnapshotMetadata",
    "CreateTableFromSnapshotRequest",
    "CreateTableRequest",
    "DataBoostReadLocalWrites",
    "DeleteAppProfileRequest",
    "DeleteAuthorizedViewRequest",
    "DeleteBackupRequest",
    "DeleteClusterRequest",
    "DeleteInstanceRequest",
    "DeleteLogicalViewRequest",
    "DeleteMaterializedViewRequest",
    "DeleteSchemaBundleRequest",
    "DeleteSnapshotRequest",
    "DeleteTableRequest",
    "DropRowRangeRequest",
    "EncryptionInfo",
    "GcRule",
    "GenerateConsistencyTokenRequest",
    "GenerateConsistencyTokenResponse",
    "GetAppProfileRequest",
    "GetAuthorizedViewRequest",
    "GetBackupRequest",
    "GetClusterRequest",
    "GetInstanceRequest",
    "GetLogicalViewRequest",
    "GetMaterializedViewRequest",
    "GetSchemaBundleRequest",
    "GetSnapshotRequest",
    "GetTableRequest",
    "HotTablet",
    "Instance",
    "ListAppProfilesRequest",
    "ListAppProfilesResponse",
    "ListAuthorizedViewsRequest",
    "ListAuthorizedViewsResponse",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ListClustersRequest",
    "ListClustersResponse",
    "ListHotTabletsRequest",
    "ListHotTabletsResponse",
    "ListInstancesRequest",
    "ListInstancesResponse",
    "ListLogicalViewsRequest",
    "ListLogicalViewsResponse",
    "ListMaterializedViewsRequest",
    "ListMaterializedViewsResponse",
    "ListSchemaBundlesRequest",
    "ListSchemaBundlesResponse",
    "ListSnapshotsRequest",
    "ListSnapshotsResponse",
    "ListTablesRequest",
    "ListTablesResponse",
    "LogicalView",
    "MaterializedView",
    "ModifyColumnFamiliesRequest",
    "OperationProgress",
    "OptimizeRestoredTableMetadata",
    "PartialUpdateClusterMetadata",
    "PartialUpdateClusterRequest",
    "PartialUpdateInstanceRequest",
    "ProtoSchema",
    "RestoreInfo",
    "RestoreSourceType",
    "RestoreTableMetadata",
    "RestoreTableRequest",
    "SchemaBundle",
    "Snapshot",
    "SnapshotTableMetadata",
    "SnapshotTableRequest",
    "StandardReadRemoteWrites",
    "StorageType",
    "Table",
    "TieredStorageConfig",
    "TieredStorageRule",
    "Type",
    "UndeleteTableMetadata",
    "UndeleteTableRequest",
    "UpdateAppProfileMetadata",
    "UpdateAppProfileRequest",
    "UpdateAuthorizedViewMetadata",
    "UpdateAuthorizedViewRequest",
    "UpdateBackupRequest",
    "UpdateClusterMetadata",
    "UpdateInstanceMetadata",
    "UpdateLogicalViewMetadata",
    "UpdateLogicalViewRequest",
    "UpdateMaterializedViewMetadata",
    "UpdateMaterializedViewRequest",
    "UpdateSchemaBundleMetadata",
    "UpdateSchemaBundleRequest",
    "UpdateTableMetadata",
    "UpdateTableRequest",
)

from .overlay import *  # noqa: F403

__all__ += overlay.__all__  # noqa: F405


api_core.check_python_version("google.cloud.bigtable_admin_v2")
api_core.check_dependency_versions("google.cloud.bigtable_admin_v2")
