# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.kms_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.kms_v1.services.autokey",
    "google.cloud.kms_v1.services.autokey_admin",
    "google.cloud.kms_v1.services.ekm_service",
    "google.cloud.kms_v1.services.hsm_management",
    "google.cloud.kms_v1.services.key_management_service",
    "google.cloud.kms_v1.types.autokey",
    "google.cloud.kms_v1.types.autokey_admin",
    "google.cloud.kms_v1.types.ekm_service",
    "google.cloud.kms_v1.types.hsm_management",
    "google.cloud.kms_v1.types.resources",
    "google.cloud.kms_v1.types.service",
}


from .services.autokey import AutokeyAsyncClient, AutokeyClient
from .services.autokey_admin import AutokeyAdminAsyncClient, AutokeyAdminClient
from .services.ekm_service import EkmServiceAsyncClient, EkmServiceClient
from .services.hsm_management import HsmManagementAsyncClient, HsmManagementClient
from .services.key_management_service import (
    KeyManagementServiceAsyncClient,
    KeyManagementServiceClient,
)
from .types.autokey import (
    CreateKeyHandleMetadata,
    CreateKeyHandleRequest,
    GetKeyHandleRequest,
    KeyHandle,
    ListKeyHandlesRequest,
    ListKeyHandlesResponse,
)
from .types.autokey_admin import (
    AutokeyConfig,
    GetAutokeyConfigRequest,
    ShowEffectiveAutokeyConfigRequest,
    ShowEffectiveAutokeyConfigResponse,
    UpdateAutokeyConfigRequest,
)
from .types.ekm_service import (
    Certificate,
    CreateEkmConnectionRequest,
    EkmConfig,
    EkmConnection,
    GetEkmConfigRequest,
    GetEkmConnectionRequest,
    ListEkmConnectionsRequest,
    ListEkmConnectionsResponse,
    UpdateEkmConfigRequest,
    UpdateEkmConnectionRequest,
    VerifyConnectivityRequest,
    VerifyConnectivityResponse,
)
from .types.hsm_management import (
    ApproveSingleTenantHsmInstanceProposalRequest,
    ApproveSingleTenantHsmInstanceProposalResponse,
    Challenge,
    ChallengeReply,
    CreateSingleTenantHsmInstanceMetadata,
    CreateSingleTenantHsmInstanceProposalMetadata,
    CreateSingleTenantHsmInstanceProposalRequest,
    CreateSingleTenantHsmInstanceRequest,
    DeleteSingleTenantHsmInstanceProposalRequest,
    ExecuteSingleTenantHsmInstanceProposalMetadata,
    ExecuteSingleTenantHsmInstanceProposalRequest,
    ExecuteSingleTenantHsmInstanceProposalResponse,
    GetSingleTenantHsmInstanceProposalRequest,
    GetSingleTenantHsmInstanceRequest,
    ListSingleTenantHsmInstanceProposalsRequest,
    ListSingleTenantHsmInstanceProposalsResponse,
    ListSingleTenantHsmInstancesRequest,
    ListSingleTenantHsmInstancesResponse,
    SingleTenantHsmInstance,
    SingleTenantHsmInstanceProposal,
)
from .types.resources import (
    AccessReason,
    ChecksummedData,
    CryptoKey,
    CryptoKeyVersion,
    CryptoKeyVersionTemplate,
    ExternalProtectionLevelOptions,
    ImportJob,
    KeyAccessJustificationsPolicy,
    KeyOperationAttestation,
    KeyRing,
    ProtectionLevel,
    PublicKey,
    RetiredResource,
)
from .types.service import (
    AsymmetricDecryptRequest,
    AsymmetricDecryptResponse,
    AsymmetricSignRequest,
    AsymmetricSignResponse,
    CreateCryptoKeyRequest,
    CreateCryptoKeyVersionRequest,
    CreateImportJobRequest,
    CreateKeyRingRequest,
    DecapsulateRequest,
    DecapsulateResponse,
    DecryptRequest,
    DecryptResponse,
    DeleteCryptoKeyMetadata,
    DeleteCryptoKeyRequest,
    DeleteCryptoKeyVersionMetadata,
    DeleteCryptoKeyVersionRequest,
    DestroyCryptoKeyVersionRequest,
    Digest,
    EncryptRequest,
    EncryptResponse,
    ExportTrustedKeyWrappedCryptoKeyVersionRequest,
    ExportTrustedKeyWrappedCryptoKeyVersionResponse,
    GenerateRandomBytesRequest,
    GenerateRandomBytesResponse,
    GetCryptoKeyRequest,
    GetCryptoKeyVersionRequest,
    GetImportJobRequest,
    GetKeyRingRequest,
    GetPublicKeyRequest,
    GetRetiredResourceRequest,
    ImportCryptoKeyVersionRequest,
    ImportTrustedKeyWrappedCryptoKeyVersionRequest,
    ListCryptoKeysRequest,
    ListCryptoKeysResponse,
    ListCryptoKeyVersionsRequest,
    ListCryptoKeyVersionsResponse,
    ListImportJobsRequest,
    ListImportJobsResponse,
    ListKeyRingsRequest,
    ListKeyRingsResponse,
    ListRetiredResourcesRequest,
    ListRetiredResourcesResponse,
    LocationMetadata,
    MacSignRequest,
    MacSignResponse,
    MacVerifyRequest,
    MacVerifyResponse,
    RawDecryptRequest,
    RawDecryptResponse,
    RawEncryptRequest,
    RawEncryptResponse,
    RestoreCryptoKeyVersionRequest,
    UpdateCryptoKeyPrimaryVersionRequest,
    UpdateCryptoKeyRequest,
    UpdateCryptoKeyVersionRequest,
)

__all__ = (
    "AutokeyAdminAsyncClient",
    "AutokeyAsyncClient",
    "EkmServiceAsyncClient",
    "HsmManagementAsyncClient",
    "KeyManagementServiceAsyncClient",
    "AccessReason",
    "ApproveSingleTenantHsmInstanceProposalRequest",
    "ApproveSingleTenantHsmInstanceProposalResponse",
    "AsymmetricDecryptRequest",
    "AsymmetricDecryptResponse",
    "AsymmetricSignRequest",
    "AsymmetricSignResponse",
    "AutokeyAdminClient",
    "AutokeyClient",
    "AutokeyConfig",
    "Certificate",
    "Challenge",
    "ChallengeReply",
    "ChecksummedData",
    "CreateCryptoKeyRequest",
    "CreateCryptoKeyVersionRequest",
    "CreateEkmConnectionRequest",
    "CreateImportJobRequest",
    "CreateKeyHandleMetadata",
    "CreateKeyHandleRequest",
    "CreateKeyRingRequest",
    "CreateSingleTenantHsmInstanceMetadata",
    "CreateSingleTenantHsmInstanceProposalMetadata",
    "CreateSingleTenantHsmInstanceProposalRequest",
    "CreateSingleTenantHsmInstanceRequest",
    "CryptoKey",
    "CryptoKeyVersion",
    "CryptoKeyVersionTemplate",
    "DecapsulateRequest",
    "DecapsulateResponse",
    "DecryptRequest",
    "DecryptResponse",
    "DeleteCryptoKeyMetadata",
    "DeleteCryptoKeyRequest",
    "DeleteCryptoKeyVersionMetadata",
    "DeleteCryptoKeyVersionRequest",
    "DeleteSingleTenantHsmInstanceProposalRequest",
    "DestroyCryptoKeyVersionRequest",
    "Digest",
    "EkmConfig",
    "EkmConnection",
    "EkmServiceClient",
    "EncryptRequest",
    "EncryptResponse",
    "ExecuteSingleTenantHsmInstanceProposalMetadata",
    "ExecuteSingleTenantHsmInstanceProposalRequest",
    "ExecuteSingleTenantHsmInstanceProposalResponse",
    "ExportTrustedKeyWrappedCryptoKeyVersionRequest",
    "ExportTrustedKeyWrappedCryptoKeyVersionResponse",
    "ExternalProtectionLevelOptions",
    "GenerateRandomBytesRequest",
    "GenerateRandomBytesResponse",
    "GetAutokeyConfigRequest",
    "GetCryptoKeyRequest",
    "GetCryptoKeyVersionRequest",
    "GetEkmConfigRequest",
    "GetEkmConnectionRequest",
    "GetImportJobRequest",
    "GetKeyHandleRequest",
    "GetKeyRingRequest",
    "GetPublicKeyRequest",
    "GetRetiredResourceRequest",
    "GetSingleTenantHsmInstanceProposalRequest",
    "GetSingleTenantHsmInstanceRequest",
    "HsmManagementClient",
    "ImportCryptoKeyVersionRequest",
    "ImportJob",
    "ImportTrustedKeyWrappedCryptoKeyVersionRequest",
    "KeyAccessJustificationsPolicy",
    "KeyHandle",
    "KeyManagementServiceClient",
    "KeyOperationAttestation",
    "KeyRing",
    "ListCryptoKeyVersionsRequest",
    "ListCryptoKeyVersionsResponse",
    "ListCryptoKeysRequest",
    "ListCryptoKeysResponse",
    "ListEkmConnectionsRequest",
    "ListEkmConnectionsResponse",
    "ListImportJobsRequest",
    "ListImportJobsResponse",
    "ListKeyHandlesRequest",
    "ListKeyHandlesResponse",
    "ListKeyRingsRequest",
    "ListKeyRingsResponse",
    "ListRetiredResourcesRequest",
    "ListRetiredResourcesResponse",
    "ListSingleTenantHsmInstanceProposalsRequest",
    "ListSingleTenantHsmInstanceProposalsResponse",
    "ListSingleTenantHsmInstancesRequest",
    "ListSingleTenantHsmInstancesResponse",
    "LocationMetadata",
    "MacSignRequest",
    "MacSignResponse",
    "MacVerifyRequest",
    "MacVerifyResponse",
    "ProtectionLevel",
    "PublicKey",
    "RawDecryptRequest",
    "RawDecryptResponse",
    "RawEncryptRequest",
    "RawEncryptResponse",
    "RestoreCryptoKeyVersionRequest",
    "RetiredResource",
    "ShowEffectiveAutokeyConfigRequest",
    "ShowEffectiveAutokeyConfigResponse",
    "SingleTenantHsmInstance",
    "SingleTenantHsmInstanceProposal",
    "UpdateAutokeyConfigRequest",
    "UpdateCryptoKeyPrimaryVersionRequest",
    "UpdateCryptoKeyRequest",
    "UpdateCryptoKeyVersionRequest",
    "UpdateEkmConfigRequest",
    "UpdateEkmConnectionRequest",
    "VerifyConnectivityRequest",
    "VerifyConnectivityResponse",
)

api_core.check_python_version("google.cloud.kms_v1")
api_core.check_dependency_versions("google.cloud.kms_v1")
