# -*- coding: utf-8 -*-
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.oracledatabase_v1 import gapic_version as package_version

__version__ = package_version.__version__


from .services.oracle_database import OracleDatabaseAsyncClient, OracleDatabaseClient
from .types.autonomous_database import (
    AllConnectionStrings,
    AutonomousDatabase,
    AutonomousDatabaseApex,
    AutonomousDatabaseConnectionStrings,
    AutonomousDatabaseConnectionUrls,
    AutonomousDatabaseProperties,
    AutonomousDatabaseStandbySummary,
    DatabaseConnectionStringProfile,
    DBWorkload,
    EncryptionKey,
    EncryptionKeyHistoryEntry,
    GenerateType,
    OperationsInsightsState,
    ScheduledOperationDetails,
    SourceConfig,
    State,
)
from .types.autonomous_database_character_set import AutonomousDatabaseCharacterSet
from .types.autonomous_db_backup import (
    AutonomousDatabaseBackup,
    AutonomousDatabaseBackupProperties,
)
from .types.autonomous_db_version import AutonomousDbVersion
from .types.common import (
    ComputeModel,
    CustomerContact,
    DataCollectionOptionsCommon,
    IdentityConnector,
)
from .types.database import (
    Database,
    DatabaseProperties,
    DbBackupConfig,
    GetDatabaseRequest,
    ListDatabasesRequest,
    ListDatabasesResponse,
)
from .types.database_character_set import (
    DatabaseCharacterSet,
    ListDatabaseCharacterSetsRequest,
    ListDatabaseCharacterSetsResponse,
)
from .types.db_node import DbNode, DbNodeProperties
from .types.db_server import DbServer, DbServerProperties
from .types.db_system import (
    CreateDbSystemRequest,
    DataCollectionOptionsDbSystem,
    DbHome,
    DbSystem,
    DbSystemOptions,
    DbSystemProperties,
    DeleteDbSystemRequest,
    GetDbSystemRequest,
    ListDbSystemsRequest,
    ListDbSystemsResponse,
)
from .types.db_system_initial_storage_size import (
    DbSystemInitialStorageSize,
    DbSystemInitialStorageSizeProperties,
    ListDbSystemInitialStorageSizesRequest,
    ListDbSystemInitialStorageSizesResponse,
    StorageSizeDetails,
)
from .types.db_system_shape import DbSystemShape
from .types.db_version import (
    DbVersion,
    DbVersionProperties,
    ListDbVersionsRequest,
    ListDbVersionsResponse,
)
from .types.entitlement import CloudAccountDetails, Entitlement
from .types.exadata_infra import (
    CloudExadataInfrastructure,
    CloudExadataInfrastructureProperties,
    MaintenanceWindow,
)
from .types.exadb_vm_cluster import (
    ExadbVmCluster,
    ExadbVmClusterProperties,
    ExadbVmClusterStorageDetails,
)
from .types.exascale_db_storage_vault import (
    CreateExascaleDbStorageVaultRequest,
    DeleteExascaleDbStorageVaultRequest,
    ExascaleDbStorageDetails,
    ExascaleDbStorageVault,
    ExascaleDbStorageVaultProperties,
    GetExascaleDbStorageVaultRequest,
    ListExascaleDbStorageVaultsRequest,
    ListExascaleDbStorageVaultsResponse,
)
from .types.gi_version import GiVersion
from .types.location_metadata import LocationMetadata
from .types.minor_version import (
    ListMinorVersionsRequest,
    ListMinorVersionsResponse,
    MinorVersion,
)
from .types.odb_network import (
    CreateOdbNetworkRequest,
    DeleteOdbNetworkRequest,
    GetOdbNetworkRequest,
    ListOdbNetworksRequest,
    ListOdbNetworksResponse,
    OdbNetwork,
)
from .types.odb_subnet import (
    CreateOdbSubnetRequest,
    DeleteOdbSubnetRequest,
    GetOdbSubnetRequest,
    ListOdbSubnetsRequest,
    ListOdbSubnetsResponse,
    OdbSubnet,
)
from .types.oracledatabase import (
    CreateAutonomousDatabaseRequest,
    CreateCloudExadataInfrastructureRequest,
    CreateCloudVmClusterRequest,
    CreateExadbVmClusterRequest,
    DeleteAutonomousDatabaseRequest,
    DeleteCloudExadataInfrastructureRequest,
    DeleteCloudVmClusterRequest,
    DeleteExadbVmClusterRequest,
    FailoverAutonomousDatabaseRequest,
    GenerateAutonomousDatabaseWalletRequest,
    GenerateAutonomousDatabaseWalletResponse,
    GetAutonomousDatabaseRequest,
    GetCloudExadataInfrastructureRequest,
    GetCloudVmClusterRequest,
    GetExadbVmClusterRequest,
    ListAutonomousDatabaseBackupsRequest,
    ListAutonomousDatabaseBackupsResponse,
    ListAutonomousDatabaseCharacterSetsRequest,
    ListAutonomousDatabaseCharacterSetsResponse,
    ListAutonomousDatabasesRequest,
    ListAutonomousDatabasesResponse,
    ListAutonomousDbVersionsRequest,
    ListAutonomousDbVersionsResponse,
    ListCloudExadataInfrastructuresRequest,
    ListCloudExadataInfrastructuresResponse,
    ListCloudVmClustersRequest,
    ListCloudVmClustersResponse,
    ListDbNodesRequest,
    ListDbNodesResponse,
    ListDbServersRequest,
    ListDbServersResponse,
    ListDbSystemShapesRequest,
    ListDbSystemShapesResponse,
    ListEntitlementsRequest,
    ListEntitlementsResponse,
    ListExadbVmClustersRequest,
    ListExadbVmClustersResponse,
    ListGiVersionsRequest,
    ListGiVersionsResponse,
    OperationMetadata,
    RemoveVirtualMachineExadbVmClusterRequest,
    RestartAutonomousDatabaseRequest,
    RestoreAutonomousDatabaseRequest,
    StartAutonomousDatabaseRequest,
    StopAutonomousDatabaseRequest,
    SwitchoverAutonomousDatabaseRequest,
    UpdateAutonomousDatabaseRequest,
    UpdateExadbVmClusterRequest,
)
from .types.pluggable_database import (
    DatabaseManagementConfig,
    GetPluggableDatabaseRequest,
    ListPluggableDatabasesRequest,
    ListPluggableDatabasesResponse,
    PluggableDatabase,
    PluggableDatabaseConnectionStrings,
    PluggableDatabaseNodeLevelDetails,
    PluggableDatabaseProperties,
)
from .types.vm_cluster import (
    CloudVmCluster,
    CloudVmClusterProperties,
    DataCollectionOptions,
)

__all__ = (
    "OracleDatabaseAsyncClient",
    "AllConnectionStrings",
    "AutonomousDatabase",
    "AutonomousDatabaseApex",
    "AutonomousDatabaseBackup",
    "AutonomousDatabaseBackupProperties",
    "AutonomousDatabaseCharacterSet",
    "AutonomousDatabaseConnectionStrings",
    "AutonomousDatabaseConnectionUrls",
    "AutonomousDatabaseProperties",
    "AutonomousDatabaseStandbySummary",
    "AutonomousDbVersion",
    "CloudAccountDetails",
    "CloudExadataInfrastructure",
    "CloudExadataInfrastructureProperties",
    "CloudVmCluster",
    "CloudVmClusterProperties",
    "ComputeModel",
    "CreateAutonomousDatabaseRequest",
    "CreateCloudExadataInfrastructureRequest",
    "CreateCloudVmClusterRequest",
    "CreateDbSystemRequest",
    "CreateExadbVmClusterRequest",
    "CreateExascaleDbStorageVaultRequest",
    "CreateOdbNetworkRequest",
    "CreateOdbSubnetRequest",
    "CustomerContact",
    "DBWorkload",
    "DataCollectionOptions",
    "DataCollectionOptionsCommon",
    "DataCollectionOptionsDbSystem",
    "Database",
    "DatabaseCharacterSet",
    "DatabaseConnectionStringProfile",
    "DatabaseManagementConfig",
    "DatabaseProperties",
    "DbBackupConfig",
    "DbHome",
    "DbNode",
    "DbNodeProperties",
    "DbServer",
    "DbServerProperties",
    "DbSystem",
    "DbSystemInitialStorageSize",
    "DbSystemInitialStorageSizeProperties",
    "DbSystemOptions",
    "DbSystemProperties",
    "DbSystemShape",
    "DbVersion",
    "DbVersionProperties",
    "DeleteAutonomousDatabaseRequest",
    "DeleteCloudExadataInfrastructureRequest",
    "DeleteCloudVmClusterRequest",
    "DeleteDbSystemRequest",
    "DeleteExadbVmClusterRequest",
    "DeleteExascaleDbStorageVaultRequest",
    "DeleteOdbNetworkRequest",
    "DeleteOdbSubnetRequest",
    "EncryptionKey",
    "EncryptionKeyHistoryEntry",
    "Entitlement",
    "ExadbVmCluster",
    "ExadbVmClusterProperties",
    "ExadbVmClusterStorageDetails",
    "ExascaleDbStorageDetails",
    "ExascaleDbStorageVault",
    "ExascaleDbStorageVaultProperties",
    "FailoverAutonomousDatabaseRequest",
    "GenerateAutonomousDatabaseWalletRequest",
    "GenerateAutonomousDatabaseWalletResponse",
    "GenerateType",
    "GetAutonomousDatabaseRequest",
    "GetCloudExadataInfrastructureRequest",
    "GetCloudVmClusterRequest",
    "GetDatabaseRequest",
    "GetDbSystemRequest",
    "GetExadbVmClusterRequest",
    "GetExascaleDbStorageVaultRequest",
    "GetOdbNetworkRequest",
    "GetOdbSubnetRequest",
    "GetPluggableDatabaseRequest",
    "GiVersion",
    "IdentityConnector",
    "ListAutonomousDatabaseBackupsRequest",
    "ListAutonomousDatabaseBackupsResponse",
    "ListAutonomousDatabaseCharacterSetsRequest",
    "ListAutonomousDatabaseCharacterSetsResponse",
    "ListAutonomousDatabasesRequest",
    "ListAutonomousDatabasesResponse",
    "ListAutonomousDbVersionsRequest",
    "ListAutonomousDbVersionsResponse",
    "ListCloudExadataInfrastructuresRequest",
    "ListCloudExadataInfrastructuresResponse",
    "ListCloudVmClustersRequest",
    "ListCloudVmClustersResponse",
    "ListDatabaseCharacterSetsRequest",
    "ListDatabaseCharacterSetsResponse",
    "ListDatabasesRequest",
    "ListDatabasesResponse",
    "ListDbNodesRequest",
    "ListDbNodesResponse",
    "ListDbServersRequest",
    "ListDbServersResponse",
    "ListDbSystemInitialStorageSizesRequest",
    "ListDbSystemInitialStorageSizesResponse",
    "ListDbSystemShapesRequest",
    "ListDbSystemShapesResponse",
    "ListDbSystemsRequest",
    "ListDbSystemsResponse",
    "ListDbVersionsRequest",
    "ListDbVersionsResponse",
    "ListEntitlementsRequest",
    "ListEntitlementsResponse",
    "ListExadbVmClustersRequest",
    "ListExadbVmClustersResponse",
    "ListExascaleDbStorageVaultsRequest",
    "ListExascaleDbStorageVaultsResponse",
    "ListGiVersionsRequest",
    "ListGiVersionsResponse",
    "ListMinorVersionsRequest",
    "ListMinorVersionsResponse",
    "ListOdbNetworksRequest",
    "ListOdbNetworksResponse",
    "ListOdbSubnetsRequest",
    "ListOdbSubnetsResponse",
    "ListPluggableDatabasesRequest",
    "ListPluggableDatabasesResponse",
    "LocationMetadata",
    "MaintenanceWindow",
    "MinorVersion",
    "OdbNetwork",
    "OdbSubnet",
    "OperationMetadata",
    "OperationsInsightsState",
    "OracleDatabaseClient",
    "PluggableDatabase",
    "PluggableDatabaseConnectionStrings",
    "PluggableDatabaseNodeLevelDetails",
    "PluggableDatabaseProperties",
    "RemoveVirtualMachineExadbVmClusterRequest",
    "RestartAutonomousDatabaseRequest",
    "RestoreAutonomousDatabaseRequest",
    "ScheduledOperationDetails",
    "SourceConfig",
    "StartAutonomousDatabaseRequest",
    "State",
    "StopAutonomousDatabaseRequest",
    "StorageSizeDetails",
    "SwitchoverAutonomousDatabaseRequest",
    "UpdateAutonomousDatabaseRequest",
    "UpdateExadbVmClusterRequest",
)
