# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.network_services_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.network_services_v1.services.dep_service",
    "google.cloud.network_services_v1.services.network_services",
    "google.cloud.network_services_v1.types.agent_gateway",
    "google.cloud.network_services_v1.types.common",
    "google.cloud.network_services_v1.types.dep",
    "google.cloud.network_services_v1.types.endpoint_policy",
    "google.cloud.network_services_v1.types.extensibility",
    "google.cloud.network_services_v1.types.gateway",
    "google.cloud.network_services_v1.types.grpc_route",
    "google.cloud.network_services_v1.types.http_route",
    "google.cloud.network_services_v1.types.mesh",
    "google.cloud.network_services_v1.types.network_services",
    "google.cloud.network_services_v1.types.route_view",
    "google.cloud.network_services_v1.types.service_binding",
    "google.cloud.network_services_v1.types.service_lb_policy",
    "google.cloud.network_services_v1.types.tcp_route",
    "google.cloud.network_services_v1.types.tls_route",
}


from .services.dep_service import DepServiceAsyncClient, DepServiceClient
from .services.network_services import NetworkServicesAsyncClient, NetworkServicesClient
from .types.agent_gateway import (
    AgentGateway,
    CreateAgentGatewayRequest,
    DeleteAgentGatewayRequest,
    GetAgentGatewayRequest,
    ListAgentGatewaysRequest,
    ListAgentGatewaysResponse,
    UpdateAgentGatewayRequest,
)
from .types.common import (
    EndpointMatcher,
    EnvoyHeaders,
    OperationMetadata,
    TrafficPortSelector,
)
from .types.dep import (
    AuthzExtension,
    BodySendMode,
    CreateAuthzExtensionRequest,
    CreateLbEdgeExtensionRequest,
    CreateLbRouteExtensionRequest,
    CreateLbTrafficExtensionRequest,
    DeleteAuthzExtensionRequest,
    DeleteLbEdgeExtensionRequest,
    DeleteLbRouteExtensionRequest,
    DeleteLbTrafficExtensionRequest,
    EventType,
    ExtensionChain,
    GetAuthzExtensionRequest,
    GetLbEdgeExtensionRequest,
    GetLbRouteExtensionRequest,
    GetLbTrafficExtensionRequest,
    LbEdgeExtension,
    LbRouteExtension,
    LbTrafficExtension,
    ListAuthzExtensionsRequest,
    ListAuthzExtensionsResponse,
    ListLbEdgeExtensionsRequest,
    ListLbEdgeExtensionsResponse,
    ListLbRouteExtensionsRequest,
    ListLbRouteExtensionsResponse,
    ListLbTrafficExtensionsRequest,
    ListLbTrafficExtensionsResponse,
    LoadBalancingScheme,
    UpdateAuthzExtensionRequest,
    UpdateLbEdgeExtensionRequest,
    UpdateLbRouteExtensionRequest,
    UpdateLbTrafficExtensionRequest,
    WireFormat,
)
from .types.endpoint_policy import (
    CreateEndpointPolicyRequest,
    DeleteEndpointPolicyRequest,
    EndpointPolicy,
    GetEndpointPolicyRequest,
    ListEndpointPoliciesRequest,
    ListEndpointPoliciesResponse,
    UpdateEndpointPolicyRequest,
)
from .types.extensibility import (
    CreateWasmPluginRequest,
    CreateWasmPluginVersionRequest,
    DeleteWasmPluginRequest,
    DeleteWasmPluginVersionRequest,
    GetWasmPluginRequest,
    GetWasmPluginVersionRequest,
    ListWasmPluginsRequest,
    ListWasmPluginsResponse,
    ListWasmPluginVersionsRequest,
    ListWasmPluginVersionsResponse,
    UpdateWasmPluginRequest,
    WasmPlugin,
    WasmPluginVersion,
    WasmPluginView,
)
from .types.gateway import (
    CreateGatewayRequest,
    DeleteGatewayRequest,
    Gateway,
    GetGatewayRequest,
    ListGatewaysRequest,
    ListGatewaysResponse,
    UpdateGatewayRequest,
)
from .types.grpc_route import (
    CreateGrpcRouteRequest,
    DeleteGrpcRouteRequest,
    GetGrpcRouteRequest,
    GrpcRoute,
    ListGrpcRoutesRequest,
    ListGrpcRoutesResponse,
    UpdateGrpcRouteRequest,
)
from .types.http_route import (
    CreateHttpRouteRequest,
    DeleteHttpRouteRequest,
    GetHttpRouteRequest,
    HttpRoute,
    ListHttpRoutesRequest,
    ListHttpRoutesResponse,
    UpdateHttpRouteRequest,
)
from .types.mesh import (
    CreateMeshRequest,
    DeleteMeshRequest,
    GetMeshRequest,
    ListMeshesRequest,
    ListMeshesResponse,
    Mesh,
    UpdateMeshRequest,
)
from .types.route_view import (
    GatewayRouteView,
    GetGatewayRouteViewRequest,
    GetMeshRouteViewRequest,
    ListGatewayRouteViewsRequest,
    ListGatewayRouteViewsResponse,
    ListMeshRouteViewsRequest,
    ListMeshRouteViewsResponse,
    MeshRouteView,
)
from .types.service_binding import (
    CreateServiceBindingRequest,
    DeleteServiceBindingRequest,
    GetServiceBindingRequest,
    ListServiceBindingsRequest,
    ListServiceBindingsResponse,
    ServiceBinding,
    UpdateServiceBindingRequest,
)
from .types.service_lb_policy import (
    CreateServiceLbPolicyRequest,
    DeleteServiceLbPolicyRequest,
    GetServiceLbPolicyRequest,
    ListServiceLbPoliciesRequest,
    ListServiceLbPoliciesResponse,
    ServiceLbPolicy,
    UpdateServiceLbPolicyRequest,
)
from .types.tcp_route import (
    CreateTcpRouteRequest,
    DeleteTcpRouteRequest,
    GetTcpRouteRequest,
    ListTcpRoutesRequest,
    ListTcpRoutesResponse,
    TcpRoute,
    UpdateTcpRouteRequest,
)
from .types.tls_route import (
    CreateTlsRouteRequest,
    DeleteTlsRouteRequest,
    GetTlsRouteRequest,
    ListTlsRoutesRequest,
    ListTlsRoutesResponse,
    TlsRoute,
    UpdateTlsRouteRequest,
)

__all__ = (
    "DepServiceAsyncClient",
    "NetworkServicesAsyncClient",
    "AgentGateway",
    "AuthzExtension",
    "BodySendMode",
    "CreateAgentGatewayRequest",
    "CreateAuthzExtensionRequest",
    "CreateEndpointPolicyRequest",
    "CreateGatewayRequest",
    "CreateGrpcRouteRequest",
    "CreateHttpRouteRequest",
    "CreateLbEdgeExtensionRequest",
    "CreateLbRouteExtensionRequest",
    "CreateLbTrafficExtensionRequest",
    "CreateMeshRequest",
    "CreateServiceBindingRequest",
    "CreateServiceLbPolicyRequest",
    "CreateTcpRouteRequest",
    "CreateTlsRouteRequest",
    "CreateWasmPluginRequest",
    "CreateWasmPluginVersionRequest",
    "DeleteAgentGatewayRequest",
    "DeleteAuthzExtensionRequest",
    "DeleteEndpointPolicyRequest",
    "DeleteGatewayRequest",
    "DeleteGrpcRouteRequest",
    "DeleteHttpRouteRequest",
    "DeleteLbEdgeExtensionRequest",
    "DeleteLbRouteExtensionRequest",
    "DeleteLbTrafficExtensionRequest",
    "DeleteMeshRequest",
    "DeleteServiceBindingRequest",
    "DeleteServiceLbPolicyRequest",
    "DeleteTcpRouteRequest",
    "DeleteTlsRouteRequest",
    "DeleteWasmPluginRequest",
    "DeleteWasmPluginVersionRequest",
    "DepServiceClient",
    "EndpointMatcher",
    "EndpointPolicy",
    "EnvoyHeaders",
    "EventType",
    "ExtensionChain",
    "Gateway",
    "GatewayRouteView",
    "GetAgentGatewayRequest",
    "GetAuthzExtensionRequest",
    "GetEndpointPolicyRequest",
    "GetGatewayRequest",
    "GetGatewayRouteViewRequest",
    "GetGrpcRouteRequest",
    "GetHttpRouteRequest",
    "GetLbEdgeExtensionRequest",
    "GetLbRouteExtensionRequest",
    "GetLbTrafficExtensionRequest",
    "GetMeshRequest",
    "GetMeshRouteViewRequest",
    "GetServiceBindingRequest",
    "GetServiceLbPolicyRequest",
    "GetTcpRouteRequest",
    "GetTlsRouteRequest",
    "GetWasmPluginRequest",
    "GetWasmPluginVersionRequest",
    "GrpcRoute",
    "HttpRoute",
    "LbEdgeExtension",
    "LbRouteExtension",
    "LbTrafficExtension",
    "ListAgentGatewaysRequest",
    "ListAgentGatewaysResponse",
    "ListAuthzExtensionsRequest",
    "ListAuthzExtensionsResponse",
    "ListEndpointPoliciesRequest",
    "ListEndpointPoliciesResponse",
    "ListGatewayRouteViewsRequest",
    "ListGatewayRouteViewsResponse",
    "ListGatewaysRequest",
    "ListGatewaysResponse",
    "ListGrpcRoutesRequest",
    "ListGrpcRoutesResponse",
    "ListHttpRoutesRequest",
    "ListHttpRoutesResponse",
    "ListLbEdgeExtensionsRequest",
    "ListLbEdgeExtensionsResponse",
    "ListLbRouteExtensionsRequest",
    "ListLbRouteExtensionsResponse",
    "ListLbTrafficExtensionsRequest",
    "ListLbTrafficExtensionsResponse",
    "ListMeshRouteViewsRequest",
    "ListMeshRouteViewsResponse",
    "ListMeshesRequest",
    "ListMeshesResponse",
    "ListServiceBindingsRequest",
    "ListServiceBindingsResponse",
    "ListServiceLbPoliciesRequest",
    "ListServiceLbPoliciesResponse",
    "ListTcpRoutesRequest",
    "ListTcpRoutesResponse",
    "ListTlsRoutesRequest",
    "ListTlsRoutesResponse",
    "ListWasmPluginVersionsRequest",
    "ListWasmPluginVersionsResponse",
    "ListWasmPluginsRequest",
    "ListWasmPluginsResponse",
    "LoadBalancingScheme",
    "Mesh",
    "MeshRouteView",
    "NetworkServicesClient",
    "OperationMetadata",
    "ServiceBinding",
    "ServiceLbPolicy",
    "TcpRoute",
    "TlsRoute",
    "TrafficPortSelector",
    "UpdateAgentGatewayRequest",
    "UpdateAuthzExtensionRequest",
    "UpdateEndpointPolicyRequest",
    "UpdateGatewayRequest",
    "UpdateGrpcRouteRequest",
    "UpdateHttpRouteRequest",
    "UpdateLbEdgeExtensionRequest",
    "UpdateLbRouteExtensionRequest",
    "UpdateLbTrafficExtensionRequest",
    "UpdateMeshRequest",
    "UpdateServiceBindingRequest",
    "UpdateServiceLbPolicyRequest",
    "UpdateTcpRouteRequest",
    "UpdateTlsRouteRequest",
    "UpdateWasmPluginRequest",
    "WasmPlugin",
    "WasmPluginVersion",
    "WasmPluginView",
    "WireFormat",
)

api_core.check_python_version("google.cloud.network_services_v1")
api_core.check_dependency_versions("google.cloud.network_services_v1")
