# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DO NOT MODIFY THIS FILE DIRECTLY.
# This file was generated by the script: scripts/generate_bigframes_bigquery.py
#

from __future__ import annotations

from typing import Optional, TypeVar, cast

from bigframes import dataframe, series, session
from bigframes.core.logging import log_adapter
from bigframes.extensions.core import series_accessor as core_accessor

T = TypeVar("T", bound="dataframe.DataFrame")
S = TypeVar("S", bound="series.Series")


@log_adapter.class_logger
class BigframesBigQuerySeriesAccessor(core_accessor.BigQuerySeriesAccessor[T, S]):
    def __init__(self, bf_obj: S):
        super().__init__(bf_obj)

    def _bf_from_series(
        self, session: Optional[session.Session] = None
    ) -> series.Series:
        return self._obj

    def _to_dataframe(self, bf_df: dataframe.DataFrame) -> T:
        return cast(T, bf_df)

    def _to_series(self, bf_series: series.Series) -> S:
        return cast(S, bf_series)

    @property
    def ai(self) -> BigframesAiSeriesAccessor[T, S]:
        return BigframesAiSeriesAccessor(self._obj)

    @property
    def aead(self) -> BigframesAeadSeriesAccessor[T, S]:
        return BigframesAeadSeriesAccessor(self._obj)


@log_adapter.class_logger
class BigframesAiSeriesAccessor(core_accessor.AiSeriesAccessor[T, S]):
    def __init__(self, bf_obj: S):
        super().__init__(bf_obj)

    def _bf_from_series(
        self, session: Optional[session.Session] = None
    ) -> series.Series:
        return self._obj

    def _to_dataframe(self, bf_df: dataframe.DataFrame) -> T:
        return cast(T, bf_df)

    def _to_series(self, bf_series: series.Series) -> S:
        return cast(S, bf_series)


@log_adapter.class_logger
class BigframesAeadSeriesAccessor(core_accessor.AeadSeriesAccessor[T, S]):
    def __init__(self, bf_obj: S):
        super().__init__(bf_obj)

    def _bf_from_series(
        self, session: Optional[session.Session] = None
    ) -> series.Series:
        return self._obj

    def _to_dataframe(self, bf_df: dataframe.DataFrame) -> T:
        return cast(T, bf_df)

    def _to_series(self, bf_series: series.Series) -> S:
        return cast(S, bf_series)
