# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.analytics.data_v1alpha import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.analytics.data_v1alpha.services.alpha_analytics_data",
    "google.analytics.data_v1alpha.types.analytics_data_api",
    "google.analytics.data_v1alpha.types.data",
}


from .services.alpha_analytics_data import (
    AlphaAnalyticsDataAsyncClient,
    AlphaAnalyticsDataClient,
)
from .types.analytics_data_api import (
    AudienceDimension,
    AudienceDimensionValue,
    AudienceList,
    AudienceListMetadata,
    AudienceRow,
    CreateAudienceListRequest,
    CreateRecurringAudienceListRequest,
    CreateReportTaskRequest,
    GetAudienceListRequest,
    GetMetadataRequest,
    GetPropertyQuotasSnapshotRequest,
    GetRecurringAudienceListRequest,
    GetReportTaskRequest,
    ListAudienceListsRequest,
    ListAudienceListsResponse,
    ListRecurringAudienceListsRequest,
    ListRecurringAudienceListsResponse,
    ListReportTasksRequest,
    ListReportTasksResponse,
    Metadata,
    PropertyQuotasSnapshot,
    QueryAudienceListRequest,
    QueryAudienceListResponse,
    QueryReportTaskRequest,
    QueryReportTaskResponse,
    RecurringAudienceList,
    ReportTask,
    ReportTaskMetadata,
    RunFunnelReportRequest,
    RunFunnelReportResponse,
    RunReportRequest,
    RunReportResponse,
    WebhookNotification,
)
from .types.data import (
    BetweenFilter,
    Cohort,
    CohortReportSettings,
    CohortSpec,
    CohortsRange,
    Comparison,
    ComparisonMetadata,
    ConversionMetadata,
    ConversionSpec,
    DateRange,
    Dimension,
    DimensionExpression,
    DimensionHeader,
    DimensionMetadata,
    DimensionValue,
    EmptyFilter,
    EventCriteriaScoping,
    EventExclusionDuration,
    EventSegment,
    EventSegmentConditionGroup,
    EventSegmentCriteria,
    EventSegmentExclusion,
    Filter,
    FilterExpression,
    FilterExpressionList,
    Funnel,
    FunnelBreakdown,
    FunnelEventFilter,
    FunnelFieldFilter,
    FunnelFilterExpression,
    FunnelFilterExpressionList,
    FunnelNextAction,
    FunnelParameterFilter,
    FunnelParameterFilterExpression,
    FunnelParameterFilterExpressionList,
    FunnelResponseMetadata,
    FunnelStep,
    FunnelSubReport,
    InListFilter,
    Metric,
    MetricAggregation,
    MetricHeader,
    MetricMetadata,
    MetricType,
    MetricValue,
    NumericFilter,
    NumericValue,
    OrderBy,
    PropertyQuota,
    QuotaStatus,
    ResponseMetaData,
    RestrictedMetricType,
    Row,
    SamplingLevel,
    SamplingMetadata,
    Section,
    Segment,
    SegmentEventFilter,
    SegmentFilter,
    SegmentFilterExpression,
    SegmentFilterExpressionList,
    SegmentFilterScoping,
    SegmentParameterFilter,
    SegmentParameterFilterExpression,
    SegmentParameterFilterExpressionList,
    SegmentParameterFilterScoping,
    SessionCriteriaScoping,
    SessionExclusionDuration,
    SessionSegment,
    SessionSegmentConditionGroup,
    SessionSegmentCriteria,
    SessionSegmentExclusion,
    StringFilter,
    UserCriteriaScoping,
    UserExclusionDuration,
    UserSegment,
    UserSegmentConditionGroup,
    UserSegmentCriteria,
    UserSegmentExclusion,
    UserSegmentSequenceGroup,
    UserSequenceStep,
)

__all__ = (
    "AlphaAnalyticsDataAsyncClient",
    "AlphaAnalyticsDataClient",
    "AudienceDimension",
    "AudienceDimensionValue",
    "AudienceList",
    "AudienceListMetadata",
    "AudienceRow",
    "BetweenFilter",
    "Cohort",
    "CohortReportSettings",
    "CohortSpec",
    "CohortsRange",
    "Comparison",
    "ComparisonMetadata",
    "ConversionMetadata",
    "ConversionSpec",
    "CreateAudienceListRequest",
    "CreateRecurringAudienceListRequest",
    "CreateReportTaskRequest",
    "DateRange",
    "Dimension",
    "DimensionExpression",
    "DimensionHeader",
    "DimensionMetadata",
    "DimensionValue",
    "EmptyFilter",
    "EventCriteriaScoping",
    "EventExclusionDuration",
    "EventSegment",
    "EventSegmentConditionGroup",
    "EventSegmentCriteria",
    "EventSegmentExclusion",
    "Filter",
    "FilterExpression",
    "FilterExpressionList",
    "Funnel",
    "FunnelBreakdown",
    "FunnelEventFilter",
    "FunnelFieldFilter",
    "FunnelFilterExpression",
    "FunnelFilterExpressionList",
    "FunnelNextAction",
    "FunnelParameterFilter",
    "FunnelParameterFilterExpression",
    "FunnelParameterFilterExpressionList",
    "FunnelResponseMetadata",
    "FunnelStep",
    "FunnelSubReport",
    "GetAudienceListRequest",
    "GetMetadataRequest",
    "GetPropertyQuotasSnapshotRequest",
    "GetRecurringAudienceListRequest",
    "GetReportTaskRequest",
    "InListFilter",
    "ListAudienceListsRequest",
    "ListAudienceListsResponse",
    "ListRecurringAudienceListsRequest",
    "ListRecurringAudienceListsResponse",
    "ListReportTasksRequest",
    "ListReportTasksResponse",
    "Metadata",
    "Metric",
    "MetricAggregation",
    "MetricHeader",
    "MetricMetadata",
    "MetricType",
    "MetricValue",
    "NumericFilter",
    "NumericValue",
    "OrderBy",
    "PropertyQuota",
    "PropertyQuotasSnapshot",
    "QueryAudienceListRequest",
    "QueryAudienceListResponse",
    "QueryReportTaskRequest",
    "QueryReportTaskResponse",
    "QuotaStatus",
    "RecurringAudienceList",
    "ReportTask",
    "ReportTaskMetadata",
    "ResponseMetaData",
    "RestrictedMetricType",
    "Row",
    "RunFunnelReportRequest",
    "RunFunnelReportResponse",
    "RunReportRequest",
    "RunReportResponse",
    "SamplingLevel",
    "SamplingMetadata",
    "Section",
    "Segment",
    "SegmentEventFilter",
    "SegmentFilter",
    "SegmentFilterExpression",
    "SegmentFilterExpressionList",
    "SegmentFilterScoping",
    "SegmentParameterFilter",
    "SegmentParameterFilterExpression",
    "SegmentParameterFilterExpressionList",
    "SegmentParameterFilterScoping",
    "SessionCriteriaScoping",
    "SessionExclusionDuration",
    "SessionSegment",
    "SessionSegmentConditionGroup",
    "SessionSegmentCriteria",
    "SessionSegmentExclusion",
    "StringFilter",
    "UserCriteriaScoping",
    "UserExclusionDuration",
    "UserSegment",
    "UserSegmentConditionGroup",
    "UserSegmentCriteria",
    "UserSegmentExclusion",
    "UserSegmentSequenceGroup",
    "UserSequenceStep",
    "WebhookNotification",
)

api_core.check_python_version("google.analytics.data_v1alpha")
api_core.check_dependency_versions("google.analytics.data_v1alpha")
