version: 2
jobs:
  # Pip
  "pip-3.5":
    docker:
      - image: thekevjames/nox
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: nox -s unit-3.5 system-3.5

  "pip-3.6":
    docker:
      - image: thekevjames/nox
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: nox -s unit-3.6 system-3.6

  "pip-3.7":
    docker:
      - image: thekevjames/nox
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: nox -s unit-3.7 system-3.7 cover

  "lint":
    docker:
      - image: thekevjames/nox
    environment:
      # Resolve "Python 3 was configured to use ASCII as encoding for the environment"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - checkout
      - run: nox -s lint

  # Conda
  "conda-3.6-0.20.1":
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON: "3.6"
      PANDAS: "0.20.1"
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: ci/run_conda.sh

workflows:
  version: 2
  build:
    jobs:
      - "pip-3.5"
      - "pip-3.6"
      - "pip-3.7"
      - lint
      - "conda-3.6-0.20.1"