version: 2
jobs:
  "lint":
    docker:
      - image: thekevjames/nox
    environment:
      # Resolve "Python 3 was configured to use ASCII as encoding for the environment"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - checkout
      - run: nox -s lint
  "docs-presubmit":
    docker:
      - image: thekevjames/nox
    environment:
      # Resolve "Python 3 was configured to use ASCII as encoding for the environment"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - checkout
      - run: nox -s docs

  # Pip
  "pip-3.7":
    docker:
      - image: thekevjames/nox
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: nox -s unit-3.7
  "pip-3.8":
    docker:
      - image: thekevjames/nox
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: nox -s unit-3.8 system-3.8 cover

  # Conda
  "conda-3.7":
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON: "3.7"
      PANDAS: "0.23.2"
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: ci/run_conda.sh
  "conda-3.9-NIGHTLY":
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON: "3.9"
      PANDAS: "NIGHTLY"
    steps:
      - checkout
      - run: ci/config_auth.sh
      - run: ci/run_conda.sh

workflows:
  version: 2
  build:
    jobs:
      - lint
      - docs-presubmit
      - "pip-3.7"
      - "pip-3.8"
      - "conda-3.7"
      - "conda-3.9-NIGHTLY"