# -*- coding: utf-8 -*-
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.apihub import gapic_version as package_version

__version__ = package_version.__version__


from google.cloud.apihub_v1.services.api_hub.async_client import ApiHubAsyncClient
from google.cloud.apihub_v1.services.api_hub.client import ApiHubClient
from google.cloud.apihub_v1.services.api_hub_collect.async_client import (
    ApiHubCollectAsyncClient,
)
from google.cloud.apihub_v1.services.api_hub_collect.client import ApiHubCollectClient
from google.cloud.apihub_v1.services.api_hub_curate.async_client import (
    ApiHubCurateAsyncClient,
)
from google.cloud.apihub_v1.services.api_hub_curate.client import ApiHubCurateClient
from google.cloud.apihub_v1.services.api_hub_dependencies.async_client import (
    ApiHubDependenciesAsyncClient,
)
from google.cloud.apihub_v1.services.api_hub_dependencies.client import (
    ApiHubDependenciesClient,
)
from google.cloud.apihub_v1.services.api_hub_discovery.async_client import (
    ApiHubDiscoveryAsyncClient,
)
from google.cloud.apihub_v1.services.api_hub_discovery.client import (
    ApiHubDiscoveryClient,
)
from google.cloud.apihub_v1.services.api_hub_plugin.async_client import (
    ApiHubPluginAsyncClient,
)
from google.cloud.apihub_v1.services.api_hub_plugin.client import ApiHubPluginClient
from google.cloud.apihub_v1.services.host_project_registration_service.async_client import (
    HostProjectRegistrationServiceAsyncClient,
)
from google.cloud.apihub_v1.services.host_project_registration_service.client import (
    HostProjectRegistrationServiceClient,
)
from google.cloud.apihub_v1.services.linting_service.async_client import (
    LintingServiceAsyncClient,
)
from google.cloud.apihub_v1.services.linting_service.client import LintingServiceClient
from google.cloud.apihub_v1.services.provisioning.async_client import (
    ProvisioningAsyncClient,
)
from google.cloud.apihub_v1.services.provisioning.client import ProvisioningClient
from google.cloud.apihub_v1.services.runtime_project_attachment_service.async_client import (
    RuntimeProjectAttachmentServiceAsyncClient,
)
from google.cloud.apihub_v1.services.runtime_project_attachment_service.client import (
    RuntimeProjectAttachmentServiceClient,
)
from google.cloud.apihub_v1.types.apihub_service import (
    ApiHubResource,
    CreateApiOperationRequest,
    CreateApiRequest,
    CreateAttributeRequest,
    CreateDependencyRequest,
    CreateDeploymentRequest,
    CreateExternalApiRequest,
    CreateSpecRequest,
    CreateVersionRequest,
    DeleteApiOperationRequest,
    DeleteApiRequest,
    DeleteAttributeRequest,
    DeleteDependencyRequest,
    DeleteDeploymentRequest,
    DeleteExternalApiRequest,
    DeleteSpecRequest,
    DeleteVersionRequest,
    GetApiOperationRequest,
    GetApiRequest,
    GetAttributeRequest,
    GetDefinitionRequest,
    GetDependencyRequest,
    GetDeploymentRequest,
    GetExternalApiRequest,
    GetSpecContentsRequest,
    GetSpecRequest,
    GetVersionRequest,
    ListApiOperationsRequest,
    ListApiOperationsResponse,
    ListApisRequest,
    ListApisResponse,
    ListAttributesRequest,
    ListAttributesResponse,
    ListDependenciesRequest,
    ListDependenciesResponse,
    ListDeploymentsRequest,
    ListDeploymentsResponse,
    ListExternalApisRequest,
    ListExternalApisResponse,
    ListSpecsRequest,
    ListSpecsResponse,
    ListVersionsRequest,
    ListVersionsResponse,
    SearchResourcesRequest,
    SearchResourcesResponse,
    SearchResult,
    UpdateApiOperationRequest,
    UpdateApiRequest,
    UpdateAttributeRequest,
    UpdateDependencyRequest,
    UpdateDeploymentRequest,
    UpdateExternalApiRequest,
    UpdateSpecRequest,
    UpdateVersionRequest,
)
from google.cloud.apihub_v1.types.collect_service import (
    ApiData,
    APIMetadata,
    ApiMetadataList,
    CollectApiDataRequest,
    CollectApiDataResponse,
    CollectionType,
    DeploymentMetadata,
    SpecMetadata,
    VersionMetadata,
)
from google.cloud.apihub_v1.types.common_fields import (
    Api,
    ApiHubInstance,
    ApiOperation,
    Attribute,
    AttributeValues,
    AuthConfig,
    AuthType,
    ConfigValueOption,
    ConfigVariable,
    ConfigVariableTemplate,
    Definition,
    Dependency,
    DependencyEntityReference,
    DependencyErrorDetail,
    Deployment,
    DiscoveredApiObservation,
    DiscoveredApiOperation,
    Documentation,
    ExternalApi,
    GoogleServiceAccountConfig,
    HttpOperation,
    HttpOperationDetails,
    Issue,
    Linter,
    LintResponse,
    LintState,
    OpenApiSpecDetails,
    OperationDetails,
    OperationMetadata,
    Owner,
    Path,
    PluginCategory,
    Point,
    Range,
    Schema,
    Secret,
    Severity,
    SourceMetadata,
    Spec,
    SpecContents,
    SpecDetails,
    Version,
)
from google.cloud.apihub_v1.types.curate_service import (
    ApplicationIntegrationEndpointDetails,
    CreateCurationRequest,
    Curation,
    DeleteCurationRequest,
    Endpoint,
    GetCurationRequest,
    ListCurationsRequest,
    ListCurationsResponse,
    UpdateCurationRequest,
)
from google.cloud.apihub_v1.types.discovery_service import (
    GetDiscoveredApiObservationRequest,
    GetDiscoveredApiOperationRequest,
    ListDiscoveredApiObservationsRequest,
    ListDiscoveredApiObservationsResponse,
    ListDiscoveredApiOperationsRequest,
    ListDiscoveredApiOperationsResponse,
)
from google.cloud.apihub_v1.types.host_project_registration_service import (
    CreateHostProjectRegistrationRequest,
    GetHostProjectRegistrationRequest,
    HostProjectRegistration,
    ListHostProjectRegistrationsRequest,
    ListHostProjectRegistrationsResponse,
)
from google.cloud.apihub_v1.types.linting_service import (
    GetStyleGuideContentsRequest,
    GetStyleGuideRequest,
    LintSpecRequest,
    StyleGuide,
    StyleGuideContents,
    UpdateStyleGuideRequest,
)
from google.cloud.apihub_v1.types.plugin_service import (
    ActionExecutionDetail,
    ActionType,
    CreatePluginInstanceRequest,
    CreatePluginRequest,
    CurationConfig,
    CurationType,
    DeletePluginInstanceRequest,
    DeletePluginRequest,
    DisablePluginInstanceActionRequest,
    DisablePluginInstanceActionResponse,
    DisablePluginRequest,
    EnablePluginInstanceActionRequest,
    EnablePluginInstanceActionResponse,
    EnablePluginRequest,
    ExecutePluginInstanceActionRequest,
    ExecutePluginInstanceActionResponse,
    ExecutionStatus,
    GatewayType,
    GetPluginInstanceRequest,
    GetPluginRequest,
    ListPluginInstancesRequest,
    ListPluginInstancesResponse,
    ListPluginsRequest,
    ListPluginsResponse,
    Plugin,
    PluginActionConfig,
    PluginInstance,
    PluginInstanceAction,
    UpdatePluginInstanceRequest,
)
from google.cloud.apihub_v1.types.provisioning_service import (
    CreateApiHubInstanceRequest,
    DeleteApiHubInstanceRequest,
    GetApiHubInstanceRequest,
    LookupApiHubInstanceRequest,
    LookupApiHubInstanceResponse,
)
from google.cloud.apihub_v1.types.runtime_project_attachment_service import (
    CreateRuntimeProjectAttachmentRequest,
    DeleteRuntimeProjectAttachmentRequest,
    GetRuntimeProjectAttachmentRequest,
    ListRuntimeProjectAttachmentsRequest,
    ListRuntimeProjectAttachmentsResponse,
    LookupRuntimeProjectAttachmentRequest,
    LookupRuntimeProjectAttachmentResponse,
    RuntimeProjectAttachment,
)

__all__ = (
    "ApiHubClient",
    "ApiHubAsyncClient",
    "ApiHubCollectClient",
    "ApiHubCollectAsyncClient",
    "ApiHubCurateClient",
    "ApiHubCurateAsyncClient",
    "ApiHubDependenciesClient",
    "ApiHubDependenciesAsyncClient",
    "ApiHubDiscoveryClient",
    "ApiHubDiscoveryAsyncClient",
    "ApiHubPluginClient",
    "ApiHubPluginAsyncClient",
    "HostProjectRegistrationServiceClient",
    "HostProjectRegistrationServiceAsyncClient",
    "LintingServiceClient",
    "LintingServiceAsyncClient",
    "ProvisioningClient",
    "ProvisioningAsyncClient",
    "RuntimeProjectAttachmentServiceClient",
    "RuntimeProjectAttachmentServiceAsyncClient",
    "ApiHubResource",
    "CreateApiOperationRequest",
    "CreateApiRequest",
    "CreateAttributeRequest",
    "CreateDependencyRequest",
    "CreateDeploymentRequest",
    "CreateExternalApiRequest",
    "CreateSpecRequest",
    "CreateVersionRequest",
    "DeleteApiOperationRequest",
    "DeleteApiRequest",
    "DeleteAttributeRequest",
    "DeleteDependencyRequest",
    "DeleteDeploymentRequest",
    "DeleteExternalApiRequest",
    "DeleteSpecRequest",
    "DeleteVersionRequest",
    "GetApiOperationRequest",
    "GetApiRequest",
    "GetAttributeRequest",
    "GetDefinitionRequest",
    "GetDependencyRequest",
    "GetDeploymentRequest",
    "GetExternalApiRequest",
    "GetSpecContentsRequest",
    "GetSpecRequest",
    "GetVersionRequest",
    "ListApiOperationsRequest",
    "ListApiOperationsResponse",
    "ListApisRequest",
    "ListApisResponse",
    "ListAttributesRequest",
    "ListAttributesResponse",
    "ListDependenciesRequest",
    "ListDependenciesResponse",
    "ListDeploymentsRequest",
    "ListDeploymentsResponse",
    "ListExternalApisRequest",
    "ListExternalApisResponse",
    "ListSpecsRequest",
    "ListSpecsResponse",
    "ListVersionsRequest",
    "ListVersionsResponse",
    "SearchResourcesRequest",
    "SearchResourcesResponse",
    "SearchResult",
    "UpdateApiOperationRequest",
    "UpdateApiRequest",
    "UpdateAttributeRequest",
    "UpdateDependencyRequest",
    "UpdateDeploymentRequest",
    "UpdateExternalApiRequest",
    "UpdateSpecRequest",
    "UpdateVersionRequest",
    "ApiData",
    "APIMetadata",
    "ApiMetadataList",
    "CollectApiDataRequest",
    "CollectApiDataResponse",
    "DeploymentMetadata",
    "SpecMetadata",
    "VersionMetadata",
    "CollectionType",
    "Api",
    "ApiHubInstance",
    "ApiOperation",
    "Attribute",
    "AttributeValues",
    "AuthConfig",
    "ConfigValueOption",
    "ConfigVariable",
    "ConfigVariableTemplate",
    "Definition",
    "Dependency",
    "DependencyEntityReference",
    "DependencyErrorDetail",
    "Deployment",
    "DiscoveredApiObservation",
    "DiscoveredApiOperation",
    "Documentation",
    "ExternalApi",
    "GoogleServiceAccountConfig",
    "HttpOperation",
    "HttpOperationDetails",
    "Issue",
    "LintResponse",
    "OpenApiSpecDetails",
    "OperationDetails",
    "OperationMetadata",
    "Owner",
    "Path",
    "Point",
    "Range",
    "Schema",
    "Secret",
    "SourceMetadata",
    "Spec",
    "SpecContents",
    "SpecDetails",
    "Version",
    "AuthType",
    "Linter",
    "LintState",
    "PluginCategory",
    "Severity",
    "ApplicationIntegrationEndpointDetails",
    "CreateCurationRequest",
    "Curation",
    "DeleteCurationRequest",
    "Endpoint",
    "GetCurationRequest",
    "ListCurationsRequest",
    "ListCurationsResponse",
    "UpdateCurationRequest",
    "GetDiscoveredApiObservationRequest",
    "GetDiscoveredApiOperationRequest",
    "ListDiscoveredApiObservationsRequest",
    "ListDiscoveredApiObservationsResponse",
    "ListDiscoveredApiOperationsRequest",
    "ListDiscoveredApiOperationsResponse",
    "CreateHostProjectRegistrationRequest",
    "GetHostProjectRegistrationRequest",
    "HostProjectRegistration",
    "ListHostProjectRegistrationsRequest",
    "ListHostProjectRegistrationsResponse",
    "GetStyleGuideContentsRequest",
    "GetStyleGuideRequest",
    "LintSpecRequest",
    "StyleGuide",
    "StyleGuideContents",
    "UpdateStyleGuideRequest",
    "ActionExecutionDetail",
    "CreatePluginInstanceRequest",
    "CreatePluginRequest",
    "CurationConfig",
    "DeletePluginInstanceRequest",
    "DeletePluginRequest",
    "DisablePluginInstanceActionRequest",
    "DisablePluginInstanceActionResponse",
    "DisablePluginRequest",
    "EnablePluginInstanceActionRequest",
    "EnablePluginInstanceActionResponse",
    "EnablePluginRequest",
    "ExecutePluginInstanceActionRequest",
    "ExecutePluginInstanceActionResponse",
    "ExecutionStatus",
    "GetPluginInstanceRequest",
    "GetPluginRequest",
    "ListPluginInstancesRequest",
    "ListPluginInstancesResponse",
    "ListPluginsRequest",
    "ListPluginsResponse",
    "Plugin",
    "PluginActionConfig",
    "PluginInstance",
    "PluginInstanceAction",
    "UpdatePluginInstanceRequest",
    "ActionType",
    "CurationType",
    "GatewayType",
    "CreateApiHubInstanceRequest",
    "DeleteApiHubInstanceRequest",
    "GetApiHubInstanceRequest",
    "LookupApiHubInstanceRequest",
    "LookupApiHubInstanceResponse",
    "CreateRuntimeProjectAttachmentRequest",
    "DeleteRuntimeProjectAttachmentRequest",
    "GetRuntimeProjectAttachmentRequest",
    "ListRuntimeProjectAttachmentsRequest",
    "ListRuntimeProjectAttachmentsResponse",
    "LookupRuntimeProjectAttachmentRequest",
    "LookupRuntimeProjectAttachmentResponse",
    "RuntimeProjectAttachment",
)
