[mypy]
python_version = 3.14
namespace_packages = True
ignore_missing_imports = False

# Helps mypy navigate the 'google' namespace more reliably in 3.10+
explicit_package_bases = True

# Performance: reuse results from previous runs to speed up 'nox'
incremental = True

# Optional dependency for GIS/spatial support. Lacks type hints.
[mypy-geoalchemy2.*]
ignore_missing_imports = True

# Optional dependency used by geoalchemy2. Lacks type hints.
[mypy-shapely.*]
ignore_missing_imports = True

# Optional dependency for database migrations. Lacks type hints.
[mypy-alembic.*]
ignore_missing_imports = True

# Obsolete package checked in __init__.py only to warn users that it is not supported
# and that they should use sqlalchemy-bigquery instead. Not installed.
[mypy-pybigquery.*]
ignore_missing_imports = True

# TODO(https://github.com/googleapis/gapic-generator-python/issues/2563):
# Dependencies that historically lacks py.typed markers
[mypy-google.iam.*]
ignore_missing_imports = True
