# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.gkehub_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.gkehub_v1.services.gke_hub",
    "google.cloud.gkehub_v1.types.feature",
    "google.cloud.gkehub_v1.types.fleet",
    "google.cloud.gkehub_v1.types.membership",
    "google.cloud.gkehub_v1.types.service",
}


from .services.gke_hub import GkeHubAsyncClient, GkeHubClient
from .types.feature import (
    CommonFeatureSpec,
    CommonFeatureState,
    Feature,
    FeatureResourceState,
    FeatureState,
    MembershipFeatureSpec,
    MembershipFeatureState,
    ScopeFeatureSpec,
    ScopeFeatureState,
)
from .types.fleet import (
    BinaryAuthorizationConfig,
    CompliancePostureConfig,
    DefaultClusterConfig,
    Fleet,
    FleetLifecycleState,
    MembershipBinding,
    MembershipBindingLifecycleState,
    Namespace,
    NamespaceLifecycleState,
    RBACRoleBinding,
    RBACRoleBindingLifecycleState,
    Scope,
    ScopeLifecycleState,
    SecurityPostureConfig,
)
from .types.membership import (
    Authority,
    GkeCluster,
    KubernetesMetadata,
    KubernetesResource,
    Membership,
    MembershipEndpoint,
    MembershipState,
    MonitoringConfig,
    ResourceManifest,
    ResourceOptions,
)
from .types.service import (
    ConnectAgentResource,
    CreateFeatureRequest,
    CreateFleetRequest,
    CreateMembershipBindingRequest,
    CreateMembershipRBACRoleBindingRequest,
    CreateMembershipRequest,
    CreateScopeNamespaceRequest,
    CreateScopeRBACRoleBindingRequest,
    CreateScopeRequest,
    DeleteFeatureRequest,
    DeleteFleetRequest,
    DeleteMembershipBindingRequest,
    DeleteMembershipRBACRoleBindingRequest,
    DeleteMembershipRequest,
    DeleteScopeNamespaceRequest,
    DeleteScopeRBACRoleBindingRequest,
    DeleteScopeRequest,
    GenerateConnectManifestRequest,
    GenerateConnectManifestResponse,
    GenerateMembershipRBACRoleBindingYAMLRequest,
    GenerateMembershipRBACRoleBindingYAMLResponse,
    GetFeatureRequest,
    GetFleetRequest,
    GetMembershipBindingRequest,
    GetMembershipRBACRoleBindingRequest,
    GetMembershipRequest,
    GetScopeNamespaceRequest,
    GetScopeRBACRoleBindingRequest,
    GetScopeRequest,
    ListBoundMembershipsRequest,
    ListBoundMembershipsResponse,
    ListFeaturesRequest,
    ListFeaturesResponse,
    ListFleetsRequest,
    ListFleetsResponse,
    ListMembershipBindingsRequest,
    ListMembershipBindingsResponse,
    ListMembershipRBACRoleBindingsRequest,
    ListMembershipRBACRoleBindingsResponse,
    ListMembershipsRequest,
    ListMembershipsResponse,
    ListPermittedScopesRequest,
    ListPermittedScopesResponse,
    ListScopeNamespacesRequest,
    ListScopeNamespacesResponse,
    ListScopeRBACRoleBindingsRequest,
    ListScopeRBACRoleBindingsResponse,
    ListScopesRequest,
    ListScopesResponse,
    OperationMetadata,
    TypeMeta,
    UpdateFeatureRequest,
    UpdateFleetRequest,
    UpdateMembershipBindingRequest,
    UpdateMembershipRBACRoleBindingRequest,
    UpdateMembershipRequest,
    UpdateScopeNamespaceRequest,
    UpdateScopeRBACRoleBindingRequest,
    UpdateScopeRequest,
)

__all__ = (
    "GkeHubAsyncClient",
    "Authority",
    "BinaryAuthorizationConfig",
    "CommonFeatureSpec",
    "CommonFeatureState",
    "CompliancePostureConfig",
    "ConnectAgentResource",
    "CreateFeatureRequest",
    "CreateFleetRequest",
    "CreateMembershipBindingRequest",
    "CreateMembershipRBACRoleBindingRequest",
    "CreateMembershipRequest",
    "CreateScopeNamespaceRequest",
    "CreateScopeRBACRoleBindingRequest",
    "CreateScopeRequest",
    "DefaultClusterConfig",
    "DeleteFeatureRequest",
    "DeleteFleetRequest",
    "DeleteMembershipBindingRequest",
    "DeleteMembershipRBACRoleBindingRequest",
    "DeleteMembershipRequest",
    "DeleteScopeNamespaceRequest",
    "DeleteScopeRBACRoleBindingRequest",
    "DeleteScopeRequest",
    "Feature",
    "FeatureResourceState",
    "FeatureState",
    "Fleet",
    "FleetLifecycleState",
    "GenerateConnectManifestRequest",
    "GenerateConnectManifestResponse",
    "GenerateMembershipRBACRoleBindingYAMLRequest",
    "GenerateMembershipRBACRoleBindingYAMLResponse",
    "GetFeatureRequest",
    "GetFleetRequest",
    "GetMembershipBindingRequest",
    "GetMembershipRBACRoleBindingRequest",
    "GetMembershipRequest",
    "GetScopeNamespaceRequest",
    "GetScopeRBACRoleBindingRequest",
    "GetScopeRequest",
    "GkeCluster",
    "GkeHubClient",
    "KubernetesMetadata",
    "KubernetesResource",
    "ListBoundMembershipsRequest",
    "ListBoundMembershipsResponse",
    "ListFeaturesRequest",
    "ListFeaturesResponse",
    "ListFleetsRequest",
    "ListFleetsResponse",
    "ListMembershipBindingsRequest",
    "ListMembershipBindingsResponse",
    "ListMembershipRBACRoleBindingsRequest",
    "ListMembershipRBACRoleBindingsResponse",
    "ListMembershipsRequest",
    "ListMembershipsResponse",
    "ListPermittedScopesRequest",
    "ListPermittedScopesResponse",
    "ListScopeNamespacesRequest",
    "ListScopeNamespacesResponse",
    "ListScopeRBACRoleBindingsRequest",
    "ListScopeRBACRoleBindingsResponse",
    "ListScopesRequest",
    "ListScopesResponse",
    "Membership",
    "MembershipBinding",
    "MembershipBindingLifecycleState",
    "MembershipEndpoint",
    "MembershipFeatureSpec",
    "MembershipFeatureState",
    "MembershipState",
    "MonitoringConfig",
    "Namespace",
    "NamespaceLifecycleState",
    "OperationMetadata",
    "RBACRoleBinding",
    "RBACRoleBindingLifecycleState",
    "ResourceManifest",
    "ResourceOptions",
    "Scope",
    "ScopeFeatureSpec",
    "ScopeFeatureState",
    "ScopeLifecycleState",
    "SecurityPostureConfig",
    "TypeMeta",
    "UpdateFeatureRequest",
    "UpdateFleetRequest",
    "UpdateMembershipBindingRequest",
    "UpdateMembershipRBACRoleBindingRequest",
    "UpdateMembershipRequest",
    "UpdateScopeNamespaceRequest",
    "UpdateScopeRBACRoleBindingRequest",
    "UpdateScopeRequest",
)

api_core.check_python_version("google.cloud.gkehub_v1")
api_core.check_dependency_versions("google.cloud.gkehub_v1")
