# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.recaptchaenterprise_v1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.recaptchaenterprise_v1.services.recaptcha_enterprise_service",
    "google.cloud.recaptchaenterprise_v1.types.recaptchaenterprise",
}


from .services.recaptcha_enterprise_service import (
    RecaptchaEnterpriseServiceAsyncClient,
    RecaptchaEnterpriseServiceClient,
)
from .types.recaptchaenterprise import (
    AccountDefenderAssessment,
    AccountVerificationInfo,
    AddIpOverrideRequest,
    AddIpOverrideResponse,
    AndroidKeySettings,
    AnnotateAssessmentRequest,
    AnnotateAssessmentResponse,
    AppleDeveloperId,
    Assessment,
    AssessmentEnvironment,
    Bot,
    ChallengeMetrics,
    ChallengeRule,
    ChallengeRuleEvaluation,
    ChallengeRuleGroup,
    ChallengeType,
    ClientSettings,
    CreateAssessmentRequest,
    CreateFirewallPolicyRequest,
    CreateKeyRequest,
    DeleteFirewallPolicyRequest,
    DeleteKeyRequest,
    EndpointVerificationInfo,
    Event,
    ExpressKeySettings,
    FirewallAction,
    FirewallPolicy,
    FirewallPolicyAssessment,
    FraudPreventionAssessment,
    FraudSignals,
    GetFirewallPolicyRequest,
    GetKeyRequest,
    GetMetricsRequest,
    GetPolicyRequest,
    IOSKeySettings,
    IpOverrideData,
    Key,
    ListFirewallPoliciesRequest,
    ListFirewallPoliciesResponse,
    ListIpOverridesRequest,
    ListIpOverridesResponse,
    ListKeysRequest,
    ListKeysResponse,
    ListRelatedAccountGroupMembershipsRequest,
    ListRelatedAccountGroupMembershipsResponse,
    ListRelatedAccountGroupsRequest,
    ListRelatedAccountGroupsResponse,
    Metrics,
    MigrateKeyRequest,
    PhoneAuthenticationEvent,
    PhoneFraudAssessment,
    Policy,
    PolicyEvaluation,
    PrivatePasswordLeakVerification,
    ProtectedEndpoint,
    ProtectedEndpointGroup,
    RelatedAccountGroup,
    RelatedAccountGroupMembership,
    RemoveIpOverrideRequest,
    RemoveIpOverrideResponse,
    ReorderFirewallPoliciesRequest,
    ReorderFirewallPoliciesResponse,
    RetrieveLegacySecretKeyRequest,
    RetrieveLegacySecretKeyResponse,
    RiskAnalysis,
    ScoreDistribution,
    ScoreMetrics,
    SearchRelatedAccountGroupMembershipsRequest,
    SearchRelatedAccountGroupMembershipsResponse,
    SmsTollFraudVerdict,
    TestingOptions,
    TokenProperties,
    TransactionData,
    TransactionEvent,
    UniversalKeySettings,
    UpdateFirewallPolicyRequest,
    UpdateKeyRequest,
    UpdatePolicyRequest,
    UserId,
    UserInfo,
    WafSettings,
    WebKeySettings,
)

__all__ = (
    "RecaptchaEnterpriseServiceAsyncClient",
    "AccountDefenderAssessment",
    "AccountVerificationInfo",
    "AddIpOverrideRequest",
    "AddIpOverrideResponse",
    "AndroidKeySettings",
    "AnnotateAssessmentRequest",
    "AnnotateAssessmentResponse",
    "AppleDeveloperId",
    "Assessment",
    "AssessmentEnvironment",
    "Bot",
    "ChallengeMetrics",
    "ChallengeRule",
    "ChallengeRuleEvaluation",
    "ChallengeRuleGroup",
    "ChallengeType",
    "ClientSettings",
    "CreateAssessmentRequest",
    "CreateFirewallPolicyRequest",
    "CreateKeyRequest",
    "DeleteFirewallPolicyRequest",
    "DeleteKeyRequest",
    "EndpointVerificationInfo",
    "Event",
    "ExpressKeySettings",
    "FirewallAction",
    "FirewallPolicy",
    "FirewallPolicyAssessment",
    "FraudPreventionAssessment",
    "FraudSignals",
    "GetFirewallPolicyRequest",
    "GetKeyRequest",
    "GetMetricsRequest",
    "GetPolicyRequest",
    "IOSKeySettings",
    "IpOverrideData",
    "Key",
    "ListFirewallPoliciesRequest",
    "ListFirewallPoliciesResponse",
    "ListIpOverridesRequest",
    "ListIpOverridesResponse",
    "ListKeysRequest",
    "ListKeysResponse",
    "ListRelatedAccountGroupMembershipsRequest",
    "ListRelatedAccountGroupMembershipsResponse",
    "ListRelatedAccountGroupsRequest",
    "ListRelatedAccountGroupsResponse",
    "Metrics",
    "MigrateKeyRequest",
    "PhoneAuthenticationEvent",
    "PhoneFraudAssessment",
    "Policy",
    "PolicyEvaluation",
    "PrivatePasswordLeakVerification",
    "ProtectedEndpoint",
    "ProtectedEndpointGroup",
    "RecaptchaEnterpriseServiceClient",
    "RelatedAccountGroup",
    "RelatedAccountGroupMembership",
    "RemoveIpOverrideRequest",
    "RemoveIpOverrideResponse",
    "ReorderFirewallPoliciesRequest",
    "ReorderFirewallPoliciesResponse",
    "RetrieveLegacySecretKeyRequest",
    "RetrieveLegacySecretKeyResponse",
    "RiskAnalysis",
    "ScoreDistribution",
    "ScoreMetrics",
    "SearchRelatedAccountGroupMembershipsRequest",
    "SearchRelatedAccountGroupMembershipsResponse",
    "SmsTollFraudVerdict",
    "TestingOptions",
    "TokenProperties",
    "TransactionData",
    "TransactionEvent",
    "UniversalKeySettings",
    "UpdateFirewallPolicyRequest",
    "UpdateKeyRequest",
    "UpdatePolicyRequest",
    "UserId",
    "UserInfo",
    "WafSettings",
    "WebKeySettings",
)

api_core.check_python_version("google.cloud.recaptchaenterprise_v1")
api_core.check_dependency_versions("google.cloud.recaptchaenterprise_v1")
