# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.networkconnectivity_v1beta import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.networkconnectivity_v1beta.services.data_transfer_service",
    "google.cloud.networkconnectivity_v1beta.services.hub_service",
    "google.cloud.networkconnectivity_v1beta.services.policy_based_routing_service",
    "google.cloud.networkconnectivity_v1beta.services.transport_manager",
    "google.cloud.networkconnectivity_v1beta.types.common",
    "google.cloud.networkconnectivity_v1beta.types.data_transfer",
    "google.cloud.networkconnectivity_v1beta.types.hub",
    "google.cloud.networkconnectivity_v1beta.types.policy_based_routing",
    "google.cloud.networkconnectivity_v1beta.types.transport_manager",
}


from .services.data_transfer_service import (
    DataTransferServiceAsyncClient,
    DataTransferServiceClient,
)
from .services.hub_service import HubServiceAsyncClient, HubServiceClient
from .services.policy_based_routing_service import (
    PolicyBasedRoutingServiceAsyncClient,
    PolicyBasedRoutingServiceClient,
)
from .services.transport_manager import (
    TransportManagerAsyncClient,
    TransportManagerClient,
)
from .types.common import OperationMetadata
from .types.data_transfer import (
    CreateDestinationRequest,
    CreateMulticloudDataTransferConfigRequest,
    DeleteDestinationRequest,
    DeleteMulticloudDataTransferConfigRequest,
    Destination,
    GetDestinationRequest,
    GetMulticloudDataTransferConfigRequest,
    GetMulticloudDataTransferSupportedServiceRequest,
    ListDestinationsRequest,
    ListDestinationsResponse,
    ListMulticloudDataTransferConfigsRequest,
    ListMulticloudDataTransferConfigsResponse,
    ListMulticloudDataTransferSupportedServicesRequest,
    ListMulticloudDataTransferSupportedServicesResponse,
    MulticloudDataTransferConfig,
    MulticloudDataTransferSupportedService,
    ServiceConfig,
    StateTimeline,
    UpdateDestinationRequest,
    UpdateMulticloudDataTransferConfigRequest,
)
from .types.hub import (
    AcceptHubSpokeRequest,
    AcceptHubSpokeResponse,
    AcceptSpokeUpdateRequest,
    AcceptSpokeUpdateResponse,
    AutoAccept,
    CreateGatewayAdvertisedRouteRequest,
    CreateHubRequest,
    CreateSpokeRequest,
    DeleteGatewayAdvertisedRouteRequest,
    DeleteHubRequest,
    DeleteSpokeRequest,
    Gateway,
    GatewayAdvertisedRoute,
    GetGatewayAdvertisedRouteRequest,
    GetGroupRequest,
    GetHubRequest,
    GetRouteRequest,
    GetRouteTableRequest,
    GetSpokeRequest,
    Group,
    Hub,
    HubStatusEntry,
    LinkedInterconnectAttachments,
    LinkedProducerVpcNetwork,
    LinkedRouterApplianceInstances,
    LinkedVpcNetwork,
    LinkedVpnTunnels,
    ListGatewayAdvertisedRoutesRequest,
    ListGatewayAdvertisedRoutesResponse,
    ListGroupsRequest,
    ListGroupsResponse,
    ListHubSpokesRequest,
    ListHubSpokesResponse,
    ListHubsRequest,
    ListHubsResponse,
    ListRoutesRequest,
    ListRoutesResponse,
    ListRouteTablesRequest,
    ListRouteTablesResponse,
    ListSpokesRequest,
    ListSpokesResponse,
    LocationFeature,
    LocationMetadata,
    NextHopInterconnectAttachment,
    NextHopRouterApplianceInstance,
    NextHopSpoke,
    NextHopVpcNetwork,
    NextHopVPNTunnel,
    PolicyMode,
    PresetTopology,
    PscPropagationStatus,
    QueryHubStatusRequest,
    QueryHubStatusResponse,
    RejectHubSpokeRequest,
    RejectHubSpokeResponse,
    RejectSpokeUpdateRequest,
    RejectSpokeUpdateResponse,
    Route,
    RouterApplianceInstance,
    RouteTable,
    RouteType,
    RoutingVPC,
    Spoke,
    SpokeSummary,
    SpokeType,
    State,
    UpdateGatewayAdvertisedRouteRequest,
    UpdateGroupRequest,
    UpdateHubRequest,
    UpdateSpokeRequest,
)
from .types.policy_based_routing import (
    CreatePolicyBasedRouteRequest,
    DeletePolicyBasedRouteRequest,
    GetPolicyBasedRouteRequest,
    ListPolicyBasedRoutesRequest,
    ListPolicyBasedRoutesResponse,
    PolicyBasedRoute,
)
from .types.transport_manager import (
    CreateTransportRequest,
    DeleteTransportRequest,
    GetRemoteTransportProfileRequest,
    GetStatusRequest,
    GetStatusResponse,
    GetTransportRequest,
    ListRemoteTransportProfilesRequest,
    ListRemoteTransportProfilesResponse,
    ListTransportsRequest,
    ListTransportsResponse,
    ParseFromActivationKeyRequest,
    ParseFromActivationKeyResponse,
    RemoteTransportProfile,
    Transport,
    UpdateTransportRequest,
)

__all__ = (
    "DataTransferServiceAsyncClient",
    "HubServiceAsyncClient",
    "PolicyBasedRoutingServiceAsyncClient",
    "TransportManagerAsyncClient",
    "AcceptHubSpokeRequest",
    "AcceptHubSpokeResponse",
    "AcceptSpokeUpdateRequest",
    "AcceptSpokeUpdateResponse",
    "AutoAccept",
    "CreateDestinationRequest",
    "CreateGatewayAdvertisedRouteRequest",
    "CreateHubRequest",
    "CreateMulticloudDataTransferConfigRequest",
    "CreatePolicyBasedRouteRequest",
    "CreateSpokeRequest",
    "CreateTransportRequest",
    "DataTransferServiceClient",
    "DeleteDestinationRequest",
    "DeleteGatewayAdvertisedRouteRequest",
    "DeleteHubRequest",
    "DeleteMulticloudDataTransferConfigRequest",
    "DeletePolicyBasedRouteRequest",
    "DeleteSpokeRequest",
    "DeleteTransportRequest",
    "Destination",
    "Gateway",
    "GatewayAdvertisedRoute",
    "GetDestinationRequest",
    "GetGatewayAdvertisedRouteRequest",
    "GetGroupRequest",
    "GetHubRequest",
    "GetMulticloudDataTransferConfigRequest",
    "GetMulticloudDataTransferSupportedServiceRequest",
    "GetPolicyBasedRouteRequest",
    "GetRemoteTransportProfileRequest",
    "GetRouteRequest",
    "GetRouteTableRequest",
    "GetSpokeRequest",
    "GetStatusRequest",
    "GetStatusResponse",
    "GetTransportRequest",
    "Group",
    "Hub",
    "HubServiceClient",
    "HubStatusEntry",
    "LinkedInterconnectAttachments",
    "LinkedProducerVpcNetwork",
    "LinkedRouterApplianceInstances",
    "LinkedVpcNetwork",
    "LinkedVpnTunnels",
    "ListDestinationsRequest",
    "ListDestinationsResponse",
    "ListGatewayAdvertisedRoutesRequest",
    "ListGatewayAdvertisedRoutesResponse",
    "ListGroupsRequest",
    "ListGroupsResponse",
    "ListHubSpokesRequest",
    "ListHubSpokesResponse",
    "ListHubsRequest",
    "ListHubsResponse",
    "ListMulticloudDataTransferConfigsRequest",
    "ListMulticloudDataTransferConfigsResponse",
    "ListMulticloudDataTransferSupportedServicesRequest",
    "ListMulticloudDataTransferSupportedServicesResponse",
    "ListPolicyBasedRoutesRequest",
    "ListPolicyBasedRoutesResponse",
    "ListRemoteTransportProfilesRequest",
    "ListRemoteTransportProfilesResponse",
    "ListRouteTablesRequest",
    "ListRouteTablesResponse",
    "ListRoutesRequest",
    "ListRoutesResponse",
    "ListSpokesRequest",
    "ListSpokesResponse",
    "ListTransportsRequest",
    "ListTransportsResponse",
    "LocationFeature",
    "LocationMetadata",
    "MulticloudDataTransferConfig",
    "MulticloudDataTransferSupportedService",
    "NextHopInterconnectAttachment",
    "NextHopRouterApplianceInstance",
    "NextHopSpoke",
    "NextHopVPNTunnel",
    "NextHopVpcNetwork",
    "OperationMetadata",
    "ParseFromActivationKeyRequest",
    "ParseFromActivationKeyResponse",
    "PolicyBasedRoute",
    "PolicyBasedRoutingServiceClient",
    "PolicyMode",
    "PresetTopology",
    "PscPropagationStatus",
    "QueryHubStatusRequest",
    "QueryHubStatusResponse",
    "RejectHubSpokeRequest",
    "RejectHubSpokeResponse",
    "RejectSpokeUpdateRequest",
    "RejectSpokeUpdateResponse",
    "RemoteTransportProfile",
    "Route",
    "RouteTable",
    "RouteType",
    "RouterApplianceInstance",
    "RoutingVPC",
    "ServiceConfig",
    "Spoke",
    "SpokeSummary",
    "SpokeType",
    "State",
    "StateTimeline",
    "Transport",
    "TransportManagerClient",
    "UpdateDestinationRequest",
    "UpdateGatewayAdvertisedRouteRequest",
    "UpdateGroupRequest",
    "UpdateHubRequest",
    "UpdateMulticloudDataTransferConfigRequest",
    "UpdateSpokeRequest",
    "UpdateTransportRequest",
)

api_core.check_python_version("google.cloud.networkconnectivity_v1beta")
api_core.check_dependency_versions("google.cloud.networkconnectivity_v1beta")
