# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from .resource import (
    ActiveConference,
    AnonymousUser,
    ConferenceRecord,
    DocsDestination,
    DriveDestination,
    Member,
    Participant,
    ParticipantSession,
    PhoneUser,
    Recording,
    SignedinUser,
    SmartNote,
    Space,
    SpaceConfig,
    Transcript,
    TranscriptEntry,
)
from .service import (
    BatchUpdateMembersRequest,
    BatchUpdateMembersResponse,
    CreateMemberRequest,
    CreateSpaceRequest,
    DeleteMemberRequest,
    EndActiveConferenceRequest,
    GetConferenceRecordRequest,
    GetMemberRequest,
    GetParticipantRequest,
    GetParticipantSessionRequest,
    GetRecordingRequest,
    GetSmartNoteRequest,
    GetSpaceRequest,
    GetTranscriptEntryRequest,
    GetTranscriptRequest,
    ListConferenceRecordsRequest,
    ListConferenceRecordsResponse,
    ListMembersRequest,
    ListMembersResponse,
    ListParticipantSessionsRequest,
    ListParticipantSessionsResponse,
    ListParticipantsRequest,
    ListParticipantsResponse,
    ListRecordingsRequest,
    ListRecordingsResponse,
    ListSmartNotesRequest,
    ListSmartNotesResponse,
    ListTranscriptEntriesRequest,
    ListTranscriptEntriesResponse,
    ListTranscriptsRequest,
    ListTranscriptsResponse,
    UpdateMemberRequest,
    UpdateSpaceRequest,
)

__all__ = (
    "ActiveConference",
    "AnonymousUser",
    "ConferenceRecord",
    "DocsDestination",
    "DriveDestination",
    "Member",
    "Participant",
    "ParticipantSession",
    "PhoneUser",
    "Recording",
    "SignedinUser",
    "SmartNote",
    "Space",
    "SpaceConfig",
    "Transcript",
    "TranscriptEntry",
    "BatchUpdateMembersRequest",
    "BatchUpdateMembersResponse",
    "CreateMemberRequest",
    "CreateSpaceRequest",
    "DeleteMemberRequest",
    "EndActiveConferenceRequest",
    "GetConferenceRecordRequest",
    "GetMemberRequest",
    "GetParticipantRequest",
    "GetParticipantSessionRequest",
    "GetRecordingRequest",
    "GetSmartNoteRequest",
    "GetSpaceRequest",
    "GetTranscriptEntryRequest",
    "GetTranscriptRequest",
    "ListConferenceRecordsRequest",
    "ListConferenceRecordsResponse",
    "ListMembersRequest",
    "ListMembersResponse",
    "ListParticipantSessionsRequest",
    "ListParticipantSessionsResponse",
    "ListParticipantsRequest",
    "ListParticipantsResponse",
    "ListRecordingsRequest",
    "ListRecordingsResponse",
    "ListSmartNotesRequest",
    "ListSmartNotesResponse",
    "ListTranscriptEntriesRequest",
    "ListTranscriptEntriesResponse",
    "ListTranscriptsRequest",
    "ListTranscriptsResponse",
    "UpdateMemberRequest",
    "UpdateSpaceRequest",
)
