package:
  name: pandas-gbq
  version: "0.1.0"

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandas
    - httplib2
    - google-api-python-client
    - oauth2client

test:
  # Python imports
  imports:
    - pandas_gbq
about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD License
  summary: 'pandas-gbq is a package providing an interface to the Google Big Query interface from pandas'
