global_files_allowlist:
  # Allow the container to read and write the root `CHANGELOG.md`
  # file during the `release` step to update the latest client library
  # versions which are hardcoded in the file.
  - path: "CHANGELOG.md"
    permissions: "read-write"

libraries:
# libraries have "release_blocked: true" so that releases are
# explicitly initiated.
# TODO(https://github.com/googleapis/google-cloud-python/issues/16489):
# Allow releases for bigframes once this bug above is fixed.
  - id: "bigframes"
    release_blocked: true