global_files_allowlist:
  # Allow the container to read and write the root `CHANGELOG.md`
  # file during the `release` step to update the latest client library
  # versions which are hardcoded in the file.
  - path: "CHANGELOG.md"
    permissions: "read-write"

libraries:
# libraries have "release_blocked: true" so that releases are
# explicitly initiated.
# TODO(https://github.com/googleapis/google-cloud-python/issues/16180):
# `google-django-spanner` is blocked until the presubmits are green.
  - id: "google-django-spanner"
    release_blocked: true
  - id: "bigquery-magics"
    release_blocked: true
  - id: "db-dtypes"
    release_blocked: true
  - id: "django-google-spanner"
    release_blocked: true
  - id: "google-ads-admanager"
    release_blocked: true
  - id: "google-ads-datamanager"
    release_blocked: true
  - id: "google-ads-marketingplatform-admin"
    release_blocked: true
  - id: "google-ai-generativelanguage"
    release_blocked: true
  - id: "google-analytics-admin"
    release_blocked: true
  - id: "google-analytics-data"
    release_blocked: true
  - id: "google-api-core"
    release_blocked: true
  - id: "google-apps-card"
    release_blocked: true
  - id: "google-apps-chat"
    release_blocked: true
  - id: "google-apps-events-subscriptions"
    release_blocked: true
  - id: "google-apps-meet"
    release_blocked: true
  - id: "google-apps-script-type"
    release_blocked: true
  - id: "google-area120-tables"
    release_blocked: true
  - id: "google-auth"
    release_blocked: true
  - id: "google-auth-httplib2"
    release_blocked: true
  - id: "google-auth-oauthlib"
    release_blocked: true
  - id: "google-cloud-access-approval"
    release_blocked: true
  - id: "google-cloud-access-context-manager"
    release_blocked: true
  - id: "google-cloud-advisorynotifications"
    release_blocked: true
  - id: "google-cloud-alloydb"
    release_blocked: true
  - id: "google-cloud-alloydb-connectors"
    release_blocked: true
  - id: "google-cloud-api-gateway"
    release_blocked: true
  - id: "google-cloud-api-keys"
    release_blocked: true
  - id: "google-cloud-apigee-connect"
    release_blocked: true
  - id: "google-cloud-apigee-registry"
    release_blocked: true
  - id: "google-cloud-apihub"
    release_blocked: true
  - id: "google-cloud-apiregistry"
    release_blocked: true
  - id: "google-cloud-appengine-admin"
    release_blocked: true
  - id: "google-cloud-appengine-logging"
    release_blocked: true
  - id: "google-cloud-apphub"
    release_blocked: true
  - id: "google-cloud-artifact-registry"
    release_blocked: true
  - id: "google-cloud-asset"
    release_blocked: true
  - id: "google-cloud-assured-workloads"
    release_blocked: true
  - id: "google-cloud-audit-log"
    release_blocked: true
  - id: "google-cloud-auditmanager"
    release_blocked: true
  - id: "google-cloud-automl"
    release_blocked: true
  - id: "google-cloud-backupdr"
    release_blocked: true
  - id: "google-cloud-bare-metal-solution"
    release_blocked: true
  - id: "google-cloud-batch"
    release_blocked: true
  - id: "google-cloud-beyondcorp-appconnections"
    release_blocked: true
  - id: "google-cloud-beyondcorp-appconnectors"
    release_blocked: true
  - id: "google-cloud-beyondcorp-appgateways"
    release_blocked: true
  - id: "google-cloud-beyondcorp-clientconnectorservices"
    release_blocked: true
  - id: "google-cloud-beyondcorp-clientgateways"
    release_blocked: true
  - id: "google-cloud-biglake"
    release_blocked: true
  - id: "google-cloud-biglake-hive"
    release_blocked: true
  - id: "google-cloud-bigquery"
    release_blocked: true
  - id: "google-cloud-bigquery-analyticshub"
    release_blocked: true
  - id: "google-cloud-bigquery-biglake"
    release_blocked: true
  - id: "google-cloud-bigquery-connection"
    release_blocked: true
  - id: "google-cloud-bigquery-data-exchange"
    release_blocked: true
  - id: "google-cloud-bigquery-datapolicies"
    release_blocked: true
  - id: "google-cloud-bigquery-datatransfer"
    release_blocked: true
  - id: "google-cloud-bigquery-logging"
    release_blocked: true
  - id: "google-cloud-bigquery-migration"
    release_blocked: true
  - id: "google-cloud-bigquery-reservation"
    release_blocked: true
  - id: "google-cloud-bigquery-storage"
    release_blocked: true
  - id: "google-cloud-billing"
    release_blocked: true
  - id: "google-cloud-billing-budgets"
    release_blocked: true
  - id: "google-cloud-binary-authorization"
    release_blocked: true
  - id: "google-cloud-build"
    release_blocked: true
  - id: "google-cloud-capacityplanner"
    release_blocked: true
  - id: "google-cloud-certificate-manager"
    release_blocked: true
  - id: "google-cloud-ces"
    release_blocked: true
  - id: "google-cloud-channel"
    release_blocked: true
  - id: "google-cloud-chronicle"
    release_blocked: true
  - id: "google-cloud-cloudcontrolspartner"
    release_blocked: true
  - id: "google-cloud-cloudsecuritycompliance"
    release_blocked: true
  - id: "google-cloud-commerce-consumer-procurement"
    release_blocked: true
  - id: "google-cloud-common"
    release_blocked: true
  - id: "google-cloud-compute"
    release_blocked: true
  - id: "google-cloud-compute-v1beta"
    release_blocked: true
  - id: "google-cloud-confidentialcomputing"
    release_blocked: true
  - id: "google-cloud-config"
    release_blocked: true
  - id: "google-cloud-configdelivery"
    release_blocked: true
  - id: "google-cloud-contact-center-insights"
    release_blocked: true
  - id: "google-cloud-container"
    release_blocked: true
  - id: "google-cloud-containeranalysis"
    release_blocked: true
  - id: "google-cloud-contentwarehouse"
    release_blocked: true
  - id: "google-cloud-core"
    release_blocked: true
  - id: "google-cloud-data-fusion"
    release_blocked: true
  - id: "google-cloud-data-qna"
    release_blocked: true
  - id: "google-cloud-databasecenter"
    release_blocked: true
  - id: "google-cloud-datacatalog"
    release_blocked: true
  - id: "google-cloud-datacatalog-lineage"
    release_blocked: true
  - id: "google-cloud-datacatalog-lineage-configmanagement"
    release_blocked: true
  - id: "google-cloud-dataflow-client"
    release_blocked: true
  - id: "google-cloud-dataform"
    release_blocked: true
  - id: "google-cloud-datalabeling"
    release_blocked: true
  - id: "google-cloud-dataplex"
    release_blocked: true
  - id: "google-cloud-dataproc"
    release_blocked: true
  - id: "google-cloud-dataproc-metastore"
    release_blocked: true
  - id: "google-cloud-datastore"
    release_blocked: true
  - id: "google-cloud-datastream"
    release_blocked: true
  - id: "google-cloud-deploy"
    release_blocked: true
  - id: "google-cloud-developerconnect"
    release_blocked: true
  - id: "google-cloud-devicestreaming"
    release_blocked: true
  - id: "google-cloud-dialogflow"
    release_blocked: true
  - id: "google-cloud-dialogflow-cx"
    release_blocked: true
  - id: "google-cloud-discoveryengine"
    release_blocked: true
  - id: "google-cloud-dlp"
    release_blocked: true
  - id: "google-cloud-dms"
    release_blocked: true
  - id: "google-cloud-dns"
    release_blocked: true
  - id: "google-cloud-documentai"
    release_blocked: true
  - id: "google-cloud-documentai-toolbox"
    release_blocked: true
  - id: "google-cloud-domains"
    release_blocked: true
  - id: "google-cloud-edgecontainer"
    release_blocked: true
  - id: "google-cloud-edgenetwork"
    release_blocked: true
  - id: "google-cloud-enterpriseknowledgegraph"
    release_blocked: true
  - id: "google-cloud-error-reporting"
    release_blocked: true
  - id: "google-cloud-essential-contacts"
    release_blocked: true
  - id: "google-cloud-eventarc"
    release_blocked: true
  - id: "google-cloud-eventarc-publishing"
    release_blocked: true
  - id: "google-cloud-filestore"
    release_blocked: true
  - id: "google-cloud-financialservices"
    release_blocked: true
  - id: "google-cloud-firestore"
    release_blocked: true
  - id: "google-cloud-functions"
    release_blocked: true
  - id: "google-cloud-gdchardwaremanagement"
    release_blocked: true
  - id: "google-cloud-geminidataanalytics"
    release_blocked: true
  - id: "google-cloud-gke-backup"
    release_blocked: true
  - id: "google-cloud-gke-connect-gateway"
    release_blocked: true
  - id: "google-cloud-gke-hub"
    release_blocked: true
  - id: "google-cloud-gke-multicloud"
    release_blocked: true
  - id: "google-cloud-gkerecommender"
    release_blocked: true
  - id: "google-cloud-gsuiteaddons"
    release_blocked: true
  - id: "google-cloud-hypercomputecluster"
    release_blocked: true
  - id: "google-cloud-iam"
    release_blocked: true
  - id: "google-cloud-iam-logging"
    release_blocked: true
  - id: "google-cloud-iap"
    release_blocked: true
  - id: "google-cloud-ids"
    release_blocked: true
