# This file is being migrated to librarian@latest, and is no longer maintained by hand.

release_only_mode: true
global_files_allowlist:
  - path: CHANGELOG.md
    permissions: read-write
libraries:
  - id: google-django-spanner
    release_blocked: true
  - id: google-cloud-storage
    release_blocked: true
  - generate_blocked: true
    id: google-cloud-bigtable
  - id: bigframes
    release_blocked: true
  - generate_blocked: true
    id: google-cloud-firestore
    release_blocked: true
  - generate_blocked: true
    id: google-cloud-dialogflow
  - id: google-crc32c
    release_blocked: true
  - id: google-cloud-spanner
    release_blocked: true
  - generate_blocked: true
    id: google-area120-tables
