# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.cloud.network_security_v1alpha1 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.cloud.network_security_v1alpha1.services.dns_threat_detector_service",
    "google.cloud.network_security_v1alpha1.services.firewall_activation",
    "google.cloud.network_security_v1alpha1.services.intercept",
    "google.cloud.network_security_v1alpha1.services.mirroring",
    "google.cloud.network_security_v1alpha1.services.network_security",
    "google.cloud.network_security_v1alpha1.services.organization_security_profile_group_service",
    "google.cloud.network_security_v1alpha1.services.sse_gateway_service",
    "google.cloud.network_security_v1alpha1.services.sse_realm_service",
    "google.cloud.network_security_v1alpha1.types.authorization_policy",
    "google.cloud.network_security_v1alpha1.types.authz_policy",
    "google.cloud.network_security_v1alpha1.types.backend_authentication_config",
    "google.cloud.network_security_v1alpha1.types.client_tls_policy",
    "google.cloud.network_security_v1alpha1.types.common",
    "google.cloud.network_security_v1alpha1.types.dns_threat_detector",
    "google.cloud.network_security_v1alpha1.types.firewall_activation",
    "google.cloud.network_security_v1alpha1.types.gateway_security_policy",
    "google.cloud.network_security_v1alpha1.types.gateway_security_policy_rule",
    "google.cloud.network_security_v1alpha1.types.intercept",
    "google.cloud.network_security_v1alpha1.types.mirroring",
    "google.cloud.network_security_v1alpha1.types.network_security",
    "google.cloud.network_security_v1alpha1.types.security_profile_group",
    "google.cloud.network_security_v1alpha1.types.security_profile_group_intercept",
    "google.cloud.network_security_v1alpha1.types.security_profile_group_mirroring",
    "google.cloud.network_security_v1alpha1.types.security_profile_group_service",
    "google.cloud.network_security_v1alpha1.types.security_profile_group_threatprevention",
    "google.cloud.network_security_v1alpha1.types.security_profile_group_urlfiltering",
    "google.cloud.network_security_v1alpha1.types.server_tls_policy",
    "google.cloud.network_security_v1alpha1.types.sse_gateway",
    "google.cloud.network_security_v1alpha1.types.sse_realm",
    "google.cloud.network_security_v1alpha1.types.tls",
    "google.cloud.network_security_v1alpha1.types.tls_inspection_policy",
    "google.cloud.network_security_v1alpha1.types.url_list",
}


from .services.dns_threat_detector_service import (
    DnsThreatDetectorServiceAsyncClient,
    DnsThreatDetectorServiceClient,
)
from .services.firewall_activation import (
    FirewallActivationAsyncClient,
    FirewallActivationClient,
)
from .services.intercept import InterceptAsyncClient, InterceptClient
from .services.mirroring import MirroringAsyncClient, MirroringClient
from .services.network_security import NetworkSecurityAsyncClient, NetworkSecurityClient
from .services.organization_security_profile_group_service import (
    OrganizationSecurityProfileGroupServiceAsyncClient,
    OrganizationSecurityProfileGroupServiceClient,
)
from .services.sse_gateway_service import (
    SSEGatewayServiceAsyncClient,
    SSEGatewayServiceClient,
)
from .services.sse_realm_service import (
    SSERealmServiceAsyncClient,
    SSERealmServiceClient,
)
from .types.authorization_policy import (
    AuthorizationPolicy,
    CreateAuthorizationPolicyRequest,
    DeleteAuthorizationPolicyRequest,
    GetAuthorizationPolicyRequest,
    ListAuthorizationPoliciesRequest,
    ListAuthorizationPoliciesResponse,
    UpdateAuthorizationPolicyRequest,
)
from .types.authz_policy import (
    AuthzPolicy,
    CreateAuthzPolicyRequest,
    DeleteAuthzPolicyRequest,
    GetAuthzPolicyRequest,
    ListAuthzPoliciesRequest,
    ListAuthzPoliciesResponse,
    UpdateAuthzPolicyRequest,
)
from .types.backend_authentication_config import (
    BackendAuthenticationConfig,
    CreateBackendAuthenticationConfigRequest,
    DeleteBackendAuthenticationConfigRequest,
    GetBackendAuthenticationConfigRequest,
    ListBackendAuthenticationConfigsRequest,
    ListBackendAuthenticationConfigsResponse,
    UpdateBackendAuthenticationConfigRequest,
)
from .types.client_tls_policy import (
    ClientTlsPolicy,
    CreateClientTlsPolicyRequest,
    DeleteClientTlsPolicyRequest,
    GetClientTlsPolicyRequest,
    ListClientTlsPoliciesRequest,
    ListClientTlsPoliciesResponse,
    UpdateClientTlsPolicyRequest,
)
from .types.common import OperationMetadata
from .types.dns_threat_detector import (
    CreateDnsThreatDetectorRequest,
    DeleteDnsThreatDetectorRequest,
    DnsThreatDetector,
    GetDnsThreatDetectorRequest,
    ListDnsThreatDetectorsRequest,
    ListDnsThreatDetectorsResponse,
    UpdateDnsThreatDetectorRequest,
)
from .types.firewall_activation import (
    CreateFirewallEndpointAssociationRequest,
    CreateFirewallEndpointRequest,
    DeleteFirewallEndpointAssociationRequest,
    DeleteFirewallEndpointRequest,
    FirewallEndpoint,
    FirewallEndpointAssociation,
    GetFirewallEndpointAssociationRequest,
    GetFirewallEndpointRequest,
    ListFirewallEndpointAssociationsRequest,
    ListFirewallEndpointAssociationsResponse,
    ListFirewallEndpointsRequest,
    ListFirewallEndpointsResponse,
    UpdateFirewallEndpointAssociationRequest,
    UpdateFirewallEndpointRequest,
)
from .types.gateway_security_policy import (
    CreateGatewaySecurityPolicyRequest,
    DeleteGatewaySecurityPolicyRequest,
    GatewaySecurityPolicy,
    GetGatewaySecurityPolicyRequest,
    ListGatewaySecurityPoliciesRequest,
    ListGatewaySecurityPoliciesResponse,
    UpdateGatewaySecurityPolicyRequest,
)
from .types.gateway_security_policy_rule import (
    CreateGatewaySecurityPolicyRuleRequest,
    DeleteGatewaySecurityPolicyRuleRequest,
    GatewaySecurityPolicyRule,
    GetGatewaySecurityPolicyRuleRequest,
    ListGatewaySecurityPolicyRulesRequest,
    ListGatewaySecurityPolicyRulesResponse,
    UpdateGatewaySecurityPolicyRuleRequest,
)
from .types.intercept import (
    CreateInterceptDeploymentGroupRequest,
    CreateInterceptDeploymentRequest,
    CreateInterceptEndpointGroupAssociationRequest,
    CreateInterceptEndpointGroupRequest,
    DeleteInterceptDeploymentGroupRequest,
    DeleteInterceptDeploymentRequest,
    DeleteInterceptEndpointGroupAssociationRequest,
    DeleteInterceptEndpointGroupRequest,
    GetInterceptDeploymentGroupRequest,
    GetInterceptDeploymentRequest,
    GetInterceptEndpointGroupAssociationRequest,
    GetInterceptEndpointGroupRequest,
    InterceptDeployment,
    InterceptDeploymentGroup,
    InterceptEndpointGroup,
    InterceptEndpointGroupAssociation,
    InterceptLocation,
    ListInterceptDeploymentGroupsRequest,
    ListInterceptDeploymentGroupsResponse,
    ListInterceptDeploymentsRequest,
    ListInterceptDeploymentsResponse,
    ListInterceptEndpointGroupAssociationsRequest,
    ListInterceptEndpointGroupAssociationsResponse,
    ListInterceptEndpointGroupsRequest,
    ListInterceptEndpointGroupsResponse,
    UpdateInterceptDeploymentGroupRequest,
    UpdateInterceptDeploymentRequest,
    UpdateInterceptEndpointGroupAssociationRequest,
    UpdateInterceptEndpointGroupRequest,
)
from .types.mirroring import (
    CreateMirroringDeploymentGroupRequest,
    CreateMirroringDeploymentRequest,
    CreateMirroringEndpointGroupAssociationRequest,
    CreateMirroringEndpointGroupRequest,
    DeleteMirroringDeploymentGroupRequest,
    DeleteMirroringDeploymentRequest,
    DeleteMirroringEndpointGroupAssociationRequest,
    DeleteMirroringEndpointGroupRequest,
    GetMirroringDeploymentGroupRequest,
    GetMirroringDeploymentRequest,
    GetMirroringEndpointGroupAssociationRequest,
    GetMirroringEndpointGroupRequest,
    ListMirroringDeploymentGroupsRequest,
    ListMirroringDeploymentGroupsResponse,
    ListMirroringDeploymentsRequest,
    ListMirroringDeploymentsResponse,
    ListMirroringEndpointGroupAssociationsRequest,
    ListMirroringEndpointGroupAssociationsResponse,
    ListMirroringEndpointGroupsRequest,
    ListMirroringEndpointGroupsResponse,
    MirroringDeployment,
    MirroringDeploymentGroup,
    MirroringEndpointGroup,
    MirroringEndpointGroupAssociation,
    MirroringLocation,
    UpdateMirroringDeploymentGroupRequest,
    UpdateMirroringDeploymentRequest,
    UpdateMirroringEndpointGroupAssociationRequest,
    UpdateMirroringEndpointGroupRequest,
)
from .types.security_profile_group import SecurityProfile, SecurityProfileGroup
from .types.security_profile_group_intercept import CustomInterceptProfile
from .types.security_profile_group_mirroring import CustomMirroringProfile
from .types.security_profile_group_service import (
    CreateSecurityProfileGroupRequest,
    CreateSecurityProfileRequest,
    DeleteSecurityProfileGroupRequest,
    DeleteSecurityProfileRequest,
    GetSecurityProfileGroupRequest,
    GetSecurityProfileRequest,
    ListSecurityProfileGroupsRequest,
    ListSecurityProfileGroupsResponse,
    ListSecurityProfilesRequest,
    ListSecurityProfilesResponse,
    UpdateSecurityProfileGroupRequest,
    UpdateSecurityProfileRequest,
)
from .types.security_profile_group_threatprevention import (
    AntivirusOverride,
    Protocol,
    Severity,
    SeverityOverride,
    ThreatAction,
    ThreatOverride,
    ThreatPreventionProfile,
    ThreatType,
)
from .types.security_profile_group_urlfiltering import UrlFilter, UrlFilteringProfile
from .types.server_tls_policy import (
    CreateServerTlsPolicyRequest,
    DeleteServerTlsPolicyRequest,
    GetServerTlsPolicyRequest,
    ListServerTlsPoliciesRequest,
    ListServerTlsPoliciesResponse,
    ServerTlsPolicy,
    UpdateServerTlsPolicyRequest,
)
from .types.sse_gateway import (
    CreatePartnerSSEGatewayRequest,
    DeletePartnerSSEGatewayRequest,
    GetPartnerSSEGatewayRequest,
    GetSSEGatewayReferenceRequest,
    ListPartnerSSEGatewaysRequest,
    ListPartnerSSEGatewaysResponse,
    ListSSEGatewayReferencesRequest,
    ListSSEGatewayReferencesResponse,
    PartnerSSEGateway,
    SSEGatewayReference,
    UpdatePartnerSSEGatewayRequest,
)
from .types.sse_realm import (
    CreatePartnerSSERealmRequest,
    CreateSACAttachmentRequest,
    CreateSACRealmRequest,
    DeletePartnerSSERealmRequest,
    DeleteSACAttachmentRequest,
    DeleteSACRealmRequest,
    GetPartnerSSERealmRequest,
    GetSACAttachmentRequest,
    GetSACRealmRequest,
    ListPartnerSSERealmsRequest,
    ListPartnerSSERealmsResponse,
    ListSACAttachmentsRequest,
    ListSACAttachmentsResponse,
    ListSACRealmsRequest,
    ListSACRealmsResponse,
    PartnerSSERealm,
    SACAttachment,
    SACRealm,
)
from .types.tls import (
    CertificateProvider,
    CertificateProviderInstance,
    GrpcEndpoint,
    ValidationCA,
)
from .types.tls_inspection_policy import (
    CreateTlsInspectionPolicyRequest,
    DeleteTlsInspectionPolicyRequest,
    GetTlsInspectionPolicyRequest,
    ListTlsInspectionPoliciesRequest,
    ListTlsInspectionPoliciesResponse,
    TlsInspectionPolicy,
    UpdateTlsInspectionPolicyRequest,
)
from .types.url_list import (
    CreateUrlListRequest,
    DeleteUrlListRequest,
    GetUrlListRequest,
    ListUrlListsRequest,
    ListUrlListsResponse,
    UpdateUrlListRequest,
    UrlList,
)

__all__ = (
    "DnsThreatDetectorServiceAsyncClient",
    "FirewallActivationAsyncClient",
    "InterceptAsyncClient",
    "MirroringAsyncClient",
    "NetworkSecurityAsyncClient",
    "OrganizationSecurityProfileGroupServiceAsyncClient",
    "SSEGatewayServiceAsyncClient",
    "SSERealmServiceAsyncClient",
    "AntivirusOverride",
    "AuthorizationPolicy",
    "AuthzPolicy",
    "BackendAuthenticationConfig",
    "CertificateProvider",
    "CertificateProviderInstance",
    "ClientTlsPolicy",
    "CreateAuthorizationPolicyRequest",
    "CreateAuthzPolicyRequest",
    "CreateBackendAuthenticationConfigRequest",
    "CreateClientTlsPolicyRequest",
    "CreateDnsThreatDetectorRequest",
    "CreateFirewallEndpointAssociationRequest",
    "CreateFirewallEndpointRequest",
    "CreateGatewaySecurityPolicyRequest",
    "CreateGatewaySecurityPolicyRuleRequest",
    "CreateInterceptDeploymentGroupRequest",
    "CreateInterceptDeploymentRequest",
    "CreateInterceptEndpointGroupAssociationRequest",
    "CreateInterceptEndpointGroupRequest",
    "CreateMirroringDeploymentGroupRequest",
    "CreateMirroringDeploymentRequest",
    "CreateMirroringEndpointGroupAssociationRequest",
    "CreateMirroringEndpointGroupRequest",
    "CreatePartnerSSEGatewayRequest",
    "CreatePartnerSSERealmRequest",
    "CreateSACAttachmentRequest",
    "CreateSACRealmRequest",
    "CreateSecurityProfileGroupRequest",
    "CreateSecurityProfileRequest",
    "CreateServerTlsPolicyRequest",
    "CreateTlsInspectionPolicyRequest",
    "CreateUrlListRequest",
    "CustomInterceptProfile",
    "CustomMirroringProfile",
    "DeleteAuthorizationPolicyRequest",
    "DeleteAuthzPolicyRequest",
    "DeleteBackendAuthenticationConfigRequest",
    "DeleteClientTlsPolicyRequest",
    "DeleteDnsThreatDetectorRequest",
    "DeleteFirewallEndpointAssociationRequest",
    "DeleteFirewallEndpointRequest",
    "DeleteGatewaySecurityPolicyRequest",
    "DeleteGatewaySecurityPolicyRuleRequest",
    "DeleteInterceptDeploymentGroupRequest",
    "DeleteInterceptDeploymentRequest",
    "DeleteInterceptEndpointGroupAssociationRequest",
    "DeleteInterceptEndpointGroupRequest",
    "DeleteMirroringDeploymentGroupRequest",
    "DeleteMirroringDeploymentRequest",
    "DeleteMirroringEndpointGroupAssociationRequest",
    "DeleteMirroringEndpointGroupRequest",
    "DeletePartnerSSEGatewayRequest",
    "DeletePartnerSSERealmRequest",
    "DeleteSACAttachmentRequest",
    "DeleteSACRealmRequest",
    "DeleteSecurityProfileGroupRequest",
    "DeleteSecurityProfileRequest",
    "DeleteServerTlsPolicyRequest",
    "DeleteTlsInspectionPolicyRequest",
    "DeleteUrlListRequest",
    "DnsThreatDetector",
    "DnsThreatDetectorServiceClient",
    "FirewallActivationClient",
    "FirewallEndpoint",
    "FirewallEndpointAssociation",
    "GatewaySecurityPolicy",
    "GatewaySecurityPolicyRule",
    "GetAuthorizationPolicyRequest",
    "GetAuthzPolicyRequest",
    "GetBackendAuthenticationConfigRequest",
    "GetClientTlsPolicyRequest",
    "GetDnsThreatDetectorRequest",
    "GetFirewallEndpointAssociationRequest",
    "GetFirewallEndpointRequest",
    "GetGatewaySecurityPolicyRequest",
    "GetGatewaySecurityPolicyRuleRequest",
    "GetInterceptDeploymentGroupRequest",
    "GetInterceptDeploymentRequest",
    "GetInterceptEndpointGroupAssociationRequest",
    "GetInterceptEndpointGroupRequest",
    "GetMirroringDeploymentGroupRequest",
    "GetMirroringDeploymentRequest",
    "GetMirroringEndpointGroupAssociationRequest",
    "GetMirroringEndpointGroupRequest",
    "GetPartnerSSEGatewayRequest",
    "GetPartnerSSERealmRequest",
    "GetSACAttachmentRequest",
    "GetSACRealmRequest",
    "GetSSEGatewayReferenceRequest",
    "GetSecurityProfileGroupRequest",
    "GetSecurityProfileRequest",
    "GetServerTlsPolicyRequest",
    "GetTlsInspectionPolicyRequest",
    "GetUrlListRequest",
    "GrpcEndpoint",
    "InterceptClient",
    "InterceptDeployment",
    "InterceptDeploymentGroup",
    "InterceptEndpointGroup",
    "InterceptEndpointGroupAssociation",
    "InterceptLocation",
    "ListAuthorizationPoliciesRequest",
    "ListAuthorizationPoliciesResponse",
    "ListAuthzPoliciesRequest",
    "ListAuthzPoliciesResponse",
    "ListBackendAuthenticationConfigsRequest",
    "ListBackendAuthenticationConfigsResponse",
    "ListClientTlsPoliciesRequest",
    "ListClientTlsPoliciesResponse",
    "ListDnsThreatDetectorsRequest",
    "ListDnsThreatDetectorsResponse",
    "ListFirewallEndpointAssociationsRequest",
    "ListFirewallEndpointAssociationsResponse",
    "ListFirewallEndpointsRequest",
    "ListFirewallEndpointsResponse",
    "ListGatewaySecurityPoliciesRequest",
    "ListGatewaySecurityPoliciesResponse",
    "ListGatewaySecurityPolicyRulesRequest",
    "ListGatewaySecurityPolicyRulesResponse",
    "ListInterceptDeploymentGroupsRequest",
    "ListInterceptDeploymentGroupsResponse",
    "ListInterceptDeploymentsRequest",
    "ListInterceptDeploymentsResponse",
    "ListInterceptEndpointGroupAssociationsRequest",
    "ListInterceptEndpointGroupAssociationsResponse",
    "ListInterceptEndpointGroupsRequest",
    "ListInterceptEndpointGroupsResponse",
    "ListMirroringDeploymentGroupsRequest",
    "ListMirroringDeploymentGroupsResponse",
    "ListMirroringDeploymentsRequest",
    "ListMirroringDeploymentsResponse",
    "ListMirroringEndpointGroupAssociationsRequest",
    "ListMirroringEndpointGroupAssociationsResponse",
    "ListMirroringEndpointGroupsRequest",
    "ListMirroringEndpointGroupsResponse",
    "ListPartnerSSEGatewaysRequest",
    "ListPartnerSSEGatewaysResponse",
    "ListPartnerSSERealmsRequest",
    "ListPartnerSSERealmsResponse",
    "ListSACAttachmentsRequest",
    "ListSACAttachmentsResponse",
    "ListSACRealmsRequest",
    "ListSACRealmsResponse",
    "ListSSEGatewayReferencesRequest",
    "ListSSEGatewayReferencesResponse",
    "ListSecurityProfileGroupsRequest",
    "ListSecurityProfileGroupsResponse",
    "ListSecurityProfilesRequest",
    "ListSecurityProfilesResponse",
    "ListServerTlsPoliciesRequest",
    "ListServerTlsPoliciesResponse",
    "ListTlsInspectionPoliciesRequest",
    "ListTlsInspectionPoliciesResponse",
    "ListUrlListsRequest",
    "ListUrlListsResponse",
    "MirroringClient",
    "MirroringDeployment",
    "MirroringDeploymentGroup",
    "MirroringEndpointGroup",
    "MirroringEndpointGroupAssociation",
    "MirroringLocation",
    "NetworkSecurityClient",
    "OperationMetadata",
    "OrganizationSecurityProfileGroupServiceClient",
    "PartnerSSEGateway",
    "PartnerSSERealm",
    "Protocol",
    "SACAttachment",
    "SACRealm",
    "SSEGatewayReference",
    "SSEGatewayServiceClient",
    "SSERealmServiceClient",
    "SecurityProfile",
    "SecurityProfileGroup",
    "ServerTlsPolicy",
    "Severity",
    "SeverityOverride",
    "ThreatAction",
    "ThreatOverride",
    "ThreatPreventionProfile",
    "ThreatType",
    "TlsInspectionPolicy",
    "UpdateAuthorizationPolicyRequest",
    "UpdateAuthzPolicyRequest",
    "UpdateBackendAuthenticationConfigRequest",
    "UpdateClientTlsPolicyRequest",
    "UpdateDnsThreatDetectorRequest",
    "UpdateFirewallEndpointAssociationRequest",
    "UpdateFirewallEndpointRequest",
    "UpdateGatewaySecurityPolicyRequest",
    "UpdateGatewaySecurityPolicyRuleRequest",
    "UpdateInterceptDeploymentGroupRequest",
    "UpdateInterceptDeploymentRequest",
    "UpdateInterceptEndpointGroupAssociationRequest",
    "UpdateInterceptEndpointGroupRequest",
    "UpdateMirroringDeploymentGroupRequest",
    "UpdateMirroringDeploymentRequest",
    "UpdateMirroringEndpointGroupAssociationRequest",
    "UpdateMirroringEndpointGroupRequest",
    "UpdatePartnerSSEGatewayRequest",
    "UpdateSecurityProfileGroupRequest",
    "UpdateSecurityProfileRequest",
    "UpdateServerTlsPolicyRequest",
    "UpdateTlsInspectionPolicyRequest",
    "UpdateUrlListRequest",
    "UrlFilter",
    "UrlFilteringProfile",
    "UrlList",
    "ValidationCA",
)

api_core.check_python_version("google.cloud.network_security_v1alpha1")
api_core.check_dependency_versions("google.cloud.network_security_v1alpha1")
