# -*- coding: utf-8 -*-
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import sys

import google.api_core as api_core

from google.analytics.admin_v1alpha import gapic_version as package_version

__version__ = package_version.__version__

if sys.version_info >= (3, 8):  # pragma: NO COVER
    from importlib import metadata
else:  # pragma: NO COVER
    # TODO(https://github.com/googleapis/python-api-core/issues/835): Remove
    # this code path once we drop support for Python 3.7
    import importlib_metadata as metadata


from .services.analytics_admin_service import (
    AnalyticsAdminServiceAsyncClient,
    AnalyticsAdminServiceClient,
)
from .types.access_report import (
    AccessBetweenFilter,
    AccessDateRange,
    AccessDimension,
    AccessDimensionHeader,
    AccessDimensionValue,
    AccessFilter,
    AccessFilterExpression,
    AccessFilterExpressionList,
    AccessInListFilter,
    AccessMetric,
    AccessMetricHeader,
    AccessMetricValue,
    AccessNumericFilter,
    AccessOrderBy,
    AccessQuota,
    AccessQuotaStatus,
    AccessRow,
    AccessStringFilter,
    NumericValue,
)
from .types.analytics_admin import (
    AcknowledgeUserDataCollectionRequest,
    AcknowledgeUserDataCollectionResponse,
    ApproveDisplayVideo360AdvertiserLinkProposalRequest,
    ApproveDisplayVideo360AdvertiserLinkProposalResponse,
    ArchiveAudienceRequest,
    ArchiveCustomDimensionRequest,
    ArchiveCustomMetricRequest,
    BatchCreateAccessBindingsRequest,
    BatchCreateAccessBindingsResponse,
    BatchDeleteAccessBindingsRequest,
    BatchGetAccessBindingsRequest,
    BatchGetAccessBindingsResponse,
    BatchUpdateAccessBindingsRequest,
    BatchUpdateAccessBindingsResponse,
    CancelDisplayVideo360AdvertiserLinkProposalRequest,
    CreateAccessBindingRequest,
    CreateAdSenseLinkRequest,
    CreateAudienceRequest,
    CreateBigQueryLinkRequest,
    CreateCalculatedMetricRequest,
    CreateChannelGroupRequest,
    CreateConversionEventRequest,
    CreateCustomDimensionRequest,
    CreateCustomMetricRequest,
    CreateDataStreamRequest,
    CreateDisplayVideo360AdvertiserLinkProposalRequest,
    CreateDisplayVideo360AdvertiserLinkRequest,
    CreateEventCreateRuleRequest,
    CreateEventEditRuleRequest,
    CreateExpandedDataSetRequest,
    CreateFirebaseLinkRequest,
    CreateGoogleAdsLinkRequest,
    CreateKeyEventRequest,
    CreateMeasurementProtocolSecretRequest,
    CreatePropertyRequest,
    CreateReportingDataAnnotationRequest,
    CreateRollupPropertyRequest,
    CreateRollupPropertyResponse,
    CreateRollupPropertySourceLinkRequest,
    CreateSearchAds360LinkRequest,
    CreateSKAdNetworkConversionValueSchemaRequest,
    CreateSubpropertyEventFilterRequest,
    DeleteAccessBindingRequest,
    DeleteAccountRequest,
    DeleteAdSenseLinkRequest,
    DeleteBigQueryLinkRequest,
    DeleteCalculatedMetricRequest,
    DeleteChannelGroupRequest,
    DeleteConversionEventRequest,
    DeleteDataStreamRequest,
    DeleteDisplayVideo360AdvertiserLinkProposalRequest,
    DeleteDisplayVideo360AdvertiserLinkRequest,
    DeleteEventCreateRuleRequest,
    DeleteEventEditRuleRequest,
    DeleteExpandedDataSetRequest,
    DeleteFirebaseLinkRequest,
    DeleteGoogleAdsLinkRequest,
    DeleteKeyEventRequest,
    DeleteMeasurementProtocolSecretRequest,
    DeletePropertyRequest,
    DeleteReportingDataAnnotationRequest,
    DeleteRollupPropertySourceLinkRequest,
    DeleteSearchAds360LinkRequest,
    DeleteSKAdNetworkConversionValueSchemaRequest,
    DeleteSubpropertyEventFilterRequest,
    GetAccessBindingRequest,
    GetAccountRequest,
    GetAdSenseLinkRequest,
    GetAttributionSettingsRequest,
    GetAudienceRequest,
    GetBigQueryLinkRequest,
    GetCalculatedMetricRequest,
    GetChannelGroupRequest,
    GetConversionEventRequest,
    GetCustomDimensionRequest,
    GetCustomMetricRequest,
    GetDataRedactionSettingsRequest,
    GetDataRetentionSettingsRequest,
    GetDataSharingSettingsRequest,
    GetDataStreamRequest,
    GetDisplayVideo360AdvertiserLinkProposalRequest,
    GetDisplayVideo360AdvertiserLinkRequest,
    GetEnhancedMeasurementSettingsRequest,
    GetEventCreateRuleRequest,
    GetEventEditRuleRequest,
    GetExpandedDataSetRequest,
    GetGlobalSiteTagRequest,
    GetGoogleSignalsSettingsRequest,
    GetKeyEventRequest,
    GetMeasurementProtocolSecretRequest,
    GetPropertyRequest,
    GetReportingDataAnnotationRequest,
    GetReportingIdentitySettingsRequest,
    GetRollupPropertySourceLinkRequest,
    GetSearchAds360LinkRequest,
    GetSKAdNetworkConversionValueSchemaRequest,
    GetSubpropertyEventFilterRequest,
    GetSubpropertySyncConfigRequest,
    ListAccessBindingsRequest,
    ListAccessBindingsResponse,
    ListAccountsRequest,
    ListAccountsResponse,
    ListAccountSummariesRequest,
    ListAccountSummariesResponse,
    ListAdSenseLinksRequest,
    ListAdSenseLinksResponse,
    ListAudiencesRequest,
    ListAudiencesResponse,
    ListBigQueryLinksRequest,
    ListBigQueryLinksResponse,
    ListCalculatedMetricsRequest,
    ListCalculatedMetricsResponse,
    ListChannelGroupsRequest,
    ListChannelGroupsResponse,
    ListConversionEventsRequest,
    ListConversionEventsResponse,
    ListCustomDimensionsRequest,
    ListCustomDimensionsResponse,
    ListCustomMetricsRequest,
    ListCustomMetricsResponse,
    ListDataStreamsRequest,
    ListDataStreamsResponse,
    ListDisplayVideo360AdvertiserLinkProposalsRequest,
    ListDisplayVideo360AdvertiserLinkProposalsResponse,
    ListDisplayVideo360AdvertiserLinksRequest,
    ListDisplayVideo360AdvertiserLinksResponse,
    ListEventCreateRulesRequest,
    ListEventCreateRulesResponse,
    ListEventEditRulesRequest,
    ListEventEditRulesResponse,
    ListExpandedDataSetsRequest,
    ListExpandedDataSetsResponse,
    ListFirebaseLinksRequest,
    ListFirebaseLinksResponse,
    ListGoogleAdsLinksRequest,
    ListGoogleAdsLinksResponse,
    ListKeyEventsRequest,
    ListKeyEventsResponse,
    ListMeasurementProtocolSecretsRequest,
    ListMeasurementProtocolSecretsResponse,
    ListPropertiesRequest,
    ListPropertiesResponse,
    ListReportingDataAnnotationsRequest,
    ListReportingDataAnnotationsResponse,
    ListRollupPropertySourceLinksRequest,
    ListRollupPropertySourceLinksResponse,
    ListSearchAds360LinksRequest,
    ListSearchAds360LinksResponse,
    ListSKAdNetworkConversionValueSchemasRequest,
    ListSKAdNetworkConversionValueSchemasResponse,
    ListSubpropertyEventFiltersRequest,
    ListSubpropertyEventFiltersResponse,
    ListSubpropertySyncConfigsRequest,
    ListSubpropertySyncConfigsResponse,
    ProvisionAccountTicketRequest,
    ProvisionAccountTicketResponse,
    ProvisionSubpropertyRequest,
    ProvisionSubpropertyResponse,
    ReorderEventEditRulesRequest,
    RunAccessReportRequest,
    RunAccessReportResponse,
    SearchChangeHistoryEventsRequest,
    SearchChangeHistoryEventsResponse,
    SubmitUserDeletionRequest,
    SubmitUserDeletionResponse,
    UpdateAccessBindingRequest,
    UpdateAccountRequest,
    UpdateAttributionSettingsRequest,
    UpdateAudienceRequest,
    UpdateBigQueryLinkRequest,
    UpdateCalculatedMetricRequest,
    UpdateChannelGroupRequest,
    UpdateConversionEventRequest,
    UpdateCustomDimensionRequest,
    UpdateCustomMetricRequest,
    UpdateDataRedactionSettingsRequest,
    UpdateDataRetentionSettingsRequest,
    UpdateDataStreamRequest,
    UpdateDisplayVideo360AdvertiserLinkRequest,
    UpdateEnhancedMeasurementSettingsRequest,
    UpdateEventCreateRuleRequest,
    UpdateEventEditRuleRequest,
    UpdateExpandedDataSetRequest,
    UpdateGoogleAdsLinkRequest,
    UpdateGoogleSignalsSettingsRequest,
    UpdateKeyEventRequest,
    UpdateMeasurementProtocolSecretRequest,
    UpdatePropertyRequest,
    UpdateReportingDataAnnotationRequest,
    UpdateSearchAds360LinkRequest,
    UpdateSKAdNetworkConversionValueSchemaRequest,
    UpdateSubpropertyEventFilterRequest,
    UpdateSubpropertySyncConfigRequest,
)
from .types.audience import (
    Audience,
    AudienceDimensionOrMetricFilter,
    AudienceEventFilter,
    AudienceEventTrigger,
    AudienceFilterClause,
    AudienceFilterExpression,
    AudienceFilterExpressionList,
    AudienceFilterScope,
    AudienceSequenceFilter,
    AudienceSimpleFilter,
)
from .types.channel_group import (
    ChannelGroup,
    ChannelGroupFilter,
    ChannelGroupFilterExpression,
    ChannelGroupFilterExpressionList,
    GroupingRule,
)
from .types.event_create_and_edit import (
    EventCreateRule,
    EventEditRule,
    MatchingCondition,
    ParameterMutation,
)
from .types.expanded_data_set import (
    ExpandedDataSet,
    ExpandedDataSetFilter,
    ExpandedDataSetFilterExpression,
    ExpandedDataSetFilterExpressionList,
)
from .types.resources import (
    AccessBinding,
    Account,
    AccountSummary,
    ActionType,
    ActorType,
    AdSenseLink,
    AttributionSettings,
    BigQueryLink,
    CalculatedMetric,
    ChangeHistoryChange,
    ChangeHistoryEvent,
    ChangeHistoryResourceType,
    CoarseValue,
    ConversionEvent,
    ConversionValues,
    CustomDimension,
    CustomMetric,
    DataRedactionSettings,
    DataRetentionSettings,
    DataSharingSettings,
    DataStream,
    DisplayVideo360AdvertiserLink,
    DisplayVideo360AdvertiserLinkProposal,
    EnhancedMeasurementSettings,
    EventMapping,
    FirebaseLink,
    GlobalSiteTag,
    GoogleAdsLink,
    GoogleSignalsConsent,
    GoogleSignalsSettings,
    GoogleSignalsState,
    IndustryCategory,
    KeyEvent,
    LinkProposalInitiatingProduct,
    LinkProposalState,
    LinkProposalStatusDetails,
    MeasurementProtocolSecret,
    PostbackWindow,
    Property,
    PropertySummary,
    PropertyType,
    ReportingDataAnnotation,
    ReportingIdentitySettings,
    RollupPropertySourceLink,
    SearchAds360Link,
    ServiceLevel,
    SKAdNetworkConversionValueSchema,
    SubpropertySyncConfig,
)
from .types.subproperty_event_filter import (
    SubpropertyEventFilter,
    SubpropertyEventFilterClause,
    SubpropertyEventFilterCondition,
    SubpropertyEventFilterExpression,
    SubpropertyEventFilterExpressionList,
)

if hasattr(api_core, "check_python_version") and hasattr(
    api_core, "check_dependency_versions"
):  # pragma: NO COVER
    api_core.check_python_version("google.analytics.admin_v1alpha")  # type: ignore
    api_core.check_dependency_versions("google.analytics.admin_v1alpha")  # type: ignore
else:  # pragma: NO COVER
    # An older version of api_core is installed which does not define the
    # functions above. We do equivalent checks manually.
    try:
        import sys
        import warnings

        _py_version_str = sys.version.split()[0]
        _package_label = "google.analytics.admin_v1alpha"
        if sys.version_info < (3, 9):
            warnings.warn(
                "You are using a non-supported Python version "
                + f"({_py_version_str}).  Google will not post any further "
                + f"updates to {_package_label} supporting this Python version. "
                + "Please upgrade to the latest Python version, or at "
                + f"least to Python 3.9, and then update {_package_label}.",
                FutureWarning,
            )
        if sys.version_info[:2] == (3, 9):
            warnings.warn(
                f"You are using a Python version ({_py_version_str}) "
                + f"which Google will stop supporting in {_package_label} in "
                + "January 2026. Please "
                + "upgrade to the latest Python version, or at "
                + "least to Python 3.10, before then, and "
                + f"then update {_package_label}.",
                FutureWarning,
            )

        def parse_version_to_tuple(version_string: str):
            """Safely converts a semantic version string to a comparable tuple of integers.
            Example: "4.25.8" -> (4, 25, 8)
            Ignores non-numeric parts and handles common version formats.
            Args:
                version_string: Version string in the format "x.y.z" or "x.y.z<suffix>"
            Returns:
                Tuple of integers for the parsed version string.
            """
            parts = []
            for part in version_string.split("."):
                try:
                    parts.append(int(part))
                except ValueError:
                    # If it's a non-numeric part (e.g., '1.0.0b1' -> 'b1'), stop here.
                    # This is a simplification compared to 'packaging.parse_version', but sufficient
                    # for comparing strictly numeric semantic versions.
                    break
            return tuple(parts)

        def _get_version(dependency_name):
            try:
                version_string: str = metadata.version(dependency_name)
                parsed_version = parse_version_to_tuple(version_string)
                return (parsed_version, version_string)
            except Exception:
                # Catch exceptions from metadata.version() (e.g., PackageNotFoundError)
                # or errors during parse_version_to_tuple
                return (None, "--")

        _dependency_package = "google.protobuf"
        _next_supported_version = "4.25.8"
        _next_supported_version_tuple = (4, 25, 8)
        _recommendation = " (we recommend 6.x)"
        (_version_used, _version_used_string) = _get_version(_dependency_package)
        if _version_used and _version_used < _next_supported_version_tuple:
            warnings.warn(
                f"Package {_package_label} depends on "
                + f"{_dependency_package}, currently installed at version "
                + f"{_version_used_string}. Future updates to "
                + f"{_package_label} will require {_dependency_package} at "
                + f"version {_next_supported_version} or higher{_recommendation}."
                + " Please ensure "
                + "that either (a) your Python environment doesn't pin the "
                + f"version of {_dependency_package}, so that updates to "
                + f"{_package_label} can require the higher version, or "
                + "(b) you manually update your Python environment to use at "
                + f"least version {_next_supported_version} of "
                + f"{_dependency_package}.",
                FutureWarning,
            )
    except Exception:
        warnings.warn(
            "Could not determine the version of Python "
            + "currently being used. To continue receiving "
            + "updates for {_package_label}, ensure you are "
            + "using a supported version of Python; see "
            + "https://devguide.python.org/versions/"
        )

__all__ = (
    "AnalyticsAdminServiceAsyncClient",
    "AccessBetweenFilter",
    "AccessBinding",
    "AccessDateRange",
    "AccessDimension",
    "AccessDimensionHeader",
    "AccessDimensionValue",
    "AccessFilter",
    "AccessFilterExpression",
    "AccessFilterExpressionList",
    "AccessInListFilter",
    "AccessMetric",
    "AccessMetricHeader",
    "AccessMetricValue",
    "AccessNumericFilter",
    "AccessOrderBy",
    "AccessQuota",
    "AccessQuotaStatus",
    "AccessRow",
    "AccessStringFilter",
    "Account",
    "AccountSummary",
    "AcknowledgeUserDataCollectionRequest",
    "AcknowledgeUserDataCollectionResponse",
    "ActionType",
    "ActorType",
    "AdSenseLink",
    "AnalyticsAdminServiceClient",
    "ApproveDisplayVideo360AdvertiserLinkProposalRequest",
    "ApproveDisplayVideo360AdvertiserLinkProposalResponse",
    "ArchiveAudienceRequest",
    "ArchiveCustomDimensionRequest",
    "ArchiveCustomMetricRequest",
    "AttributionSettings",
    "Audience",
    "AudienceDimensionOrMetricFilter",
    "AudienceEventFilter",
    "AudienceEventTrigger",
    "AudienceFilterClause",
    "AudienceFilterExpression",
    "AudienceFilterExpressionList",
    "AudienceFilterScope",
    "AudienceSequenceFilter",
    "AudienceSimpleFilter",
    "BatchCreateAccessBindingsRequest",
    "BatchCreateAccessBindingsResponse",
    "BatchDeleteAccessBindingsRequest",
    "BatchGetAccessBindingsRequest",
    "BatchGetAccessBindingsResponse",
    "BatchUpdateAccessBindingsRequest",
    "BatchUpdateAccessBindingsResponse",
    "BigQueryLink",
    "CalculatedMetric",
    "CancelDisplayVideo360AdvertiserLinkProposalRequest",
    "ChangeHistoryChange",
    "ChangeHistoryEvent",
    "ChangeHistoryResourceType",
    "ChannelGroup",
    "ChannelGroupFilter",
    "ChannelGroupFilterExpression",
    "ChannelGroupFilterExpressionList",
    "CoarseValue",
    "ConversionEvent",
    "ConversionValues",
    "CreateAccessBindingRequest",
    "CreateAdSenseLinkRequest",
    "CreateAudienceRequest",
    "CreateBigQueryLinkRequest",
    "CreateCalculatedMetricRequest",
    "CreateChannelGroupRequest",
    "CreateConversionEventRequest",
    "CreateCustomDimensionRequest",
    "CreateCustomMetricRequest",
    "CreateDataStreamRequest",
    "CreateDisplayVideo360AdvertiserLinkProposalRequest",
    "CreateDisplayVideo360AdvertiserLinkRequest",
    "CreateEventCreateRuleRequest",
    "CreateEventEditRuleRequest",
    "CreateExpandedDataSetRequest",
    "CreateFirebaseLinkRequest",
    "CreateGoogleAdsLinkRequest",
    "CreateKeyEventRequest",
    "CreateMeasurementProtocolSecretRequest",
    "CreatePropertyRequest",
    "CreateReportingDataAnnotationRequest",
    "CreateRollupPropertyRequest",
    "CreateRollupPropertyResponse",
    "CreateRollupPropertySourceLinkRequest",
    "CreateSKAdNetworkConversionValueSchemaRequest",
    "CreateSearchAds360LinkRequest",
    "CreateSubpropertyEventFilterRequest",
    "CustomDimension",
    "CustomMetric",
    "DataRedactionSettings",
    "DataRetentionSettings",
    "DataSharingSettings",
    "DataStream",
    "DeleteAccessBindingRequest",
    "DeleteAccountRequest",
    "DeleteAdSenseLinkRequest",
    "DeleteBigQueryLinkRequest",
    "DeleteCalculatedMetricRequest",
    "DeleteChannelGroupRequest",
    "DeleteConversionEventRequest",
    "DeleteDataStreamRequest",
    "DeleteDisplayVideo360AdvertiserLinkProposalRequest",
    "DeleteDisplayVideo360AdvertiserLinkRequest",
    "DeleteEventCreateRuleRequest",
    "DeleteEventEditRuleRequest",
    "DeleteExpandedDataSetRequest",
    "DeleteFirebaseLinkRequest",
    "DeleteGoogleAdsLinkRequest",
    "DeleteKeyEventRequest",
    "DeleteMeasurementProtocolSecretRequest",
    "DeletePropertyRequest",
    "DeleteReportingDataAnnotationRequest",
    "DeleteRollupPropertySourceLinkRequest",
    "DeleteSKAdNetworkConversionValueSchemaRequest",
    "DeleteSearchAds360LinkRequest",
    "DeleteSubpropertyEventFilterRequest",
    "DisplayVideo360AdvertiserLink",
    "DisplayVideo360AdvertiserLinkProposal",
    "EnhancedMeasurementSettings",
    "EventCreateRule",
    "EventEditRule",
    "EventMapping",
    "ExpandedDataSet",
    "ExpandedDataSetFilter",
    "ExpandedDataSetFilterExpression",
    "ExpandedDataSetFilterExpressionList",
    "FirebaseLink",
    "GetAccessBindingRequest",
    "GetAccountRequest",
    "GetAdSenseLinkRequest",
    "GetAttributionSettingsRequest",
    "GetAudienceRequest",
    "GetBigQueryLinkRequest",
    "GetCalculatedMetricRequest",
    "GetChannelGroupRequest",
    "GetConversionEventRequest",
    "GetCustomDimensionRequest",
    "GetCustomMetricRequest",
    "GetDataRedactionSettingsRequest",
    "GetDataRetentionSettingsRequest",
    "GetDataSharingSettingsRequest",
    "GetDataStreamRequest",
    "GetDisplayVideo360AdvertiserLinkProposalRequest",
    "GetDisplayVideo360AdvertiserLinkRequest",
    "GetEnhancedMeasurementSettingsRequest",
    "GetEventCreateRuleRequest",
    "GetEventEditRuleRequest",
    "GetExpandedDataSetRequest",
    "GetGlobalSiteTagRequest",
    "GetGoogleSignalsSettingsRequest",
    "GetKeyEventRequest",
    "GetMeasurementProtocolSecretRequest",
    "GetPropertyRequest",
    "GetReportingDataAnnotationRequest",
    "GetReportingIdentitySettingsRequest",
    "GetRollupPropertySourceLinkRequest",
    "GetSKAdNetworkConversionValueSchemaRequest",
    "GetSearchAds360LinkRequest",
    "GetSubpropertyEventFilterRequest",
    "GetSubpropertySyncConfigRequest",
    "GlobalSiteTag",
    "GoogleAdsLink",
    "GoogleSignalsConsent",
    "GoogleSignalsSettings",
    "GoogleSignalsState",
    "GroupingRule",
    "IndustryCategory",
    "KeyEvent",
    "LinkProposalInitiatingProduct",
    "LinkProposalState",
    "LinkProposalStatusDetails",
    "ListAccessBindingsRequest",
    "ListAccessBindingsResponse",
    "ListAccountSummariesRequest",
    "ListAccountSummariesResponse",
    "ListAccountsRequest",
    "ListAccountsResponse",
    "ListAdSenseLinksRequest",
    "ListAdSenseLinksResponse",
    "ListAudiencesRequest",
    "ListAudiencesResponse",
    "ListBigQueryLinksRequest",
    "ListBigQueryLinksResponse",
    "ListCalculatedMetricsRequest",
    "ListCalculatedMetricsResponse",
    "ListChannelGroupsRequest",
    "ListChannelGroupsResponse",
    "ListConversionEventsRequest",
    "ListConversionEventsResponse",
    "ListCustomDimensionsRequest",
    "ListCustomDimensionsResponse",
    "ListCustomMetricsRequest",
    "ListCustomMetricsResponse",
    "ListDataStreamsRequest",
    "ListDataStreamsResponse",
    "ListDisplayVideo360AdvertiserLinkProposalsRequest",
    "ListDisplayVideo360AdvertiserLinkProposalsResponse",
    "ListDisplayVideo360AdvertiserLinksRequest",
    "ListDisplayVideo360AdvertiserLinksResponse",
    "ListEventCreateRulesRequest",
    "ListEventCreateRulesResponse",
    "ListEventEditRulesRequest",
    "ListEventEditRulesResponse",
    "ListExpandedDataSetsRequest",
    "ListExpandedDataSetsResponse",
    "ListFirebaseLinksRequest",
    "ListFirebaseLinksResponse",
    "ListGoogleAdsLinksRequest",
    "ListGoogleAdsLinksResponse",
    "ListKeyEventsRequest",
    "ListKeyEventsResponse",
    "ListMeasurementProtocolSecretsRequest",
    "ListMeasurementProtocolSecretsResponse",
    "ListPropertiesRequest",
    "ListPropertiesResponse",
    "ListReportingDataAnnotationsRequest",
    "ListReportingDataAnnotationsResponse",
    "ListRollupPropertySourceLinksRequest",
    "ListRollupPropertySourceLinksResponse",
    "ListSKAdNetworkConversionValueSchemasRequest",
    "ListSKAdNetworkConversionValueSchemasResponse",
    "ListSearchAds360LinksRequest",
    "ListSearchAds360LinksResponse",
    "ListSubpropertyEventFiltersRequest",
    "ListSubpropertyEventFiltersResponse",
    "ListSubpropertySyncConfigsRequest",
    "ListSubpropertySyncConfigsResponse",
    "MatchingCondition",
    "MeasurementProtocolSecret",
    "NumericValue",
    "ParameterMutation",
    "PostbackWindow",
    "Property",
    "PropertySummary",
    "PropertyType",
    "ProvisionAccountTicketRequest",
    "ProvisionAccountTicketResponse",
    "ProvisionSubpropertyRequest",
    "ProvisionSubpropertyResponse",
    "ReorderEventEditRulesRequest",
    "ReportingDataAnnotation",
    "ReportingIdentitySettings",
    "RollupPropertySourceLink",
    "RunAccessReportRequest",
    "RunAccessReportResponse",
    "SKAdNetworkConversionValueSchema",
    "SearchAds360Link",
    "SearchChangeHistoryEventsRequest",
    "SearchChangeHistoryEventsResponse",
    "ServiceLevel",
    "SubmitUserDeletionRequest",
    "SubmitUserDeletionResponse",
    "SubpropertyEventFilter",
    "SubpropertyEventFilterClause",
    "SubpropertyEventFilterCondition",
    "SubpropertyEventFilterExpression",
    "SubpropertyEventFilterExpressionList",
    "SubpropertySyncConfig",
    "UpdateAccessBindingRequest",
    "UpdateAccountRequest",
    "UpdateAttributionSettingsRequest",
    "UpdateAudienceRequest",
    "UpdateBigQueryLinkRequest",
    "UpdateCalculatedMetricRequest",
    "UpdateChannelGroupRequest",
    "UpdateConversionEventRequest",
    "UpdateCustomDimensionRequest",
    "UpdateCustomMetricRequest",
    "UpdateDataRedactionSettingsRequest",
    "UpdateDataRetentionSettingsRequest",
    "UpdateDataStreamRequest",
    "UpdateDisplayVideo360AdvertiserLinkRequest",
    "UpdateEnhancedMeasurementSettingsRequest",
    "UpdateEventCreateRuleRequest",
    "UpdateEventEditRuleRequest",
    "UpdateExpandedDataSetRequest",
    "UpdateGoogleAdsLinkRequest",
    "UpdateGoogleSignalsSettingsRequest",
    "UpdateKeyEventRequest",
    "UpdateMeasurementProtocolSecretRequest",
    "UpdatePropertyRequest",
    "UpdateReportingDataAnnotationRequest",
    "UpdateSKAdNetworkConversionValueSchemaRequest",
    "UpdateSearchAds360LinkRequest",
    "UpdateSubpropertyEventFilterRequest",
    "UpdateSubpropertySyncConfigRequest",
)
