# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
  - /owl-bot-staging

deep-copy-regex:
  - source: /google/cloud/audit/(audit-py)/(.*audit.*)
    dest: /owl-bot-staging/google-cloud-audit-log/$1/google/cloud/audit/$2
  
begin-after-commit-hash: 7af2cb8b2b725641ac0d07e2f256d453682802e6

