description: Search rules for identifying dependency versions
rules:
  - name: explicit_version_string
    description: Finds explicit version strings in code or configs.
    examples:
      - "'3.7'"
      - '"3.7.1"'
      - "'3.7.12'"
      - "Python 3.7"
    rules:
      - |
        \b{major}\.{minor}(\.\d+)?\b

  - name: python_requires
    description: Finds various forms of python_requires declarations.
    applies_to: [python]
    examples:
      - "python_requires = '==3.7'"
      - "python_requires = '>=3.7'"
      - "python_requires = '<=3.7'"
      - "python_requires = '>3.6'"
      - "python_requires = '<3.8'"
    rules:
      - |
        python_requires\s*=\s*['"]==3\.{minor}['"]
      - |
        python_requires\s*=\s*['"]>=3\.{minor}['"]
      - |
        python_requires\s*=\s*['"]<=3\.{minor}['"]
      - |
        python_requires\s*=\s*['"]>3\.{minor_minus_one}['"]
      - |
        python_requires\s*=\s*['"]<3\.{minor_plus_one}['"]

  - name: sys_version_info
    description: Finds sys.version_info checks in code.
    applies_to: [python]
    examples:
      - "sys.version_info == (3, 7)"
      - "sys.version_info >= (3, 7)"
      - "sys.version_info <= (3, 7)"
      - "sys.version_info > (3, 6)"
      - "sys.version_info < (3, 8)"
      - "sys.version_info.minor == 7"
      - "sys.version_info.minor >= 7"
      - "sys.version_info.minor <= 7"
      - "sys.version_info.minor > 6"
      - "sys.version_info.minor < 8"
    rules:
      - |
        sys\.version_info\s*==\s*\(3,\s*{minor}\)
      - |
        sys\.version_info\s*>=\s*\(3,\s*{minor}\)
      - |
        sys\.version_info\s*<=\s*\(3,\s*{minor}\)
      - |
        sys\.version_info\s*>\s*\(3,\s*{minor_minus_one}\)
      - |
        sys\.version_info\s*<\s*\(3,\s*{minor_plus_one}\)
      - |
        sys\.version_info\.minor\s*==\s*{minor}
      - |
        sys\.version_info\.minor\s*>=\s*{minor}
      - |
        sys\.version_info\.minor\s*<=\s*{minor}
      - |
        sys\.version_info\.minor\s*>\s*{minor_minus_one}
      - |
        sys\.version_info\.minor\s*<\s*{minor_plus_one}

  - name: python_env_short
    description: Finds short python environment names often used in tox or nox.
    applies_to: [python]
    examples:
      - "py37"
      - "py37-cover"
    rules:
      - |
        \bpy3{minor}\b

  - name: explicit_python_command
    description: Finds explicit python commands with version.
    applies_to: [python]
    examples:
      - "python3.7"
      - "python3.7 -m pip"
      - "Python3.7"
    rules:
      - |
        python3\.{minor}(?!\d)

  - name: combined_version_string
    description: Finds combined version strings often used in class or variable names.
    applies_to: [python]
    examples:
      - "Python37"
      - "Python37DeprecationWarning"
    rules:
      - |
        Python{major}{minor}(?!\d)


