# -*- coding: utf-8 -*-
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.network_security import gapic_version as package_version

__version__ = package_version.__version__


from google.cloud.network_security_v1.services.address_group_service.async_client import (
    AddressGroupServiceAsyncClient,
)
from google.cloud.network_security_v1.services.address_group_service.client import (
    AddressGroupServiceClient,
)
from google.cloud.network_security_v1.services.dns_threat_detector_service.async_client import (
    DnsThreatDetectorServiceAsyncClient,
)
from google.cloud.network_security_v1.services.dns_threat_detector_service.client import (
    DnsThreatDetectorServiceClient,
)
from google.cloud.network_security_v1.services.firewall_activation.async_client import (
    FirewallActivationAsyncClient,
)
from google.cloud.network_security_v1.services.firewall_activation.client import (
    FirewallActivationClient,
)
from google.cloud.network_security_v1.services.intercept.async_client import (
    InterceptAsyncClient,
)
from google.cloud.network_security_v1.services.intercept.client import InterceptClient
from google.cloud.network_security_v1.services.mirroring.async_client import (
    MirroringAsyncClient,
)
from google.cloud.network_security_v1.services.mirroring.client import MirroringClient
from google.cloud.network_security_v1.services.network_security.async_client import (
    NetworkSecurityAsyncClient,
)
from google.cloud.network_security_v1.services.network_security.client import (
    NetworkSecurityClient,
)
from google.cloud.network_security_v1.services.organization_address_group_service.async_client import (
    OrganizationAddressGroupServiceAsyncClient,
)
from google.cloud.network_security_v1.services.organization_address_group_service.client import (
    OrganizationAddressGroupServiceClient,
)
from google.cloud.network_security_v1.services.organization_security_profile_group_service.async_client import (
    OrganizationSecurityProfileGroupServiceAsyncClient,
)
from google.cloud.network_security_v1.services.organization_security_profile_group_service.client import (
    OrganizationSecurityProfileGroupServiceClient,
)
from google.cloud.network_security_v1.types.address_group import (
    AddAddressGroupItemsRequest,
    AddressGroup,
    CloneAddressGroupItemsRequest,
    CreateAddressGroupRequest,
    DeleteAddressGroupRequest,
    GetAddressGroupRequest,
    ListAddressGroupReferencesRequest,
    ListAddressGroupReferencesResponse,
    ListAddressGroupsRequest,
    ListAddressGroupsResponse,
    RemoveAddressGroupItemsRequest,
    UpdateAddressGroupRequest,
)
from google.cloud.network_security_v1.types.authorization_policy import (
    AuthorizationPolicy,
    CreateAuthorizationPolicyRequest,
    DeleteAuthorizationPolicyRequest,
    GetAuthorizationPolicyRequest,
    ListAuthorizationPoliciesRequest,
    ListAuthorizationPoliciesResponse,
    UpdateAuthorizationPolicyRequest,
)
from google.cloud.network_security_v1.types.authz_policy import (
    AuthzPolicy,
    CreateAuthzPolicyRequest,
    DeleteAuthzPolicyRequest,
    GetAuthzPolicyRequest,
    ListAuthzPoliciesRequest,
    ListAuthzPoliciesResponse,
    UpdateAuthzPolicyRequest,
)
from google.cloud.network_security_v1.types.backend_authentication_config import (
    BackendAuthenticationConfig,
    CreateBackendAuthenticationConfigRequest,
    DeleteBackendAuthenticationConfigRequest,
    GetBackendAuthenticationConfigRequest,
    ListBackendAuthenticationConfigsRequest,
    ListBackendAuthenticationConfigsResponse,
    UpdateBackendAuthenticationConfigRequest,
)
from google.cloud.network_security_v1.types.client_tls_policy import (
    ClientTlsPolicy,
    CreateClientTlsPolicyRequest,
    DeleteClientTlsPolicyRequest,
    GetClientTlsPolicyRequest,
    ListClientTlsPoliciesRequest,
    ListClientTlsPoliciesResponse,
    UpdateClientTlsPolicyRequest,
)
from google.cloud.network_security_v1.types.common import OperationMetadata
from google.cloud.network_security_v1.types.dns_threat_detector import (
    CreateDnsThreatDetectorRequest,
    DeleteDnsThreatDetectorRequest,
    DnsThreatDetector,
    GetDnsThreatDetectorRequest,
    ListDnsThreatDetectorsRequest,
    ListDnsThreatDetectorsResponse,
    UpdateDnsThreatDetectorRequest,
)
from google.cloud.network_security_v1.types.firewall_activation import (
    CreateFirewallEndpointAssociationRequest,
    CreateFirewallEndpointRequest,
    DeleteFirewallEndpointAssociationRequest,
    DeleteFirewallEndpointRequest,
    FirewallEndpoint,
    FirewallEndpointAssociation,
    GetFirewallEndpointAssociationRequest,
    GetFirewallEndpointRequest,
    ListFirewallEndpointAssociationsRequest,
    ListFirewallEndpointAssociationsResponse,
    ListFirewallEndpointsRequest,
    ListFirewallEndpointsResponse,
    UpdateFirewallEndpointAssociationRequest,
    UpdateFirewallEndpointRequest,
)
from google.cloud.network_security_v1.types.gateway_security_policy import (
    CreateGatewaySecurityPolicyRequest,
    DeleteGatewaySecurityPolicyRequest,
    GatewaySecurityPolicy,
    GetGatewaySecurityPolicyRequest,
    ListGatewaySecurityPoliciesRequest,
    ListGatewaySecurityPoliciesResponse,
    UpdateGatewaySecurityPolicyRequest,
)
from google.cloud.network_security_v1.types.gateway_security_policy_rule import (
    CreateGatewaySecurityPolicyRuleRequest,
    DeleteGatewaySecurityPolicyRuleRequest,
    GatewaySecurityPolicyRule,
    GetGatewaySecurityPolicyRuleRequest,
    ListGatewaySecurityPolicyRulesRequest,
    ListGatewaySecurityPolicyRulesResponse,
    UpdateGatewaySecurityPolicyRuleRequest,
)
from google.cloud.network_security_v1.types.intercept import (
    CreateInterceptDeploymentGroupRequest,
    CreateInterceptDeploymentRequest,
    CreateInterceptEndpointGroupAssociationRequest,
    CreateInterceptEndpointGroupRequest,
    DeleteInterceptDeploymentGroupRequest,
    DeleteInterceptDeploymentRequest,
    DeleteInterceptEndpointGroupAssociationRequest,
    DeleteInterceptEndpointGroupRequest,
    GetInterceptDeploymentGroupRequest,
    GetInterceptDeploymentRequest,
    GetInterceptEndpointGroupAssociationRequest,
    GetInterceptEndpointGroupRequest,
    InterceptDeployment,
    InterceptDeploymentGroup,
    InterceptEndpointGroup,
    InterceptEndpointGroupAssociation,
    InterceptLocation,
    ListInterceptDeploymentGroupsRequest,
    ListInterceptDeploymentGroupsResponse,
    ListInterceptDeploymentsRequest,
    ListInterceptDeploymentsResponse,
    ListInterceptEndpointGroupAssociationsRequest,
    ListInterceptEndpointGroupAssociationsResponse,
    ListInterceptEndpointGroupsRequest,
    ListInterceptEndpointGroupsResponse,
    UpdateInterceptDeploymentGroupRequest,
    UpdateInterceptDeploymentRequest,
    UpdateInterceptEndpointGroupAssociationRequest,
    UpdateInterceptEndpointGroupRequest,
)
from google.cloud.network_security_v1.types.mirroring import (
    CreateMirroringDeploymentGroupRequest,
    CreateMirroringDeploymentRequest,
    CreateMirroringEndpointGroupAssociationRequest,
    CreateMirroringEndpointGroupRequest,
    DeleteMirroringDeploymentGroupRequest,
    DeleteMirroringDeploymentRequest,
    DeleteMirroringEndpointGroupAssociationRequest,
    DeleteMirroringEndpointGroupRequest,
    GetMirroringDeploymentGroupRequest,
    GetMirroringDeploymentRequest,
    GetMirroringEndpointGroupAssociationRequest,
    GetMirroringEndpointGroupRequest,
    ListMirroringDeploymentGroupsRequest,
    ListMirroringDeploymentGroupsResponse,
    ListMirroringDeploymentsRequest,
    ListMirroringDeploymentsResponse,
    ListMirroringEndpointGroupAssociationsRequest,
    ListMirroringEndpointGroupAssociationsResponse,
    ListMirroringEndpointGroupsRequest,
    ListMirroringEndpointGroupsResponse,
    MirroringDeployment,
    MirroringDeploymentGroup,
    MirroringEndpointGroup,
    MirroringEndpointGroupAssociation,
    MirroringLocation,
    UpdateMirroringDeploymentGroupRequest,
    UpdateMirroringDeploymentRequest,
    UpdateMirroringEndpointGroupAssociationRequest,
    UpdateMirroringEndpointGroupRequest,
)
from google.cloud.network_security_v1.types.security_profile_group import (
    SecurityProfile,
    SecurityProfileGroup,
)
from google.cloud.network_security_v1.types.security_profile_group_intercept import (
    CustomInterceptProfile,
)
from google.cloud.network_security_v1.types.security_profile_group_mirroring import (
    CustomMirroringProfile,
)
from google.cloud.network_security_v1.types.security_profile_group_service import (
    CreateSecurityProfileGroupRequest,
    CreateSecurityProfileRequest,
    DeleteSecurityProfileGroupRequest,
    DeleteSecurityProfileRequest,
    GetSecurityProfileGroupRequest,
    GetSecurityProfileRequest,
    ListSecurityProfileGroupsRequest,
    ListSecurityProfileGroupsResponse,
    ListSecurityProfilesRequest,
    ListSecurityProfilesResponse,
    UpdateSecurityProfileGroupRequest,
    UpdateSecurityProfileRequest,
)
from google.cloud.network_security_v1.types.security_profile_group_threatprevention import (
    AntivirusOverride,
    Protocol,
    Severity,
    SeverityOverride,
    ThreatAction,
    ThreatOverride,
    ThreatPreventionProfile,
    ThreatType,
)
from google.cloud.network_security_v1.types.security_profile_group_urlfiltering import (
    UrlFilter,
    UrlFilteringProfile,
)
from google.cloud.network_security_v1.types.server_tls_policy import (
    CreateServerTlsPolicyRequest,
    DeleteServerTlsPolicyRequest,
    GetServerTlsPolicyRequest,
    ListServerTlsPoliciesRequest,
    ListServerTlsPoliciesResponse,
    ServerTlsPolicy,
    UpdateServerTlsPolicyRequest,
)
from google.cloud.network_security_v1.types.tls import (
    CertificateProvider,
    CertificateProviderInstance,
    GrpcEndpoint,
    ValidationCA,
)
from google.cloud.network_security_v1.types.tls_inspection_policy import (
    CreateTlsInspectionPolicyRequest,
    DeleteTlsInspectionPolicyRequest,
    GetTlsInspectionPolicyRequest,
    ListTlsInspectionPoliciesRequest,
    ListTlsInspectionPoliciesResponse,
    TlsInspectionPolicy,
    UpdateTlsInspectionPolicyRequest,
)
from google.cloud.network_security_v1.types.url_list import (
    CreateUrlListRequest,
    DeleteUrlListRequest,
    GetUrlListRequest,
    ListUrlListsRequest,
    ListUrlListsResponse,
    UpdateUrlListRequest,
    UrlList,
)

__all__ = (
    "AddressGroupServiceClient",
    "AddressGroupServiceAsyncClient",
    "DnsThreatDetectorServiceClient",
    "DnsThreatDetectorServiceAsyncClient",
    "FirewallActivationClient",
    "FirewallActivationAsyncClient",
    "InterceptClient",
    "InterceptAsyncClient",
    "MirroringClient",
    "MirroringAsyncClient",
    "NetworkSecurityClient",
    "NetworkSecurityAsyncClient",
    "OrganizationAddressGroupServiceClient",
    "OrganizationAddressGroupServiceAsyncClient",
    "OrganizationSecurityProfileGroupServiceClient",
    "OrganizationSecurityProfileGroupServiceAsyncClient",
    "AddAddressGroupItemsRequest",
    "AddressGroup",
    "CloneAddressGroupItemsRequest",
    "CreateAddressGroupRequest",
    "DeleteAddressGroupRequest",
    "GetAddressGroupRequest",
    "ListAddressGroupReferencesRequest",
    "ListAddressGroupReferencesResponse",
    "ListAddressGroupsRequest",
    "ListAddressGroupsResponse",
    "RemoveAddressGroupItemsRequest",
    "UpdateAddressGroupRequest",
    "AuthorizationPolicy",
    "CreateAuthorizationPolicyRequest",
    "DeleteAuthorizationPolicyRequest",
    "GetAuthorizationPolicyRequest",
    "ListAuthorizationPoliciesRequest",
    "ListAuthorizationPoliciesResponse",
    "UpdateAuthorizationPolicyRequest",
    "AuthzPolicy",
    "CreateAuthzPolicyRequest",
    "DeleteAuthzPolicyRequest",
    "GetAuthzPolicyRequest",
    "ListAuthzPoliciesRequest",
    "ListAuthzPoliciesResponse",
    "UpdateAuthzPolicyRequest",
    "BackendAuthenticationConfig",
    "CreateBackendAuthenticationConfigRequest",
    "DeleteBackendAuthenticationConfigRequest",
    "GetBackendAuthenticationConfigRequest",
    "ListBackendAuthenticationConfigsRequest",
    "ListBackendAuthenticationConfigsResponse",
    "UpdateBackendAuthenticationConfigRequest",
    "ClientTlsPolicy",
    "CreateClientTlsPolicyRequest",
    "DeleteClientTlsPolicyRequest",
    "GetClientTlsPolicyRequest",
    "ListClientTlsPoliciesRequest",
    "ListClientTlsPoliciesResponse",
    "UpdateClientTlsPolicyRequest",
    "OperationMetadata",
    "CreateDnsThreatDetectorRequest",
    "DeleteDnsThreatDetectorRequest",
    "DnsThreatDetector",
    "GetDnsThreatDetectorRequest",
    "ListDnsThreatDetectorsRequest",
    "ListDnsThreatDetectorsResponse",
    "UpdateDnsThreatDetectorRequest",
    "CreateFirewallEndpointAssociationRequest",
    "CreateFirewallEndpointRequest",
    "DeleteFirewallEndpointAssociationRequest",
    "DeleteFirewallEndpointRequest",
    "FirewallEndpoint",
    "FirewallEndpointAssociation",
    "GetFirewallEndpointAssociationRequest",
    "GetFirewallEndpointRequest",
    "ListFirewallEndpointAssociationsRequest",
    "ListFirewallEndpointAssociationsResponse",
    "ListFirewallEndpointsRequest",
    "ListFirewallEndpointsResponse",
    "UpdateFirewallEndpointAssociationRequest",
    "UpdateFirewallEndpointRequest",
    "CreateGatewaySecurityPolicyRequest",
    "DeleteGatewaySecurityPolicyRequest",
    "GatewaySecurityPolicy",
    "GetGatewaySecurityPolicyRequest",
    "ListGatewaySecurityPoliciesRequest",
    "ListGatewaySecurityPoliciesResponse",
    "UpdateGatewaySecurityPolicyRequest",
    "CreateGatewaySecurityPolicyRuleRequest",
    "DeleteGatewaySecurityPolicyRuleRequest",
    "GatewaySecurityPolicyRule",
    "GetGatewaySecurityPolicyRuleRequest",
    "ListGatewaySecurityPolicyRulesRequest",
    "ListGatewaySecurityPolicyRulesResponse",
    "UpdateGatewaySecurityPolicyRuleRequest",
    "CreateInterceptDeploymentGroupRequest",
    "CreateInterceptDeploymentRequest",
    "CreateInterceptEndpointGroupAssociationRequest",
    "CreateInterceptEndpointGroupRequest",
    "DeleteInterceptDeploymentGroupRequest",
    "DeleteInterceptDeploymentRequest",
    "DeleteInterceptEndpointGroupAssociationRequest",
    "DeleteInterceptEndpointGroupRequest",
    "GetInterceptDeploymentGroupRequest",
    "GetInterceptDeploymentRequest",
    "GetInterceptEndpointGroupAssociationRequest",
    "GetInterceptEndpointGroupRequest",
    "InterceptDeployment",
    "InterceptDeploymentGroup",
    "InterceptEndpointGroup",
    "InterceptEndpointGroupAssociation",
    "InterceptLocation",
    "ListInterceptDeploymentGroupsRequest",
    "ListInterceptDeploymentGroupsResponse",
    "ListInterceptDeploymentsRequest",
    "ListInterceptDeploymentsResponse",
    "ListInterceptEndpointGroupAssociationsRequest",
    "ListInterceptEndpointGroupAssociationsResponse",
    "ListInterceptEndpointGroupsRequest",
    "ListInterceptEndpointGroupsResponse",
    "UpdateInterceptDeploymentGroupRequest",
    "UpdateInterceptDeploymentRequest",
    "UpdateInterceptEndpointGroupAssociationRequest",
    "UpdateInterceptEndpointGroupRequest",
    "CreateMirroringDeploymentGroupRequest",
    "CreateMirroringDeploymentRequest",
    "CreateMirroringEndpointGroupAssociationRequest",
    "CreateMirroringEndpointGroupRequest",
    "DeleteMirroringDeploymentGroupRequest",
    "DeleteMirroringDeploymentRequest",
    "DeleteMirroringEndpointGroupAssociationRequest",
    "DeleteMirroringEndpointGroupRequest",
    "GetMirroringDeploymentGroupRequest",
    "GetMirroringDeploymentRequest",
    "GetMirroringEndpointGroupAssociationRequest",
    "GetMirroringEndpointGroupRequest",
    "ListMirroringDeploymentGroupsRequest",
    "ListMirroringDeploymentGroupsResponse",
    "ListMirroringDeploymentsRequest",
    "ListMirroringDeploymentsResponse",
    "ListMirroringEndpointGroupAssociationsRequest",
    "ListMirroringEndpointGroupAssociationsResponse",
    "ListMirroringEndpointGroupsRequest",
    "ListMirroringEndpointGroupsResponse",
    "MirroringDeployment",
    "MirroringDeploymentGroup",
    "MirroringEndpointGroup",
    "MirroringEndpointGroupAssociation",
    "MirroringLocation",
    "UpdateMirroringDeploymentGroupRequest",
    "UpdateMirroringDeploymentRequest",
    "UpdateMirroringEndpointGroupAssociationRequest",
    "UpdateMirroringEndpointGroupRequest",
    "SecurityProfile",
    "SecurityProfileGroup",
    "CustomInterceptProfile",
    "CustomMirroringProfile",
    "CreateSecurityProfileGroupRequest",
    "CreateSecurityProfileRequest",
    "DeleteSecurityProfileGroupRequest",
    "DeleteSecurityProfileRequest",
    "GetSecurityProfileGroupRequest",
    "GetSecurityProfileRequest",
    "ListSecurityProfileGroupsRequest",
    "ListSecurityProfileGroupsResponse",
    "ListSecurityProfilesRequest",
    "ListSecurityProfilesResponse",
    "UpdateSecurityProfileGroupRequest",
    "UpdateSecurityProfileRequest",
    "AntivirusOverride",
    "SeverityOverride",
    "ThreatOverride",
    "ThreatPreventionProfile",
    "Protocol",
    "Severity",
    "ThreatAction",
    "ThreatType",
    "UrlFilter",
    "UrlFilteringProfile",
    "CreateServerTlsPolicyRequest",
    "DeleteServerTlsPolicyRequest",
    "GetServerTlsPolicyRequest",
    "ListServerTlsPoliciesRequest",
    "ListServerTlsPoliciesResponse",
    "ServerTlsPolicy",
    "UpdateServerTlsPolicyRequest",
    "CertificateProvider",
    "CertificateProviderInstance",
    "GrpcEndpoint",
    "ValidationCA",
    "CreateTlsInspectionPolicyRequest",
    "DeleteTlsInspectionPolicyRequest",
    "GetTlsInspectionPolicyRequest",
    "ListTlsInspectionPoliciesRequest",
    "ListTlsInspectionPoliciesResponse",
    "TlsInspectionPolicy",
    "UpdateTlsInspectionPolicyRequest",
    "CreateUrlListRequest",
    "DeleteUrlListRequest",
    "GetUrlListRequest",
    "ListUrlListsRequest",
    "ListUrlListsResponse",
    "UpdateUrlListRequest",
    "UrlList",
)
