# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from google.cloud.sql import gapic_version as package_version

__version__ = package_version.__version__


from google.cloud.sql_v1.services.sql_available_database_versions_service.async_client import (
    SqlAvailableDatabaseVersionsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_available_database_versions_service.client import (
    SqlAvailableDatabaseVersionsServiceClient,
)
from google.cloud.sql_v1.services.sql_backup_runs_service.async_client import (
    SqlBackupRunsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_backup_runs_service.client import (
    SqlBackupRunsServiceClient,
)
from google.cloud.sql_v1.services.sql_backups_service.async_client import (
    SqlBackupsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_backups_service.client import (
    SqlBackupsServiceClient,
)
from google.cloud.sql_v1.services.sql_connect_service.async_client import (
    SqlConnectServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_connect_service.client import (
    SqlConnectServiceClient,
)
from google.cloud.sql_v1.services.sql_databases_service.async_client import (
    SqlDatabasesServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_databases_service.client import (
    SqlDatabasesServiceClient,
)
from google.cloud.sql_v1.services.sql_events_service.async_client import (
    SqlEventsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_events_service.client import (
    SqlEventsServiceClient,
)
from google.cloud.sql_v1.services.sql_feature_eligibility_service.async_client import (
    SqlFeatureEligibilityServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_feature_eligibility_service.client import (
    SqlFeatureEligibilityServiceClient,
)
from google.cloud.sql_v1.services.sql_flags_service.async_client import (
    SqlFlagsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_flags_service.client import SqlFlagsServiceClient
from google.cloud.sql_v1.services.sql_iam_policies_service.async_client import (
    SqlIamPoliciesServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_iam_policies_service.client import (
    SqlIamPoliciesServiceClient,
)
from google.cloud.sql_v1.services.sql_instance_names_service.async_client import (
    SqlInstanceNamesServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_instance_names_service.client import (
    SqlInstanceNamesServiceClient,
)
from google.cloud.sql_v1.services.sql_instances_service.async_client import (
    SqlInstancesServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_instances_service.client import (
    SqlInstancesServiceClient,
)
from google.cloud.sql_v1.services.sql_operations_service.async_client import (
    SqlOperationsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_operations_service.client import (
    SqlOperationsServiceClient,
)
from google.cloud.sql_v1.services.sql_regions_service.async_client import (
    SqlRegionsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_regions_service.client import (
    SqlRegionsServiceClient,
)
from google.cloud.sql_v1.services.sql_ssl_certs_service.async_client import (
    SqlSslCertsServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_ssl_certs_service.client import (
    SqlSslCertsServiceClient,
)
from google.cloud.sql_v1.services.sql_tiers_service.async_client import (
    SqlTiersServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_tiers_service.client import SqlTiersServiceClient
from google.cloud.sql_v1.services.sql_users_service.async_client import (
    SqlUsersServiceAsyncClient,
)
from google.cloud.sql_v1.services.sql_users_service.client import SqlUsersServiceClient
from google.cloud.sql_v1.types.cloud_sql_backup_runs import (
    BackupRun,
    BackupRunsListResponse,
    SqlBackupKind,
    SqlBackupRunsDeleteRequest,
    SqlBackupRunsGetRequest,
    SqlBackupRunsInsertRequest,
    SqlBackupRunsListRequest,
    SqlBackupRunStatus,
    SqlBackupRunType,
)
from google.cloud.sql_v1.types.cloud_sql_backups import (
    Backup,
    CreateBackupRequest,
    DeleteBackupRequest,
    GetBackupRequest,
    ListBackupsRequest,
    ListBackupsResponse,
    UpdateBackupRequest,
)
from google.cloud.sql_v1.types.cloud_sql_connect import (
    ConnectSettings,
    GenerateEphemeralCertRequest,
    GenerateEphemeralCertResponse,
    GetConnectSettingsRequest,
    ResolveConnectSettingsRequest,
)
from google.cloud.sql_v1.types.cloud_sql_databases import (
    DatabasesListResponse,
    SqlDatabasesDeleteRequest,
    SqlDatabasesGetRequest,
    SqlDatabasesInsertRequest,
    SqlDatabasesListRequest,
    SqlDatabasesUpdateRequest,
)
from google.cloud.sql_v1.types.cloud_sql_flags import (
    Flag,
    FlagsListResponse,
    SqlFlagScope,
    SqlFlagsListRequest,
    SqlFlagType,
)
from google.cloud.sql_v1.types.cloud_sql_instances import (
    AvailableDatabaseVersion,
    BackupReencryptionConfig,
    BinLogCoordinates,
    CloneContext,
    Column,
    DatabaseInstance,
    DemoteContext,
    DemoteMasterContext,
    ExecuteSqlPayload,
    ExternalSyncParallelLevel,
    ExternalSyncSelectedObject,
    FailoverContext,
    GeminiInstanceConfig,
    InstancesAcquireSsrsLeaseRequest,
    InstancesCloneRequest,
    InstancesDemoteMasterRequest,
    InstancesDemoteRequest,
    InstancesExportRequest,
    InstancesFailoverRequest,
    InstancesImportRequest,
    InstancesListEntraIdCertificatesResponse,
    InstancesListResponse,
    InstancesListServerCasResponse,
    InstancesListServerCertificatesResponse,
    InstancesPreCheckMajorVersionUpgradeRequest,
    InstancesReencryptRequest,
    InstancesRestoreBackupRequest,
    InstancesRotateEntraIdCertificateRequest,
    InstancesRotateServerCaRequest,
    InstancesRotateServerCertificateRequest,
    InstancesTruncateLogRequest,
    Metadata,
    OnPremisesConfiguration,
    PointInTimeRestoreContext,
    QueryResult,
    ReplicaConfiguration,
    ReplicationCluster,
    RestoreBackupContext,
    RotateEntraIdCertificateContext,
    RotateServerCaContext,
    RotateServerCertificateContext,
    Row,
    SelectedObjects,
    SqlExternalSyncSettingError,
    SqlInstancesAcquireSsrsLeaseRequest,
    SqlInstancesAcquireSsrsLeaseResponse,
    SqlInstancesAddEntraIdCertificateRequest,
    SqlInstancesAddServerCaRequest,
    SqlInstancesAddServerCertificateRequest,
    SqlInstancesCloneRequest,
    SqlInstancesCreateEphemeralCertRequest,
    SqlInstancesDeleteRequest,
    SqlInstancesDemoteMasterRequest,
    SqlInstancesDemoteRequest,
    SqlInstancesExecuteSqlRequest,
    SqlInstancesExecuteSqlResponse,
    SqlInstancesExportRequest,
    SqlInstancesFailoverRequest,
    SqlInstancesGetDiskShrinkConfigRequest,
    SqlInstancesGetDiskShrinkConfigResponse,
    SqlInstancesGetLatestRecoveryTimeRequest,
    SqlInstancesGetLatestRecoveryTimeResponse,
    SqlInstancesGetRequest,
    SqlInstancesImportRequest,
    SqlInstancesInsertRequest,
    SqlInstancesListEntraIdCertificatesRequest,
    SqlInstancesListRequest,
    SqlInstancesListServerCasRequest,
    SqlInstancesListServerCertificatesRequest,
    SqlInstancesPatchRequest,
    SqlInstancesPerformDiskShrinkRequest,
    SqlInstancesPointInTimeRestoreRequest,
    SqlInstancesPreCheckMajorVersionUpgradeRequest,
    SqlInstancesPromoteReplicaRequest,
    SqlInstancesReencryptRequest,
    SqlInstancesReleaseSsrsLeaseRequest,
    SqlInstancesReleaseSsrsLeaseResponse,
    SqlInstancesRescheduleMaintenanceRequest,
    SqlInstancesRescheduleMaintenanceRequestBody,
    SqlInstancesResetReplicaSizeRequest,
    SqlInstancesResetSslConfigRequest,
    SqlInstancesRestartRequest,
    SqlInstancesRestoreBackupRequest,
    SqlInstancesRotateEntraIdCertificateRequest,
    SqlInstancesRotateServerCaRequest,
    SqlInstancesRotateServerCertificateRequest,
    SqlInstancesStartExternalSyncRequest,
    SqlInstancesStartReplicaRequest,
    SqlInstancesStopReplicaRequest,
    SqlInstancesSwitchoverRequest,
    SqlInstancesTruncateLogRequest,
    SqlInstancesUpdateRequest,
    SqlInstancesVerifyExternalSyncSettingsRequest,
    SqlInstancesVerifyExternalSyncSettingsResponse,
    SqlInstanceType,
    SqlSuspensionReason,
    SslCertsCreateEphemeralRequest,
    TruncateLogContext,
    Value,
)
from google.cloud.sql_v1.types.cloud_sql_operations import (
    OperationsListResponse,
    SqlOperationsCancelRequest,
    SqlOperationsGetRequest,
    SqlOperationsListRequest,
)
from google.cloud.sql_v1.types.cloud_sql_resources import (
    AclEntry,
    AcquireSsrsLeaseContext,
    AdvancedMachineFeatures,
    ApiWarning,
    AutoDnsStatus,
    BackupConfiguration,
    BackupContext,
    BackupRetentionSettings,
    BakType,
    ConnectionPoolConfig,
    ConnectionPoolFlags,
    Database,
    DatabaseFlags,
    DataCacheConfig,
    DemoteMasterConfiguration,
    DemoteMasterMySqlReplicaConfiguration,
    DenyMaintenancePeriod,
    DiskEncryptionConfiguration,
    DiskEncryptionStatus,
    DnsNameMapping,
    ExportContext,
    FinalBackupConfig,
    ImportContext,
    InsightsConfig,
    InstanceReference,
    IpConfiguration,
    IpMapping,
    LocationPreference,
    MaintenanceWindow,
    MySqlReplicaConfiguration,
    MySqlSyncConfig,
    Operation,
    OperationError,
    OperationErrors,
    PasswordValidationPolicy,
    PerformanceCaptureConfig,
    PerformDiskShrinkContext,
    PreCheckMajorVersionUpgradeContext,
    PreCheckResponse,
    PscAutoConnectionConfig,
    PscConfig,
    ReadPoolAutoScaleConfig,
    Settings,
    SqlActiveDirectoryConfig,
    SqlAvailabilityType,
    SqlBackendType,
    SqlDatabaseVersion,
    SqlDataDiskType,
    SqlFileType,
    SqlIpAddressType,
    SqlMaintenanceType,
    SqlPricingPlan,
    SqlReplicationType,
    SqlServerAuditConfig,
    SqlServerDatabaseDetails,
    SqlServerEntraIdConfig,
    SqlSubOperationType,
    SqlUpdateTrack,
    SslCert,
    SslCertDetail,
    SyncFlags,
)
from google.cloud.sql_v1.types.cloud_sql_ssl_certs import (
    SqlSslCertsDeleteRequest,
    SqlSslCertsGetRequest,
    SqlSslCertsInsertRequest,
    SqlSslCertsListRequest,
    SslCertsInsertRequest,
    SslCertsInsertResponse,
    SslCertsListResponse,
)
from google.cloud.sql_v1.types.cloud_sql_tiers import (
    SqlTiersListRequest,
    Tier,
    TiersListResponse,
)
from google.cloud.sql_v1.types.cloud_sql_users import (
    PasswordStatus,
    SqlServerUserDetails,
    SqlUsersDeleteRequest,
    SqlUsersGetRequest,
    SqlUsersInsertRequest,
    SqlUsersListRequest,
    SqlUsersUpdateRequest,
    User,
    UserPasswordValidationPolicy,
    UsersListResponse,
)

__all__ = (
    "SqlAvailableDatabaseVersionsServiceClient",
    "SqlAvailableDatabaseVersionsServiceAsyncClient",
    "SqlBackupRunsServiceClient",
    "SqlBackupRunsServiceAsyncClient",
    "SqlBackupsServiceClient",
    "SqlBackupsServiceAsyncClient",
    "SqlConnectServiceClient",
    "SqlConnectServiceAsyncClient",
    "SqlDatabasesServiceClient",
    "SqlDatabasesServiceAsyncClient",
    "SqlEventsServiceClient",
    "SqlEventsServiceAsyncClient",
    "SqlFeatureEligibilityServiceClient",
    "SqlFeatureEligibilityServiceAsyncClient",
    "SqlFlagsServiceClient",
    "SqlFlagsServiceAsyncClient",
    "SqlIamPoliciesServiceClient",
    "SqlIamPoliciesServiceAsyncClient",
    "SqlInstanceNamesServiceClient",
    "SqlInstanceNamesServiceAsyncClient",
    "SqlInstancesServiceClient",
    "SqlInstancesServiceAsyncClient",
    "SqlOperationsServiceClient",
    "SqlOperationsServiceAsyncClient",
    "SqlRegionsServiceClient",
    "SqlRegionsServiceAsyncClient",
    "SqlSslCertsServiceClient",
    "SqlSslCertsServiceAsyncClient",
    "SqlTiersServiceClient",
    "SqlTiersServiceAsyncClient",
    "SqlUsersServiceClient",
    "SqlUsersServiceAsyncClient",
    "BackupRun",
    "BackupRunsListResponse",
    "SqlBackupRunsDeleteRequest",
    "SqlBackupRunsGetRequest",
    "SqlBackupRunsInsertRequest",
    "SqlBackupRunsListRequest",
    "SqlBackupKind",
    "SqlBackupRunStatus",
    "SqlBackupRunType",
    "Backup",
    "CreateBackupRequest",
    "DeleteBackupRequest",
    "GetBackupRequest",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "UpdateBackupRequest",
    "ConnectSettings",
    "GenerateEphemeralCertRequest",
    "GenerateEphemeralCertResponse",
    "GetConnectSettingsRequest",
    "ResolveConnectSettingsRequest",
    "DatabasesListResponse",
    "SqlDatabasesDeleteRequest",
    "SqlDatabasesGetRequest",
    "SqlDatabasesInsertRequest",
    "SqlDatabasesListRequest",
    "SqlDatabasesUpdateRequest",
    "Flag",
    "FlagsListResponse",
    "SqlFlagsListRequest",
    "SqlFlagScope",
    "SqlFlagType",
    "AvailableDatabaseVersion",
    "BackupReencryptionConfig",
    "BinLogCoordinates",
    "CloneContext",
    "Column",
    "DatabaseInstance",
    "DemoteContext",
    "DemoteMasterContext",
    "ExecuteSqlPayload",
    "ExternalSyncSelectedObject",
    "FailoverContext",
    "GeminiInstanceConfig",
    "InstancesAcquireSsrsLeaseRequest",
    "InstancesCloneRequest",
    "InstancesDemoteMasterRequest",
    "InstancesDemoteRequest",
    "InstancesExportRequest",
    "InstancesFailoverRequest",
    "InstancesImportRequest",
    "InstancesListEntraIdCertificatesResponse",
    "InstancesListResponse",
    "InstancesListServerCasResponse",
    "InstancesListServerCertificatesResponse",
    "InstancesPreCheckMajorVersionUpgradeRequest",
    "InstancesReencryptRequest",
    "InstancesRestoreBackupRequest",
    "InstancesRotateEntraIdCertificateRequest",
    "InstancesRotateServerCaRequest",
    "InstancesRotateServerCertificateRequest",
    "InstancesTruncateLogRequest",
    "Metadata",
    "OnPremisesConfiguration",
    "PointInTimeRestoreContext",
    "QueryResult",
    "ReplicaConfiguration",
    "ReplicationCluster",
    "RestoreBackupContext",
    "RotateEntraIdCertificateContext",
    "RotateServerCaContext",
    "RotateServerCertificateContext",
    "Row",
    "SelectedObjects",
    "SqlExternalSyncSettingError",
    "SqlInstancesAcquireSsrsLeaseRequest",
    "SqlInstancesAcquireSsrsLeaseResponse",
    "SqlInstancesAddEntraIdCertificateRequest",
    "SqlInstancesAddServerCaRequest",
    "SqlInstancesAddServerCertificateRequest",
    "SqlInstancesCloneRequest",
    "SqlInstancesCreateEphemeralCertRequest",
    "SqlInstancesDeleteRequest",
    "SqlInstancesDemoteMasterRequest",
    "SqlInstancesDemoteRequest",
    "SqlInstancesExecuteSqlRequest",
    "SqlInstancesExecuteSqlResponse",
    "SqlInstancesExportRequest",
    "SqlInstancesFailoverRequest",
    "SqlInstancesGetDiskShrinkConfigRequest",
    "SqlInstancesGetDiskShrinkConfigResponse",
    "SqlInstancesGetLatestRecoveryTimeRequest",
    "SqlInstancesGetLatestRecoveryTimeResponse",
    "SqlInstancesGetRequest",
    "SqlInstancesImportRequest",
    "SqlInstancesInsertRequest",
    "SqlInstancesListEntraIdCertificatesRequest",
    "SqlInstancesListRequest",
    "SqlInstancesListServerCasRequest",
    "SqlInstancesListServerCertificatesRequest",
    "SqlInstancesPatchRequest",
    "SqlInstancesPerformDiskShrinkRequest",
    "SqlInstancesPointInTimeRestoreRequest",
    "SqlInstancesPreCheckMajorVersionUpgradeRequest",
    "SqlInstancesPromoteReplicaRequest",
    "SqlInstancesReencryptRequest",
    "SqlInstancesReleaseSsrsLeaseRequest",
    "SqlInstancesReleaseSsrsLeaseResponse",
    "SqlInstancesRescheduleMaintenanceRequest",
    "SqlInstancesRescheduleMaintenanceRequestBody",
    "SqlInstancesResetReplicaSizeRequest",
    "SqlInstancesResetSslConfigRequest",
    "SqlInstancesRestartRequest",
    "SqlInstancesRestoreBackupRequest",
    "SqlInstancesRotateEntraIdCertificateRequest",
    "SqlInstancesRotateServerCaRequest",
    "SqlInstancesRotateServerCertificateRequest",
    "SqlInstancesStartExternalSyncRequest",
    "SqlInstancesStartReplicaRequest",
    "SqlInstancesStopReplicaRequest",
    "SqlInstancesSwitchoverRequest",
    "SqlInstancesTruncateLogRequest",
    "SqlInstancesUpdateRequest",
    "SqlInstancesVerifyExternalSyncSettingsRequest",
    "SqlInstancesVerifyExternalSyncSettingsResponse",
    "SslCertsCreateEphemeralRequest",
    "TruncateLogContext",
    "Value",
    "ExternalSyncParallelLevel",
    "SqlInstanceType",
    "SqlSuspensionReason",
    "OperationsListResponse",
    "SqlOperationsCancelRequest",
    "SqlOperationsGetRequest",
    "SqlOperationsListRequest",
    "AclEntry",
    "AcquireSsrsLeaseContext",
    "AdvancedMachineFeatures",
    "ApiWarning",
    "BackupConfiguration",
    "BackupContext",
    "BackupRetentionSettings",
    "ConnectionPoolConfig",
    "ConnectionPoolFlags",
    "Database",
    "DatabaseFlags",
    "DataCacheConfig",
    "DemoteMasterConfiguration",
    "DemoteMasterMySqlReplicaConfiguration",
    "DenyMaintenancePeriod",
    "DiskEncryptionConfiguration",
    "DiskEncryptionStatus",
    "DnsNameMapping",
    "ExportContext",
    "FinalBackupConfig",
    "ImportContext",
    "InsightsConfig",
    "InstanceReference",
    "IpConfiguration",
    "IpMapping",
    "LocationPreference",
    "MaintenanceWindow",
    "MySqlReplicaConfiguration",
    "MySqlSyncConfig",
    "Operation",
    "OperationError",
    "OperationErrors",
    "PasswordValidationPolicy",
    "PerformanceCaptureConfig",
    "PerformDiskShrinkContext",
    "PreCheckMajorVersionUpgradeContext",
    "PreCheckResponse",
    "PscAutoConnectionConfig",
    "PscConfig",
    "ReadPoolAutoScaleConfig",
    "Settings",
    "SqlActiveDirectoryConfig",
    "SqlServerAuditConfig",
    "SqlServerDatabaseDetails",
    "SqlServerEntraIdConfig",
    "SqlSubOperationType",
    "SslCert",
    "SslCertDetail",
    "SyncFlags",
    "AutoDnsStatus",
    "BakType",
    "SqlAvailabilityType",
    "SqlBackendType",
    "SqlDatabaseVersion",
    "SqlDataDiskType",
    "SqlFileType",
    "SqlIpAddressType",
    "SqlMaintenanceType",
    "SqlPricingPlan",
    "SqlReplicationType",
    "SqlUpdateTrack",
    "SqlSslCertsDeleteRequest",
    "SqlSslCertsGetRequest",
    "SqlSslCertsInsertRequest",
    "SqlSslCertsListRequest",
    "SslCertsInsertRequest",
    "SslCertsInsertResponse",
    "SslCertsListResponse",
    "SqlTiersListRequest",
    "Tier",
    "TiersListResponse",
    "PasswordStatus",
    "SqlServerUserDetails",
    "SqlUsersDeleteRequest",
    "SqlUsersGetRequest",
    "SqlUsersInsertRequest",
    "SqlUsersListRequest",
    "SqlUsersUpdateRequest",
    "User",
    "UserPasswordValidationPolicy",
    "UsersListResponse",
)
