permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'packages/django-google-spanner/**'
      - '.github/workflows/django-spanner-foreign_keys.yaml'
  push:
    branches:
      - main
    paths:
      - 'packages/django-google-spanner/**'
      - '.github/workflows/django-spanner-foreign_keys.yaml'

defaults:
  run:
    working-directory: packages/django-google-spanner

name: foreign-keys-test
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      run_django_spanner: ${{ steps.filter.outputs.django_spanner }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            django_spanner:
              - 'packages/django-google-spanner/**'
              - '.github/workflows/django-spanner-foreign_keys.yaml'

  system-tests:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.run_django_spanner == 'true' }}
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest # zizmor: ignore[unpinned-images]
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.10"
      - name: Run Django foreign key test
        run: sh foreign_key_test.sh
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: emulator-test-project
          GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE: true
          SPANNER_TEST_INSTANCE: google-cloud-django-backend-tests
