name: librarian tidy

on:
  pull_request:

permissions:
  contents: read

jobs:
  tidy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: changes
        with:
          filters: |
            librarian:
              - 'librarian.yaml'

      -  uses: googleapis/librarian@main # zizmor: ignore[unpinned-uses]

      - name: Run librarian tidy
        if: steps.changes.outputs.librarian == 'true'
        run: librarian tidy

      - name: Check for diff
        if: steps.changes.outputs.librarian == 'true'
        run: |
          if ! git diff --exit-code; then
            V=$(go run github.com/googleapis/librarian/cmd/librarian@latest config get version)
            echo "librarian.yaml is not tidy. Please run:"
            echo ""
            echo "  go run github.com/googleapis/librarian/cmd/librarian@${V} tidy"
            echo ""
            echo "to tidy librarian.yaml and commit the changes."
            exit 1
          fi

