# Copyright 2025 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: A workflow for testing cross package compatibility using pex

# Controls when the action will run.

# Run this action anytime `gapic_version.py` is updated in main
on:
  push:
    paths:
      - '**/gapic_version.py'
    branches:
      - main
  # TODO: Remove this before merging
  pull_request:
    branches:
      - main
  

permissions:
  contents: read

jobs:
  build:
    permissions:
      issues: write # to open issues when compatibility issues are found
    name: Cross Package Compatibility using Pex
    runs-on: ubuntu-latest
    # don't run the workflow on forks of googleapis/google-cloud-python
    if: ${{github.repository == 'googleapis/google-cloud-python'}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install build dependencies
        run: pip install build wheel
      - name: Build wheels for all packages
        run: ./build_wheels.sh
        working-directory: ./scripts/test_cross_package_compatibility
      - name: Create requirements.txt file to install all packages from source
        run: ./create_requirements_file.sh
        working-directory: ./scripts/test_cross_package_compatibility
      - name: Create python file to be used during the compatibility check
        run: ./generate_test_code.sh
        working-directory: ./scripts/test_cross_package_compatibility
      - name: Install pex
        run: pip install pex
      - name: Install all packages and run compatibility check
        run: pex -r requirements.txt -- test_imports.py
        working-directory: ./scripts/test_cross_package_compatibility      
      # TODO : open github issue if there are failures
