# -*- coding: utf-8 -*-
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import google.api_core as api_core

from google.devicesandservices.health_v4 import gapic_version as package_version

__version__ = package_version.__version__

# PEP 0810: Explicit Lazy Imports
# Python 3.15+ natively intercepts and defers these imports.
# Developers can disable this behavior and force eager imports.
# For more information, see:
# https://docs.python.org/3.15/library/sys.html#sys.set_lazy_imports_filter
# Older Python versions safely ignore this variable.
__lazy_modules__ = {
    "google.devicesandservices.health_v4.services.data_points_service",
    "google.devicesandservices.health_v4.services.data_subscription_service",
    "google.devicesandservices.health_v4.services.health_profile_service",
    "google.devicesandservices.health_v4.types.data_coordinates",
    "google.devicesandservices.health_v4.types.data_model",
    "google.devicesandservices.health_v4.types.data_points",
    "google.devicesandservices.health_v4.types.data_source",
    "google.devicesandservices.health_v4.types.data_subscription_service",
    "google.devicesandservices.health_v4.types.health_profile",
    "google.devicesandservices.health_v4.types.medical_device_info",
    "google.devicesandservices.health_v4.types.webhook_notification_cloud_log",
}


from .services.data_points_service import (
    DataPointsServiceAsyncClient,
    DataPointsServiceClient,
)
from .services.data_subscription_service import (
    DataSubscriptionServiceAsyncClient,
    DataSubscriptionServiceClient,
)
from .services.health_profile_service import (
    HealthProfileServiceAsyncClient,
    HealthProfileServiceClient,
)
from .types.data_coordinates import (
    CivilDateTime,
    CivilTimeInterval,
    ObservationSampleTime,
    ObservationTimeInterval,
    SessionTimeInterval,
)
from .types.data_model import (
    ActiveEnergyBurned,
    ActiveEnergyBurnedRollupValue,
    ActiveMinutes,
    ActiveMinutesRollupValue,
    ActiveZoneMinutes,
    ActiveZoneMinutesRollupValue,
    ActivityLevel,
    ActivityLevelRollupValue,
    Altitude,
    AltitudeRollupValue,
    BasalEnergyBurned,
    BloodGlucose,
    BloodGlucoseRollupValue,
    BodyFat,
    BodyFatRollupValue,
    CaloriesInHeartRateZoneRollupValue,
    CoreBodyTemperature,
    CoreBodyTemperatureRollupValue,
    DailyHeartRateVariability,
    DailyHeartRateZones,
    DailyOxygenSaturation,
    DailyRespiratoryRate,
    DailyRestingHeartRate,
    DailySleepTemperatureDerivations,
    DailyVO2Max,
    Distance,
    DistanceRollupValue,
    Electrocardiogram,
    EnergyQuantity,
    EnergyUnit,
    Exercise,
    Floors,
    FloorsRollupValue,
    Food,
    FoodAccessLevel,
    FoodMeasurementUnit,
    HeartRate,
    HeartRateRollupValue,
    HeartRateVariability,
    HeartRateVariabilityPersonalRangeRollupValue,
    HeartRateZoneType,
    Height,
    HydrationLog,
    HydrationLogRollupValue,
    IrregularRhythmNotification,
    MealType,
    MenstrualPeriod,
    MetricsSummary,
    Moods,
    Nutrient,
    NutrientQuantity,
    NutritionLog,
    NutritionLogRollupValue,
    OvulationTest,
    OvulationTestResult,
    OxygenSaturation,
    RespiratoryRateSleepSummary,
    RestingHeartRatePersonalRangeRollupValue,
    RunVO2Max,
    RunVO2MaxRollupValue,
    SedentaryPeriod,
    SedentaryPeriodRollupValue,
    Sleep,
    Steps,
    StepsRollupValue,
    SwimLengthsData,
    SwimLengthsDataRollupValue,
    Symptoms,
    TimeInHeartRateZone,
    TimeInHeartRateZoneRollupValue,
    TotalCaloriesRollupValue,
    VO2Max,
    VolumeQuantity,
    VolumeUnit,
    Weight,
    WeightQuantity,
    WeightRollupValue,
    WeightUnit,
)
from .types.data_points import (
    BatchDeleteDataPointsOperationMetadata,
    BatchDeleteDataPointsRequest,
    BatchDeleteDataPointsResponse,
    CreateDataPointOperationMetadata,
    CreateDataPointRequest,
    DailyRollupDataPoint,
    DailyRollUpDataPointsRequest,
    DailyRollUpDataPointsResponse,
    DataPoint,
    DataType,
    ExportExerciseTcxRequest,
    ExportExerciseTcxResponse,
    GetDataPointRequest,
    ListDataPointsRequest,
    ListDataPointsResponse,
    ReconcileDataPointsRequest,
    ReconcileDataPointsResponse,
    ReconciledDataPoint,
    RollupDataPoint,
    RollUpDataPointsRequest,
    RollUpDataPointsResponse,
    UpdateDataPointOperationMetadata,
    UpdateDataPointRequest,
)
from .types.data_source import DataSource
from .types.data_subscription_service import (
    CreateSubscriberMetadata,
    CreateSubscriberPayload,
    CreateSubscriberRequest,
    CreateSubscriptionPayload,
    CreateSubscriptionRequest,
    DeleteSubscriberMetadata,
    DeleteSubscriberRequest,
    DeleteSubscriptionRequest,
    EndpointAuthorization,
    ListSubscribersRequest,
    ListSubscribersResponse,
    ListSubscriptionsRequest,
    ListSubscriptionsResponse,
    Subscriber,
    SubscriberConfig,
    Subscription,
    UpdateSubscriberMetadata,
    UpdateSubscriberRequest,
    UpdateSubscriptionRequest,
)
from .types.health_profile import (
    GetIdentityRequest,
    GetIrnProfileRequest,
    GetPairedDeviceRequest,
    GetProfileRequest,
    GetSettingsRequest,
    Identity,
    IrnProfile,
    ListPairedDevicesRequest,
    ListPairedDevicesResponse,
    PairedDevice,
    Profile,
    Settings,
    UpdateProfileRequest,
    UpdateSettingsRequest,
    User,
)
from .types.medical_device_info import MedicalDeviceInfo
from .types.webhook_notification_cloud_log import WebhookNotificationCloudLog

__all__ = (
    "DataPointsServiceAsyncClient",
    "DataSubscriptionServiceAsyncClient",
    "HealthProfileServiceAsyncClient",
    "ActiveEnergyBurned",
    "ActiveEnergyBurnedRollupValue",
    "ActiveMinutes",
    "ActiveMinutesRollupValue",
    "ActiveZoneMinutes",
    "ActiveZoneMinutesRollupValue",
    "ActivityLevel",
    "ActivityLevelRollupValue",
    "Altitude",
    "AltitudeRollupValue",
    "BasalEnergyBurned",
    "BatchDeleteDataPointsOperationMetadata",
    "BatchDeleteDataPointsRequest",
    "BatchDeleteDataPointsResponse",
    "BloodGlucose",
    "BloodGlucoseRollupValue",
    "BodyFat",
    "BodyFatRollupValue",
    "CaloriesInHeartRateZoneRollupValue",
    "CivilDateTime",
    "CivilTimeInterval",
    "CoreBodyTemperature",
    "CoreBodyTemperatureRollupValue",
    "CreateDataPointOperationMetadata",
    "CreateDataPointRequest",
    "CreateSubscriberMetadata",
    "CreateSubscriberPayload",
    "CreateSubscriberRequest",
    "CreateSubscriptionPayload",
    "CreateSubscriptionRequest",
    "DailyHeartRateVariability",
    "DailyHeartRateZones",
    "DailyOxygenSaturation",
    "DailyRespiratoryRate",
    "DailyRestingHeartRate",
    "DailyRollUpDataPointsRequest",
    "DailyRollUpDataPointsResponse",
    "DailyRollupDataPoint",
    "DailySleepTemperatureDerivations",
    "DailyVO2Max",
    "DataPoint",
    "DataPointsServiceClient",
    "DataSource",
    "DataSubscriptionServiceClient",
    "DataType",
    "DeleteSubscriberMetadata",
    "DeleteSubscriberRequest",
    "DeleteSubscriptionRequest",
    "Distance",
    "DistanceRollupValue",
    "Electrocardiogram",
    "EndpointAuthorization",
    "EnergyQuantity",
    "EnergyUnit",
    "Exercise",
    "ExportExerciseTcxRequest",
    "ExportExerciseTcxResponse",
    "Floors",
    "FloorsRollupValue",
    "Food",
    "FoodAccessLevel",
    "FoodMeasurementUnit",
    "GetDataPointRequest",
    "GetIdentityRequest",
    "GetIrnProfileRequest",
    "GetPairedDeviceRequest",
    "GetProfileRequest",
    "GetSettingsRequest",
    "HealthProfileServiceClient",
    "HeartRate",
    "HeartRateRollupValue",
    "HeartRateVariability",
    "HeartRateVariabilityPersonalRangeRollupValue",
    "HeartRateZoneType",
    "Height",
    "HydrationLog",
    "HydrationLogRollupValue",
    "Identity",
    "IrnProfile",
    "IrregularRhythmNotification",
    "ListDataPointsRequest",
    "ListDataPointsResponse",
    "ListPairedDevicesRequest",
    "ListPairedDevicesResponse",
    "ListSubscribersRequest",
    "ListSubscribersResponse",
    "ListSubscriptionsRequest",
    "ListSubscriptionsResponse",
    "MealType",
    "MedicalDeviceInfo",
    "MenstrualPeriod",
    "MetricsSummary",
    "Moods",
    "Nutrient",
    "NutrientQuantity",
    "NutritionLog",
    "NutritionLogRollupValue",
    "ObservationSampleTime",
    "ObservationTimeInterval",
    "OvulationTest",
    "OvulationTestResult",
    "OxygenSaturation",
    "PairedDevice",
    "Profile",
    "ReconcileDataPointsRequest",
    "ReconcileDataPointsResponse",
    "ReconciledDataPoint",
    "RespiratoryRateSleepSummary",
    "RestingHeartRatePersonalRangeRollupValue",
    "RollUpDataPointsRequest",
    "RollUpDataPointsResponse",
    "RollupDataPoint",
    "RunVO2Max",
    "RunVO2MaxRollupValue",
    "SedentaryPeriod",
    "SedentaryPeriodRollupValue",
    "SessionTimeInterval",
    "Settings",
    "Sleep",
    "Steps",
    "StepsRollupValue",
    "Subscriber",
    "SubscriberConfig",
    "Subscription",
    "SwimLengthsData",
    "SwimLengthsDataRollupValue",
    "Symptoms",
    "TimeInHeartRateZone",
    "TimeInHeartRateZoneRollupValue",
    "TotalCaloriesRollupValue",
    "UpdateDataPointOperationMetadata",
    "UpdateDataPointRequest",
    "UpdateProfileRequest",
    "UpdateSettingsRequest",
    "UpdateSubscriberMetadata",
    "UpdateSubscriberRequest",
    "UpdateSubscriptionRequest",
    "User",
    "VO2Max",
    "VolumeQuantity",
    "VolumeUnit",
    "WebhookNotificationCloudLog",
    "Weight",
    "WeightQuantity",
    "WeightRollupValue",
    "WeightUnit",
)

api_core.check_python_version("google.devicesandservices.health_v4")
api_core.check_dependency_versions("google.devicesandservices.health_v4")
